#!/bin/bash
# Uninstall script for Visual Paradigm
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Visual Paradigm..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Visual Paradigm if running..."
pkill -f "Visual Paradigm" 2>/dev/null || true

# Remove /Applications/Visual Paradigm.app
echo "Removing /Applications/Visual Paradigm.app..."
if [ -d "/Applications/Visual Paradigm.app" ]; then
    rm -rf "/Applications/Visual Paradigm.app" 2>/dev/null || true
elif [ -f "/Applications/Visual Paradigm.app" ]; then
    rm -f "/Applications/Visual Paradigm.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Visual Paradigm
echo "Removing $HOME/Library/Application Support/Visual Paradigm..."
if [ -d "$HOME/Library/Application Support/Visual Paradigm" ]; then
    rm -rf "$HOME/Library/Application Support/Visual Paradigm" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Visual Paradigm" ]; then
    rm -f "$HOME/Library/Application Support/Visual Paradigm" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/VisualParadigm
echo "Removing $HOME/Library/Application Support/VisualParadigm..."
if [ -d "$HOME/Library/Application Support/VisualParadigm" ]; then
    rm -rf "$HOME/Library/Application Support/VisualParadigm" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/VisualParadigm" ]; then
    rm -f "$HOME/Library/Application Support/VisualParadigm" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.install4j.1106-5897-7327-6550.5.savedState
echo "Removing $HOME/Library/Saved Application State/com.install4j.1106-5897-7327-6550.5.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.install4j.1106-5897-7327-6550.5.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.install4j.1106-5897-7327-6550.5.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.install4j.1106-5897-7327-6550.5.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.install4j.1106-5897-7327-6550.5.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
