#!/bin/bash
# Uninstall script for Arq
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Arq..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Arq if running..."
pkill -f "Arq" 2>/dev/null || true

# Unload service com.haystacksoftware.arqagent
echo "Unloading service com.haystacksoftware.arqagent..."
launchctl unload -w /Library/LaunchAgents/com.haystacksoftware.arqagent.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.haystacksoftware.arqagent.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.haystacksoftware.arqagent.plist 2>/dev/null || true

# Unload service com.haystacksoftware.ArqMonitor
echo "Unloading service com.haystacksoftware.ArqMonitor..."
launchctl unload -w /Library/LaunchAgents/com.haystacksoftware.ArqMonitor.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.haystacksoftware.ArqMonitor.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.haystacksoftware.ArqMonitor.plist 2>/dev/null || true

# Kill application with bundle ID com.haystacksoftware.Arq if running
echo "Stopping application with bundle ID com.haystacksoftware.Arq if running..."
killall -9 "com.haystacksoftware.Arq" 2>/dev/null || true

# Remove binary /Applications/Arq.app/Arq.app/Contents/Resources/arqc
echo "Removing binary /Applications/Arq.app/Arq.app/Contents/Resources/arqc..."
if [ -f "/Applications/Arq.app/Arq.app/Contents/Resources/arqc" ]; then
    rm -f "/Applications/Arq.app/Arq.app/Contents/Resources/arqc" 2>/dev/null || true
fi

# Remove /Library/Application Support/ArqAgent
echo "Removing /Library/Application Support/ArqAgent..."
if [ -d "/Library/Application Support/ArqAgent" ]; then
    rm -rf "/Library/Application Support/ArqAgent" 2>/dev/null || true
elif [ -f "/Library/Application Support/ArqAgent" ]; then
    rm -f "/Library/Application Support/ArqAgent" 2>/dev/null || true
fi

# Remove /Library/Application Support/ArqAgentAPFS
echo "Removing /Library/Application Support/ArqAgentAPFS..."
if [ -d "/Library/Application Support/ArqAgentAPFS" ]; then
    rm -rf "/Library/Application Support/ArqAgentAPFS" 2>/dev/null || true
elif [ -f "/Library/Application Support/ArqAgentAPFS" ]; then
    rm -f "/Library/Application Support/ArqAgentAPFS" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Arq *
echo "Removing $HOME/Library/Application Support/Arq *..."
if [ -d "$HOME/Library/Application Support/Arq *" ]; then
    rm -rf "$HOME/Library/Application Support/Arq *" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Arq *" ]; then
    rm -f "$HOME/Library/Application Support/Arq *" 2>/dev/null || true
fi

# Remove $HOME/Library/Arq *
echo "Removing $HOME/Library/Arq *..."
if [ -d "$HOME/Library/Arq *" ]; then
    rm -rf "$HOME/Library/Arq *" 2>/dev/null || true
elif [ -f "$HOME/Library/Arq *" ]; then
    rm -f "$HOME/Library/Arq *" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.haystacksoftware.Arq.plist
echo "Removing $HOME/Library/Preferences/com.haystacksoftware.Arq.plist..."
if [ -d "$HOME/Library/Preferences/com.haystacksoftware.Arq.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.haystacksoftware.Arq.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.haystacksoftware.Arq.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.haystacksoftware.Arq.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.haystacksoftware.ArqMonitor.plist
echo "Removing $HOME/Library/Preferences/com.haystacksoftware.ArqMonitor.plist..."
if [ -d "$HOME/Library/Preferences/com.haystacksoftware.ArqMonitor.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.haystacksoftware.ArqMonitor.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.haystacksoftware.ArqMonitor.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.haystacksoftware.ArqMonitor.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
