#!/bin/bash
# Uninstall script for Lark
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Lark..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Lark if running..."
pkill -f "Lark" 2>/dev/null || true

# Remove /Applications/LarkSuite.app
echo "Removing /Applications/LarkSuite.app..."
if [ -d "/Applications/LarkSuite.app" ]; then
    rm -rf "/Applications/LarkSuite.app" 2>/dev/null || true
elif [ -f "/Applications/LarkSuite.app" ]; then
    rm -f "/Applications/LarkSuite.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.electron.lark
echo "Removing $HOME/Library/Caches/com.electron.lark..."
if [ -d "$HOME/Library/Caches/com.electron.lark" ]; then
    rm -rf "$HOME/Library/Caches/com.electron.lark" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.electron.lark" ]; then
    rm -f "$HOME/Library/Caches/com.electron.lark" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.electron.lark.helper
echo "Removing $HOME/Library/Caches/com.electron.lark.helper..."
if [ -d "$HOME/Library/Caches/com.electron.lark.helper" ]; then
    rm -rf "$HOME/Library/Caches/com.electron.lark.helper" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.electron.lark.helper" ]; then
    rm -f "$HOME/Library/Caches/com.electron.lark.helper" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.electron.lark.helper.plist
echo "Removing $HOME/Library/Preferences/com.electron.lark.helper.plist..."
if [ -d "$HOME/Library/Preferences/com.electron.lark.helper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.electron.lark.helper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.electron.lark.helper.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.electron.lark.helper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.electron.lark.savedState
echo "Removing $HOME/Library/Saved Application State/com.electron.lark.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.electron.lark.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.electron.lark.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.electron.lark.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.electron.lark.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
