#!/bin/bash
# Uninstall script for ComfyUI
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling ComfyUI..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping ComfyUI if running..."
pkill -f "ComfyUI" 2>/dev/null || true

# Remove /Applications/ComfyUI.app
echo "Removing /Applications/ComfyUI.app..."
if [ -d "/Applications/ComfyUI.app" ]; then
    rm -rf "/Applications/ComfyUI.app" 2>/dev/null || true
elif [ -f "/Applications/ComfyUI.app" ]; then
    rm -f "/Applications/ComfyUI.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/ComfyUI
echo "Removing $HOME/Library/Application Support/ComfyUI..."
if [ -d "$HOME/Library/Application Support/ComfyUI" ]; then
    rm -rf "$HOME/Library/Application Support/ComfyUI" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/ComfyUI" ]; then
    rm -f "$HOME/Library/Application Support/ComfyUI" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/ComfyUI
echo "Removing $HOME/Library/Logs/ComfyUI..."
if [ -d "$HOME/Library/Logs/ComfyUI" ]; then
    rm -rf "$HOME/Library/Logs/ComfyUI" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/ComfyUI" ]; then
    rm -f "$HOME/Library/Logs/ComfyUI" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
