#!/bin/bash
# Uninstall script for NetBeans IDE
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling NetBeans IDE..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping NetBeans IDE if running..."
pkill -f "NetBeans IDE" 2>/dev/null || true

# Remove $HOME/Library/Application Support/NetBeans
echo "Removing $HOME/Library/Application Support/NetBeans..."
if [ -d "$HOME/Library/Application Support/NetBeans" ]; then
    rm -rf "$HOME/Library/Application Support/NetBeans" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/NetBeans" ]; then
    rm -f "$HOME/Library/Application Support/NetBeans" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/NetBeans
echo "Removing $HOME/Library/Caches/NetBeans..."
if [ -d "$HOME/Library/Caches/NetBeans" ]; then
    rm -rf "$HOME/Library/Caches/NetBeans" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/NetBeans" ]; then
    rm -f "$HOME/Library/Caches/NetBeans" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
