#!/bin/bash
# Uninstall script for ELAN
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling ELAN..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping ELAN if running..."
pkill -f "ELAN" 2>/dev/null || true

# Remove /Applications/ELAN_7-0_M1_mac/ELAN_7.0.app
echo "Removing /Applications/ELAN_7-0_M1_mac/ELAN_7.0.app..."
if [ -d "/Applications/ELAN_7-0_M1_mac/ELAN_7.0.app" ]; then
    rm -rf "/Applications/ELAN_7-0_M1_mac/ELAN_7.0.app" 2>/dev/null || true
elif [ -f "/Applications/ELAN_7-0_M1_mac/ELAN_7.0.app" ]; then
    rm -f "/Applications/ELAN_7-0_M1_mac/ELAN_7.0.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/ELAN
echo "Removing $HOME/Library/Preferences/ELAN..."
if [ -d "$HOME/Library/Preferences/ELAN" ]; then
    rm -rf "$HOME/Library/Preferences/ELAN" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/ELAN" ]; then
    rm -f "$HOME/Library/Preferences/ELAN" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/nl.mpi.elan.plist
echo "Removing $HOME/Library/Preferences/nl.mpi.elan.plist..."
if [ -d "$HOME/Library/Preferences/nl.mpi.elan.plist" ]; then
    rm -rf "$HOME/Library/Preferences/nl.mpi.elan.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/nl.mpi.elan.plist" ]; then
    rm -f "$HOME/Library/Preferences/nl.mpi.elan.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
