#!/bin/bash
# Uninstall script for Battery Buddy
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Battery Buddy..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Battery Buddy if running..."
pkill -f "Battery Buddy" 2>/dev/null || true

# Remove /Applications/Battery Buddy.app
echo "Removing /Applications/Battery Buddy.app..."
if [ -d "/Applications/Battery Buddy.app" ]; then
    rm -rf "/Applications/Battery Buddy.app" 2>/dev/null || true
elif [ -f "/Applications/Battery Buddy.app" ]; then
    rm -f "/Applications/Battery Buddy.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.NeilSardesai.Battery-Buddy-Helper
echo "Removing $HOME/Library/Application Scripts/com.NeilSardesai.Battery-Buddy-Helper..."
if [ -d "$HOME/Library/Application Scripts/com.NeilSardesai.Battery-Buddy-Helper" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.NeilSardesai.Battery-Buddy-Helper" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.NeilSardesai.Battery-Buddy-Helper" ]; then
    rm -f "$HOME/Library/Application Scripts/com.NeilSardesai.Battery-Buddy-Helper" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.NeilSardesai.Battery-Buddy-Helper
echo "Removing $HOME/Library/Containers/com.NeilSardesai.Battery-Buddy-Helper..."
if [ -d "$HOME/Library/Containers/com.NeilSardesai.Battery-Buddy-Helper" ]; then
    rm -rf "$HOME/Library/Containers/com.NeilSardesai.Battery-Buddy-Helper" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.NeilSardesai.Battery-Buddy-Helper" ]; then
    rm -f "$HOME/Library/Containers/com.NeilSardesai.Battery-Buddy-Helper" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.NeilSardesai.Battery-Buddy.plist
echo "Removing $HOME/Library/Preferences/com.NeilSardesai.Battery-Buddy.plist..."
if [ -d "$HOME/Library/Preferences/com.NeilSardesai.Battery-Buddy.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.NeilSardesai.Battery-Buddy.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.NeilSardesai.Battery-Buddy.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.NeilSardesai.Battery-Buddy.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
