#!/bin/bash
# Uninstall script for Pitch
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Pitch..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Pitch if running..."
pkill -f "Pitch" 2>/dev/null || true

# Remove /Applications/Pitch.app
echo "Removing /Applications/Pitch.app..."
if [ -d "/Applications/Pitch.app" ]; then
    rm -rf "/Applications/Pitch.app" 2>/dev/null || true
elif [ -f "/Applications/Pitch.app" ]; then
    rm -f "/Applications/Pitch.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Pitch
echo "Removing $HOME/Library/Application Support/Pitch..."
if [ -d "$HOME/Library/Application Support/Pitch" ]; then
    rm -rf "$HOME/Library/Application Support/Pitch" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Pitch" ]; then
    rm -f "$HOME/Library/Application Support/Pitch" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Pitch
echo "Removing $HOME/Library/Logs/Pitch..."
if [ -d "$HOME/Library/Logs/Pitch" ]; then
    rm -rf "$HOME/Library/Logs/Pitch" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Pitch" ]; then
    rm -f "$HOME/Library/Logs/Pitch" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/io.pitch.pitch-macos.plist
echo "Removing $HOME/Library/Preferences/io.pitch.pitch-macos.plist..."
if [ -d "$HOME/Library/Preferences/io.pitch.pitch-macos.plist" ]; then
    rm -rf "$HOME/Library/Preferences/io.pitch.pitch-macos.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/io.pitch.pitch-macos.plist" ]; then
    rm -f "$HOME/Library/Preferences/io.pitch.pitch-macos.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/io.pitch.pitch-macos.savedState
echo "Removing $HOME/Library/Saved Application State/io.pitch.pitch-macos.savedState..."
if [ -d "$HOME/Library/Saved Application State/io.pitch.pitch-macos.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/io.pitch.pitch-macos.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/io.pitch.pitch-macos.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/io.pitch.pitch-macos.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
