#!/bin/bash
# Uninstall script for Amethyst
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Amethyst..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Amethyst if running..."
pkill -f "Amethyst" 2>/dev/null || true

# Remove /Applications/Amethyst.app
echo "Removing /Applications/Amethyst.app..."
if [ -d "/Applications/Amethyst.app" ]; then
    rm -rf "/Applications/Amethyst.app" 2>/dev/null || true
elif [ -f "/Applications/Amethyst.app" ]; then
    rm -f "/Applications/Amethyst.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Amethyst
echo "Removing $HOME/Library/Application Support/Amethyst..."
if [ -d "$HOME/Library/Application Support/Amethyst" ]; then
    rm -rf "$HOME/Library/Application Support/Amethyst" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Amethyst" ]; then
    rm -f "$HOME/Library/Application Support/Amethyst" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.amethyst.amethyst.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.amethyst.amethyst.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.amethyst.amethyst.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.amethyst.amethyst.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.amethyst.amethyst.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.amethyst.amethyst.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.amethyst.Amethyst
echo "Removing $HOME/Library/Caches/com.amethyst.Amethyst..."
if [ -d "$HOME/Library/Caches/com.amethyst.Amethyst" ]; then
    rm -rf "$HOME/Library/Caches/com.amethyst.Amethyst" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.amethyst.Amethyst" ]; then
    rm -f "$HOME/Library/Caches/com.amethyst.Amethyst" 2>/dev/null || true
fi

# Remove $HOME/Library/Cookies/com.amethyst.Amethyst.binarycookies
echo "Removing $HOME/Library/Cookies/com.amethyst.Amethyst.binarycookies..."
if [ -d "$HOME/Library/Cookies/com.amethyst.Amethyst.binarycookies" ]; then
    rm -rf "$HOME/Library/Cookies/com.amethyst.Amethyst.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/Cookies/com.amethyst.Amethyst.binarycookies" ]; then
    rm -f "$HOME/Library/Cookies/com.amethyst.Amethyst.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.amethyst.Amethyst
echo "Removing $HOME/Library/HTTPStorages/com.amethyst.Amethyst..."
if [ -d "$HOME/Library/HTTPStorages/com.amethyst.Amethyst" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.amethyst.Amethyst" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.amethyst.Amethyst" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.amethyst.Amethyst" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.amethyst.Amethyst.plist
echo "Removing $HOME/Library/Preferences/com.amethyst.Amethyst.plist..."
if [ -d "$HOME/Library/Preferences/com.amethyst.Amethyst.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.amethyst.Amethyst.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.amethyst.Amethyst.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.amethyst.Amethyst.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
