#!/bin/bash
# Uninstall script for Google Antigravity
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Google Antigravity..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Google Antigravity if running..."
pkill -f "Google Antigravity" 2>/dev/null || true

# Kill application with bundle ID com.google.antigravity if running
echo "Stopping application with bundle ID com.google.antigravity if running..."
killall -9 "com.google.antigravity" 2>/dev/null || true

# Remove /Applications/Antigravity.app
echo "Removing /Applications/Antigravity.app..."
if [ -d "/Applications/Antigravity.app" ]; then
    rm -rf "/Applications/Antigravity.app" 2>/dev/null || true
elif [ -f "/Applications/Antigravity.app" ]; then
    rm -f "/Applications/Antigravity.app" 2>/dev/null || true
fi

# Remove $HOME/.antigravity
echo "Removing $HOME/.antigravity..."
if [ -d "$HOME/.antigravity" ]; then
    rm -rf "$HOME/.antigravity" 2>/dev/null || true
elif [ -f "$HOME/.antigravity" ]; then
    rm -f "$HOME/.antigravity" 2>/dev/null || true
fi

# Remove $HOME/.gemini/antigravity
echo "Removing $HOME/.gemini/antigravity..."
if [ -d "$HOME/.gemini/antigravity" ]; then
    rm -rf "$HOME/.gemini/antigravity" 2>/dev/null || true
elif [ -f "$HOME/.gemini/antigravity" ]; then
    rm -f "$HOME/.gemini/antigravity" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Antigravity
echo "Removing $HOME/Library/Application Support/Antigravity..."
if [ -d "$HOME/Library/Application Support/Antigravity" ]; then
    rm -rf "$HOME/Library/Application Support/Antigravity" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Antigravity" ]; then
    rm -f "$HOME/Library/Application Support/Antigravity" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.google.antigravity.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.google.antigravity.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.google.antigravity.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.google.antigravity.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.google.antigravity.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.google.antigravity.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.google.antigravity
echo "Removing $HOME/Library/Caches/com.google.antigravity..."
if [ -d "$HOME/Library/Caches/com.google.antigravity" ]; then
    rm -rf "$HOME/Library/Caches/com.google.antigravity" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.google.antigravity" ]; then
    rm -f "$HOME/Library/Caches/com.google.antigravity" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.google.antigravity.ShipIt
echo "Removing $HOME/Library/Caches/com.google.antigravity.ShipIt..."
if [ -d "$HOME/Library/Caches/com.google.antigravity.ShipIt" ]; then
    rm -rf "$HOME/Library/Caches/com.google.antigravity.ShipIt" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.google.antigravity.ShipIt" ]; then
    rm -f "$HOME/Library/Caches/com.google.antigravity.ShipIt" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.google.antigravity
echo "Removing $HOME/Library/HTTPStorages/com.google.antigravity..."
if [ -d "$HOME/Library/HTTPStorages/com.google.antigravity" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.google.antigravity" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.google.antigravity" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.google.antigravity" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Antigravity
echo "Removing $HOME/Library/Logs/Antigravity..."
if [ -d "$HOME/Library/Logs/Antigravity" ]; then
    rm -rf "$HOME/Library/Logs/Antigravity" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Antigravity" ]; then
    rm -f "$HOME/Library/Logs/Antigravity" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/ByHost/com.google.antigravity.ShipIt.*.plist
echo "Removing $HOME/Library/Preferences/ByHost/com.google.antigravity.ShipIt.*.plist..."
if [ -d "$HOME/Library/Preferences/ByHost/com.google.antigravity.ShipIt.*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/ByHost/com.google.antigravity.ShipIt.*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/ByHost/com.google.antigravity.ShipIt.*.plist" ]; then
    rm -f "$HOME/Library/Preferences/ByHost/com.google.antigravity.ShipIt.*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.google.antigravity.plist
echo "Removing $HOME/Library/Preferences/com.google.antigravity.plist..."
if [ -d "$HOME/Library/Preferences/com.google.antigravity.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.google.antigravity.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.google.antigravity.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.google.antigravity.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.google.Antigravity.savedState
echo "Removing $HOME/Library/Saved Application State/com.google.Antigravity.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.google.Antigravity.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.google.Antigravity.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.google.Antigravity.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.google.Antigravity.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
