#!/bin/bash
# Uninstall script for Butler
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Butler..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Butler if running..."
pkill -f "Butler" 2>/dev/null || true

# Remove /Applications/Butler.app
echo "Removing /Applications/Butler.app..."
if [ -d "/Applications/Butler.app" ]; then
    rm -rf "/Applications/Butler.app" 2>/dev/null || true
elif [ -f "/Applications/Butler.app" ]; then
    rm -f "/Applications/Butler.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Butler
echo "Removing $HOME/Library/Application Support/Butler..."
if [ -d "$HOME/Library/Application Support/Butler" ]; then
    rm -rf "$HOME/Library/Application Support/Butler" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Butler" ]; then
    rm -f "$HOME/Library/Application Support/Butler" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.manytricks.Butler
echo "Removing $HOME/Library/HTTPStorages/com.manytricks.Butler..."
if [ -d "$HOME/Library/HTTPStorages/com.manytricks.Butler" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.manytricks.Butler" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.manytricks.Butler" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.manytricks.Butler" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.manytricks.Butler.plist
echo "Removing $HOME/Library/Preferences/com.manytricks.Butler.plist..."
if [ -d "$HOME/Library/Preferences/com.manytricks.Butler.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.manytricks.Butler.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.manytricks.Butler.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.manytricks.Butler.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
