#!/bin/bash
# Uninstall script for sbarex QLMarkdown
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling sbarex QLMarkdown..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping sbarex QLMarkdown if running..."
pkill -f "sbarex QLMarkdown" 2>/dev/null || true

# Kill application with bundle ID org.sbarex.QLMarkdown if running
echo "Stopping application with bundle ID org.sbarex.QLMarkdown if running..."
killall -9 "org.sbarex.QLMarkdown" 2>/dev/null || true

# Remove /Applications/QLMarkdown.app
echo "Removing /Applications/QLMarkdown.app..."
if [ -d "/Applications/QLMarkdown.app" ]; then
    rm -rf "/Applications/QLMarkdown.app" 2>/dev/null || true
elif [ -f "/Applications/QLMarkdown.app" ]; then
    rm -f "/Applications/QLMarkdown.app" 2>/dev/null || true
fi

# Remove binary /Applications/sbarex QLMarkdown.app/QLMarkdown.app/Contents/Resources/qlmarkdown_cli
echo "Removing binary /Applications/sbarex QLMarkdown.app/QLMarkdown.app/Contents/Resources/qlmarkdown_cli..."
if [ -f "/Applications/sbarex QLMarkdown.app/QLMarkdown.app/Contents/Resources/qlmarkdown_cli" ]; then
    rm -f "/Applications/sbarex QLMarkdown.app/QLMarkdown.app/Contents/Resources/qlmarkdown_cli" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/group.org.sbarex.qlmarkdown
echo "Removing $HOME/Library/Application Scripts/group.org.sbarex.qlmarkdown..."
if [ -d "$HOME/Library/Application Scripts/group.org.sbarex.qlmarkdown" ]; then
    rm -rf "$HOME/Library/Application Scripts/group.org.sbarex.qlmarkdown" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/group.org.sbarex.qlmarkdown" ]; then
    rm -f "$HOME/Library/Application Scripts/group.org.sbarex.qlmarkdown" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/org.sbarex.QLMarkdown
echo "Removing $HOME/Library/Application Scripts/org.sbarex.QLMarkdown..."
if [ -d "$HOME/Library/Application Scripts/org.sbarex.QLMarkdown" ]; then
    rm -rf "$HOME/Library/Application Scripts/org.sbarex.QLMarkdown" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/org.sbarex.QLMarkdown" ]; then
    rm -f "$HOME/Library/Application Scripts/org.sbarex.QLMarkdown" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/org.sbarex.QLMarkdown.QLExtension
echo "Removing $HOME/Library/Application Scripts/org.sbarex.QLMarkdown.QLExtension..."
if [ -d "$HOME/Library/Application Scripts/org.sbarex.QLMarkdown.QLExtension" ]; then
    rm -rf "$HOME/Library/Application Scripts/org.sbarex.QLMarkdown.QLExtension" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/org.sbarex.QLMarkdown.QLExtension" ]; then
    rm -f "$HOME/Library/Application Scripts/org.sbarex.QLMarkdown.QLExtension" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/org.sbarex.QLMarkdown.Shortcut-Extension
echo "Removing $HOME/Library/Application Scripts/org.sbarex.QLMarkdown.Shortcut-Extension..."
if [ -d "$HOME/Library/Application Scripts/org.sbarex.QLMarkdown.Shortcut-Extension" ]; then
    rm -rf "$HOME/Library/Application Scripts/org.sbarex.QLMarkdown.Shortcut-Extension" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/org.sbarex.QLMarkdown.Shortcut-Extension" ]; then
    rm -f "$HOME/Library/Application Scripts/org.sbarex.QLMarkdown.Shortcut-Extension" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/QLMarkdown
echo "Removing $HOME/Library/Application Support/QLMarkdown..."
if [ -d "$HOME/Library/Application Support/QLMarkdown" ]; then
    rm -rf "$HOME/Library/Application Support/QLMarkdown" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/QLMarkdown" ]; then
    rm -f "$HOME/Library/Application Support/QLMarkdown" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/org.sbarex.QLMarkdown
echo "Removing $HOME/Library/Containers/org.sbarex.QLMarkdown..."
if [ -d "$HOME/Library/Containers/org.sbarex.QLMarkdown" ]; then
    rm -rf "$HOME/Library/Containers/org.sbarex.QLMarkdown" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/org.sbarex.QLMarkdown" ]; then
    rm -f "$HOME/Library/Containers/org.sbarex.QLMarkdown" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/org.sbarex.QLMarkdown.QLExtension
echo "Removing $HOME/Library/Containers/org.sbarex.QLMarkdown.QLExtension..."
if [ -d "$HOME/Library/Containers/org.sbarex.QLMarkdown.QLExtension" ]; then
    rm -rf "$HOME/Library/Containers/org.sbarex.QLMarkdown.QLExtension" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/org.sbarex.QLMarkdown.QLExtension" ]; then
    rm -f "$HOME/Library/Containers/org.sbarex.QLMarkdown.QLExtension" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/org.sbarex.QLMarkdown.Shortcut-Extension
echo "Removing $HOME/Library/Containers/org.sbarex.QLMarkdown.Shortcut-Extension..."
if [ -d "$HOME/Library/Containers/org.sbarex.QLMarkdown.Shortcut-Extension" ]; then
    rm -rf "$HOME/Library/Containers/org.sbarex.QLMarkdown.Shortcut-Extension" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/org.sbarex.QLMarkdown.Shortcut-Extension" ]; then
    rm -f "$HOME/Library/Containers/org.sbarex.QLMarkdown.Shortcut-Extension" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/group.org.sbarex.qlmarkdown
echo "Removing $HOME/Library/Group Containers/group.org.sbarex.qlmarkdown..."
if [ -d "$HOME/Library/Group Containers/group.org.sbarex.qlmarkdown" ]; then
    rm -rf "$HOME/Library/Group Containers/group.org.sbarex.qlmarkdown" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/group.org.sbarex.qlmarkdown" ]; then
    rm -f "$HOME/Library/Group Containers/group.org.sbarex.qlmarkdown" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/org.sbarex.QLMarkdown
echo "Removing $HOME/Library/Group Containers/org.sbarex.QLMarkdown..."
if [ -d "$HOME/Library/Group Containers/org.sbarex.QLMarkdown" ]; then
    rm -rf "$HOME/Library/Group Containers/org.sbarex.QLMarkdown" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/org.sbarex.QLMarkdown" ]; then
    rm -f "$HOME/Library/Group Containers/org.sbarex.QLMarkdown" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/org.sbarex.qlmarkdown
echo "Removing $HOME/Library/Group Containers/org.sbarex.qlmarkdown..."
if [ -d "$HOME/Library/Group Containers/org.sbarex.qlmarkdown" ]; then
    rm -rf "$HOME/Library/Group Containers/org.sbarex.qlmarkdown" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/org.sbarex.qlmarkdown" ]; then
    rm -f "$HOME/Library/Group Containers/org.sbarex.qlmarkdown" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/org.sbarex.QLMarkdown.plist
echo "Removing $HOME/Library/Preferences/org.sbarex.QLMarkdown.plist..."
if [ -d "$HOME/Library/Preferences/org.sbarex.QLMarkdown.plist" ]; then
    rm -rf "$HOME/Library/Preferences/org.sbarex.QLMarkdown.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/org.sbarex.QLMarkdown.plist" ]; then
    rm -f "$HOME/Library/Preferences/org.sbarex.QLMarkdown.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/org.sbarex.QLMarkdownXPCHelper.plist
echo "Removing $HOME/Library/Preferences/org.sbarex.QLMarkdownXPCHelper.plist..."
if [ -d "$HOME/Library/Preferences/org.sbarex.QLMarkdownXPCHelper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/org.sbarex.QLMarkdownXPCHelper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/org.sbarex.QLMarkdownXPCHelper.plist" ]; then
    rm -f "$HOME/Library/Preferences/org.sbarex.QLMarkdownXPCHelper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/QuickLook/QLMarkdown.qlgenerator
echo "Removing $HOME/Library/QuickLook/QLMarkdown.qlgenerator..."
if [ -d "$HOME/Library/QuickLook/QLMarkdown.qlgenerator" ]; then
    rm -rf "$HOME/Library/QuickLook/QLMarkdown.qlgenerator" 2>/dev/null || true
elif [ -f "$HOME/Library/QuickLook/QLMarkdown.qlgenerator" ]; then
    rm -f "$HOME/Library/QuickLook/QLMarkdown.qlgenerator" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
