#!/bin/bash
# Uninstall script for WorkFlowy
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling WorkFlowy..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping WorkFlowy if running..."
pkill -f "WorkFlowy" 2>/dev/null || true

# Remove /Applications/WorkFlowy.app
echo "Removing /Applications/WorkFlowy.app..."
if [ -d "/Applications/WorkFlowy.app" ]; then
    rm -rf "/Applications/WorkFlowy.app" 2>/dev/null || true
elif [ -f "/Applications/WorkFlowy.app" ]; then
    rm -f "/Applications/WorkFlowy.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/WorkFlowy
echo "Removing $HOME/Library/Application Support/WorkFlowy..."
if [ -d "$HOME/Library/Application Support/WorkFlowy" ]; then
    rm -rf "$HOME/Library/Application Support/WorkFlowy" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/WorkFlowy" ]; then
    rm -f "$HOME/Library/Application Support/WorkFlowy" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.workflowy.desktop.plist
echo "Removing $HOME/Library/Preferences/com.workflowy.desktop.plist..."
if [ -d "$HOME/Library/Preferences/com.workflowy.desktop.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.workflowy.desktop.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.workflowy.desktop.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.workflowy.desktop.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.workflowy.desktop.savedState
echo "Removing $HOME/Library/Saved Application State/com.workflowy.desktop.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.workflowy.desktop.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.workflowy.desktop.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.workflowy.desktop.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.workflowy.desktop.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
