#!/bin/bash
# Uninstall script for Deepnest
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Deepnest..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Deepnest if running..."
pkill -f "Deepnest" 2>/dev/null || true

# Remove /Applications/Deepnest-1.0.5-mac/Deepnest-mac-1.0.5.app
echo "Removing /Applications/Deepnest-1.0.5-mac/Deepnest-mac-1.0.5.app..."
if [ -d "/Applications/Deepnest-1.0.5-mac/Deepnest-mac-1.0.5.app" ]; then
    rm -rf "/Applications/Deepnest-1.0.5-mac/Deepnest-mac-1.0.5.app" 2>/dev/null || true
elif [ -f "/Applications/Deepnest-1.0.5-mac/Deepnest-mac-1.0.5.app" ]; then
    rm -f "/Applications/Deepnest-1.0.5-mac/Deepnest-mac-1.0.5.app" 2>/dev/null || true
fi

# Remove /Applications/{'target': 'Deepnest.app'}
echo "Removing /Applications/{'target': 'Deepnest.app'}..."
if [ -d "/Applications/{'target': 'Deepnest.app'}" ]; then
    rm -rf "/Applications/{'target': 'Deepnest.app'}" 2>/dev/null || true
elif [ -f "/Applications/{'target': 'Deepnest.app'}" ]; then
    rm -f "/Applications/{'target': 'Deepnest.app'}" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Deepnest.io
echo "Removing $HOME/Library/Application Support/Deepnest.io..."
if [ -d "$HOME/Library/Application Support/Deepnest.io" ]; then
    rm -rf "$HOME/Library/Application Support/Deepnest.io" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Deepnest.io" ]; then
    rm -f "$HOME/Library/Application Support/Deepnest.io" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.deepnest.io
echo "Removing $HOME/Library/Caches/com.deepnest.io..."
if [ -d "$HOME/Library/Caches/com.deepnest.io" ]; then
    rm -rf "$HOME/Library/Caches/com.deepnest.io" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.deepnest.io" ]; then
    rm -f "$HOME/Library/Caches/com.deepnest.io" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.deepnest.io.helper.plist
echo "Removing $HOME/Library/Preferences/com.deepnest.io.helper.plist..."
if [ -d "$HOME/Library/Preferences/com.deepnest.io.helper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.deepnest.io.helper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.deepnest.io.helper.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.deepnest.io.helper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.deepnest.io.plist
echo "Removing $HOME/Library/Preferences/com.deepnest.io.plist..."
if [ -d "$HOME/Library/Preferences/com.deepnest.io.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.deepnest.io.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.deepnest.io.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.deepnest.io.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.deepnest.io.savedState
echo "Removing $HOME/Library/Saved Application State/com.deepnest.io.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.deepnest.io.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.deepnest.io.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.deepnest.io.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.deepnest.io.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.deepnest.io
echo "Removing $HOME/Library/WebKit/com.deepnest.io..."
if [ -d "$HOME/Library/WebKit/com.deepnest.io" ]; then
    rm -rf "$HOME/Library/WebKit/com.deepnest.io" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.deepnest.io" ]; then
    rm -f "$HOME/Library/WebKit/com.deepnest.io" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
