#!/bin/bash
# Uninstall script for Monodraw
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Monodraw..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Monodraw if running..."
pkill -f "Monodraw" 2>/dev/null || true

# Remove /Applications/Monodraw.app
echo "Removing /Applications/Monodraw.app..."
if [ -d "/Applications/Monodraw.app" ]; then
    rm -rf "/Applications/Monodraw.app" 2>/dev/null || true
elif [ -f "/Applications/Monodraw.app" ]; then
    rm -f "/Applications/Monodraw.app" 2>/dev/null || true
fi

# Remove binary /Applications/Monodraw.app/Monodraw.app/Contents/Resources/monodraw
echo "Removing binary /Applications/Monodraw.app/Monodraw.app/Contents/Resources/monodraw..."
if [ -f "/Applications/Monodraw.app/Monodraw.app/Contents/Resources/monodraw" ]; then
    rm -f "/Applications/Monodraw.app/Monodraw.app/Contents/Resources/monodraw" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.helftone.monodraw
echo "Removing $HOME/Library/Application Support/com.helftone.monodraw..."
if [ -d "$HOME/Library/Application Support/com.helftone.monodraw" ]; then
    rm -rf "$HOME/Library/Application Support/com.helftone.monodraw" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.helftone.monodraw" ]; then
    rm -f "$HOME/Library/Application Support/com.helftone.monodraw" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/com.helftone.monodraw.help*
echo "Removing $HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/com.helftone.monodraw.help*..."
if [ -d "$HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/com.helftone.monodraw.help*" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/com.helftone.monodraw.help*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/com.helftone.monodraw.help*" ]; then
    rm -f "$HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/com.helftone.monodraw.help*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.helftone.monodraw
echo "Removing $HOME/Library/Caches/com.helftone.monodraw..."
if [ -d "$HOME/Library/Caches/com.helftone.monodraw" ]; then
    rm -rf "$HOME/Library/Caches/com.helftone.monodraw" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.helftone.monodraw" ]; then
    rm -f "$HOME/Library/Caches/com.helftone.monodraw" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.helftone.monodraw.plist
echo "Removing $HOME/Library/Preferences/com.helftone.monodraw.plist..."
if [ -d "$HOME/Library/Preferences/com.helftone.monodraw.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.helftone.monodraw.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.helftone.monodraw.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.helftone.monodraw.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
