#!/bin/bash
# Uninstall script for Session Manager Plugin for the AWS CLI
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Session Manager Plugin for the AWS CLI..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Session Manager Plugin for the AWS CLI if running..."
pkill -f "Session Manager Plugin for the AWS CLI" 2>/dev/null || true

# Remove /usr/local/bin//usr/local/sessionmanagerplugin/bin/session-manager-plugin
echo "Removing /usr/local/bin//usr/local/sessionmanagerplugin/bin/session-manager-plugin..."
if [ -d "/usr/local/bin//usr/local/sessionmanagerplugin/bin/session-manager-plugin" ]; then
    rm -rf "/usr/local/bin//usr/local/sessionmanagerplugin/bin/session-manager-plugin" 2>/dev/null || true
elif [ -f "/usr/local/bin//usr/local/sessionmanagerplugin/bin/session-manager-plugin" ]; then
    rm -f "/usr/local/bin//usr/local/sessionmanagerplugin/bin/session-manager-plugin" 2>/dev/null || true
fi

# Remove /Library/LaunchDaemons/SessionManagerPlugin.plist
echo "Removing /Library/LaunchDaemons/SessionManagerPlugin.plist..."
if [ -d "/Library/LaunchDaemons/SessionManagerPlugin.plist" ]; then
    rm -rf "/Library/LaunchDaemons/SessionManagerPlugin.plist" 2>/dev/null || true
elif [ -f "/Library/LaunchDaemons/SessionManagerPlugin.plist" ]; then
    rm -f "/Library/LaunchDaemons/SessionManagerPlugin.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
