#!/bin/bash
# Uninstall script for Gitify
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Gitify..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Gitify if running..."
pkill -f "Gitify" 2>/dev/null || true

# Kill application with bundle ID com.electron.gitify if running
echo "Stopping application with bundle ID com.electron.gitify if running..."
killall -9 "com.electron.gitify" 2>/dev/null || true

# Kill application with bundle ID com.electron.gitify.helper if running
echo "Stopping application with bundle ID com.electron.gitify.helper if running..."
killall -9 "com.electron.gitify.helper" 2>/dev/null || true

# Remove /Applications/Gitify.app
echo "Removing /Applications/Gitify.app..."
if [ -d "/Applications/Gitify.app" ]; then
    rm -rf "/Applications/Gitify.app" 2>/dev/null || true
elif [ -f "/Applications/Gitify.app" ]; then
    rm -f "/Applications/Gitify.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.electron.gitify.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.electron.gitify.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.electron.gitify.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.electron.gitify.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.electron.gitify.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.electron.gitify.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/gitify
echo "Removing $HOME/Library/Application Support/gitify..."
if [ -d "$HOME/Library/Application Support/gitify" ]; then
    rm -rf "$HOME/Library/Application Support/gitify" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/gitify" ]; then
    rm -f "$HOME/Library/Application Support/gitify" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.electron.gitify*
echo "Removing $HOME/Library/Caches/com.electron.gitify*..."
if [ -d "$HOME/Library/Caches/com.electron.gitify*" ]; then
    rm -rf "$HOME/Library/Caches/com.electron.gitify*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.electron.gitify*" ]; then
    rm -f "$HOME/Library/Caches/com.electron.gitify*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/gitify-updater
echo "Removing $HOME/Library/Caches/gitify-updater..."
if [ -d "$HOME/Library/Caches/gitify-updater" ]; then
    rm -rf "$HOME/Library/Caches/gitify-updater" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/gitify-updater" ]; then
    rm -f "$HOME/Library/Caches/gitify-updater" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.electron.gitify
echo "Removing $HOME/Library/HTTPStorages/com.electron.gitify..."
if [ -d "$HOME/Library/HTTPStorages/com.electron.gitify" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.electron.gitify" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.electron.gitify" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.electron.gitify" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.electron.gitify*.plist
echo "Removing $HOME/Library/Preferences/com.electron.gitify*.plist..."
if [ -d "$HOME/Library/Preferences/com.electron.gitify*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.electron.gitify*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.electron.gitify*.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.electron.gitify*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.electron.gitify.savedState
echo "Removing $HOME/Library/Saved Application State/com.electron.gitify.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.electron.gitify.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.electron.gitify.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.electron.gitify.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.electron.gitify.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
