#!/bin/bash
# Uninstall script for Bezel
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Bezel..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Bezel if running..."
pkill -f "Bezel" 2>/dev/null || true

# Remove /Applications/Bezel.app
echo "Removing /Applications/Bezel.app..."
if [ -d "/Applications/Bezel.app" ]; then
    rm -rf "/Applications/Bezel.app" 2>/dev/null || true
elif [ -f "/Applications/Bezel.app" ]; then
    rm -f "/Applications/Bezel.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.nonstrict.Bezel-direct
echo "Removing $HOME/Library/Caches/com.nonstrict.Bezel-direct..."
if [ -d "$HOME/Library/Caches/com.nonstrict.Bezel-direct" ]; then
    rm -rf "$HOME/Library/Caches/com.nonstrict.Bezel-direct" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.nonstrict.Bezel-direct" ]; then
    rm -f "$HOME/Library/Caches/com.nonstrict.Bezel-direct" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.nonstrict.Bezel-direct
echo "Removing $HOME/Library/HTTPStorages/com.nonstrict.Bezel-direct..."
if [ -d "$HOME/Library/HTTPStorages/com.nonstrict.Bezel-direct" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.nonstrict.Bezel-direct" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.nonstrict.Bezel-direct" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.nonstrict.Bezel-direct" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.nonstrict.Bezel-direct.plist
echo "Removing $HOME/Library/Preferences/com.nonstrict.Bezel-direct.plist..."
if [ -d "$HOME/Library/Preferences/com.nonstrict.Bezel-direct.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.nonstrict.Bezel-direct.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.nonstrict.Bezel-direct.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.nonstrict.Bezel-direct.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
