#!/bin/bash
# Uninstall script for Panic Nova
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Panic Nova..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Panic Nova if running..."
pkill -f "Panic Nova" 2>/dev/null || true

# Remove /Applications/Nova.app
echo "Removing /Applications/Nova.app..."
if [ -d "/Applications/Nova.app" ]; then
    rm -rf "/Applications/Nova.app" 2>/dev/null || true
elif [ -f "/Applications/Nova.app" ]; then
    rm -f "/Applications/Nova.app" 2>/dev/null || true
fi

# Remove binary /Applications/Panic Nova.app/Nova.app/Contents/SharedSupport/nova
echo "Removing binary /Applications/Panic Nova.app/Nova.app/Contents/SharedSupport/nova..."
if [ -f "/Applications/Panic Nova.app/Nova.app/Contents/SharedSupport/nova" ]; then
    rm -f "/Applications/Panic Nova.app/Nova.app/Contents/SharedSupport/nova" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.panic.Nova.NovaQuickLookPreview
echo "Removing $HOME/Library/Application Scripts/com.panic.Nova.NovaQuickLookPreview..."
if [ -d "$HOME/Library/Application Scripts/com.panic.Nova.NovaQuickLookPreview" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.panic.Nova.NovaQuickLookPreview" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.panic.Nova.NovaQuickLookPreview" ]; then
    rm -f "$HOME/Library/Application Scripts/com.panic.Nova.NovaQuickLookPreview" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.panic.Nova.NovaQuickLookThumbnail
echo "Removing $HOME/Library/Application Scripts/com.panic.Nova.NovaQuickLookThumbnail..."
if [ -d "$HOME/Library/Application Scripts/com.panic.Nova.NovaQuickLookThumbnail" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.panic.Nova.NovaQuickLookThumbnail" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.panic.Nova.NovaQuickLookThumbnail" ]; then
    rm -f "$HOME/Library/Application Scripts/com.panic.Nova.NovaQuickLookThumbnail" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.panic.nova.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.panic.nova.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.panic.nova.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.panic.nova.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.panic.nova.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.panic.nova.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.panic.Nova
echo "Removing $HOME/Library/Caches/com.panic.Nova..."
if [ -d "$HOME/Library/Caches/com.panic.Nova" ]; then
    rm -rf "$HOME/Library/Caches/com.panic.Nova" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.panic.Nova" ]; then
    rm -f "$HOME/Library/Caches/com.panic.Nova" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.panic.Nova.NovaQuickLookPreview
echo "Removing $HOME/Library/Containers/com.panic.Nova.NovaQuickLookPreview..."
if [ -d "$HOME/Library/Containers/com.panic.Nova.NovaQuickLookPreview" ]; then
    rm -rf "$HOME/Library/Containers/com.panic.Nova.NovaQuickLookPreview" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.panic.Nova.NovaQuickLookPreview" ]; then
    rm -f "$HOME/Library/Containers/com.panic.Nova.NovaQuickLookPreview" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.panic.Nova.NovaQuickLookThumbnail
echo "Removing $HOME/Library/Containers/com.panic.Nova.NovaQuickLookThumbnail..."
if [ -d "$HOME/Library/Containers/com.panic.Nova.NovaQuickLookThumbnail" ]; then
    rm -rf "$HOME/Library/Containers/com.panic.Nova.NovaQuickLookThumbnail" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.panic.Nova.NovaQuickLookThumbnail" ]; then
    rm -f "$HOME/Library/Containers/com.panic.Nova.NovaQuickLookThumbnail" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.panic.Nova.plist
echo "Removing $HOME/Library/Preferences/com.panic.Nova.plist..."
if [ -d "$HOME/Library/Preferences/com.panic.Nova.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.panic.Nova.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.panic.Nova.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.panic.Nova.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.panic.Nova
echo "Removing $HOME/Library/WebKit/com.panic.Nova..."
if [ -d "$HOME/Library/WebKit/com.panic.Nova" ]; then
    rm -rf "$HOME/Library/WebKit/com.panic.Nova" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.panic.Nova" ]; then
    rm -f "$HOME/Library/WebKit/com.panic.Nova" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
