#!/bin/bash
# Uninstall script for Descript
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Descript..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Descript if running..."
pkill -f "Descript" 2>/dev/null || true

# Remove /Applications/Descript.app
echo "Removing /Applications/Descript.app..."
if [ -d "/Applications/Descript.app" ]; then
    rm -rf "/Applications/Descript.app" 2>/dev/null || true
elif [ -f "/Applications/Descript.app" ]; then
    rm -f "/Applications/Descript.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Descript
echo "Removing $HOME/Library/Application Support/Descript..."
if [ -d "$HOME/Library/Application Support/Descript" ]; then
    rm -rf "$HOME/Library/Application Support/Descript" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Descript" ]; then
    rm -f "$HOME/Library/Application Support/Descript" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.descript.beachcube
echo "Removing $HOME/Library/Caches/com.descript.beachcube..."
if [ -d "$HOME/Library/Caches/com.descript.beachcube" ]; then
    rm -rf "$HOME/Library/Caches/com.descript.beachcube" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.descript.beachcube" ]; then
    rm -f "$HOME/Library/Caches/com.descript.beachcube" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.descript.beachcube.ShipIt
echo "Removing $HOME/Library/Caches/com.descript.beachcube.ShipIt..."
if [ -d "$HOME/Library/Caches/com.descript.beachcube.ShipIt" ]; then
    rm -rf "$HOME/Library/Caches/com.descript.beachcube.ShipIt" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.descript.beachcube.ShipIt" ]; then
    rm -f "$HOME/Library/Caches/com.descript.beachcube.ShipIt" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.descript.Descript-Installer
echo "Removing $HOME/Library/Caches/com.descript.Descript-Installer..."
if [ -d "$HOME/Library/Caches/com.descript.Descript-Installer" ]; then
    rm -rf "$HOME/Library/Caches/com.descript.Descript-Installer" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.descript.Descript-Installer" ]; then
    rm -f "$HOME/Library/Caches/com.descript.Descript-Installer" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.descript.beachcube.plist
echo "Removing $HOME/Library/Preferences/com.descript.beachcube.plist..."
if [ -d "$HOME/Library/Preferences/com.descript.beachcube.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.descript.beachcube.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.descript.beachcube.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.descript.beachcube.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.descript.Descript-Installer.plist
echo "Removing $HOME/Library/Preferences/com.descript.Descript-Installer.plist..."
if [ -d "$HOME/Library/Preferences/com.descript.Descript-Installer.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.descript.Descript-Installer.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.descript.Descript-Installer.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.descript.Descript-Installer.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.descript.ScreenRecorder.plist
echo "Removing $HOME/Library/Preferences/com.descript.ScreenRecorder.plist..."
if [ -d "$HOME/Library/Preferences/com.descript.ScreenRecorder.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.descript.ScreenRecorder.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.descript.ScreenRecorder.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.descript.ScreenRecorder.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.descript.beachcube.savedState
echo "Removing $HOME/Library/Saved Application State/com.descript.beachcube.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.descript.beachcube.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.descript.beachcube.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.descript.beachcube.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.descript.beachcube.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.descript.Descript-Installer.savedState
echo "Removing $HOME/Library/Saved Application State/com.descript.Descript-Installer.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.descript.Descript-Installer.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.descript.Descript-Installer.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.descript.Descript-Installer.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.descript.Descript-Installer.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
