#!/bin/bash
# Uninstall script for Kodi
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Kodi..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Kodi if running..."
pkill -f "Kodi" 2>/dev/null || true

# Remove /Applications/Kodi.app
echo "Removing /Applications/Kodi.app..."
if [ -d "/Applications/Kodi.app" ]; then
    rm -rf "/Applications/Kodi.app" 2>/dev/null || true
elif [ -f "/Applications/Kodi.app" ]; then
    rm -f "/Applications/Kodi.app" 2>/dev/null || true
fi

# Remove $HOME/.kodi
echo "Removing $HOME/.kodi..."
if [ -d "$HOME/.kodi" ]; then
    rm -rf "$HOME/.kodi" 2>/dev/null || true
elif [ -f "$HOME/.kodi" ]; then
    rm -f "$HOME/.kodi" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Kodi
echo "Removing $HOME/Library/Application Support/Kodi..."
if [ -d "$HOME/Library/Application Support/Kodi" ]; then
    rm -rf "$HOME/Library/Application Support/Kodi" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Kodi" ]; then
    rm -f "$HOME/Library/Application Support/Kodi" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/kodi.log
echo "Removing $HOME/Library/Logs/kodi.log..."
if [ -d "$HOME/Library/Logs/kodi.log" ]; then
    rm -rf "$HOME/Library/Logs/kodi.log" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/kodi.log" ]; then
    rm -f "$HOME/Library/Logs/kodi.log" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/kodi.old.log
echo "Removing $HOME/Library/Logs/kodi.old.log..."
if [ -d "$HOME/Library/Logs/kodi.old.log" ]; then
    rm -rf "$HOME/Library/Logs/kodi.old.log" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/kodi.old.log" ]; then
    rm -f "$HOME/Library/Logs/kodi.old.log" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/org.xbmc.kodi.plist
echo "Removing $HOME/Library/Preferences/org.xbmc.kodi.plist..."
if [ -d "$HOME/Library/Preferences/org.xbmc.kodi.plist" ]; then
    rm -rf "$HOME/Library/Preferences/org.xbmc.kodi.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/org.xbmc.kodi.plist" ]; then
    rm -f "$HOME/Library/Preferences/org.xbmc.kodi.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/org.xbmc.kodi.savedState
echo "Removing $HOME/Library/Saved Application State/org.xbmc.kodi.savedState..."
if [ -d "$HOME/Library/Saved Application State/org.xbmc.kodi.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/org.xbmc.kodi.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/org.xbmc.kodi.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/org.xbmc.kodi.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
