#!/bin/bash
# Uninstall script for IntelliJ IDEA Ultimate
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling IntelliJ IDEA Ultimate..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping IntelliJ IDEA Ultimate if running..."
pkill -f "IntelliJ IDEA Ultimate" 2>/dev/null || true

# Kill application with bundle ID com.jetbrains.intellij if running
echo "Stopping application with bundle ID com.jetbrains.intellij if running..."
killall -9 "com.jetbrains.intellij" 2>/dev/null || true

# Remove /Applications/IntelliJ IDEA.app
echo "Removing /Applications/IntelliJ IDEA.app..."
if [ -d "/Applications/IntelliJ IDEA.app" ]; then
    rm -rf "/Applications/IntelliJ IDEA.app" 2>/dev/null || true
elif [ -f "/Applications/IntelliJ IDEA.app" ]; then
    rm -f "/Applications/IntelliJ IDEA.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/JetBrains/IntelliJIdea2026.2
echo "Removing $HOME/Library/Application Support/JetBrains/IntelliJIdea2026.2..."
if [ -d "$HOME/Library/Application Support/JetBrains/IntelliJIdea2026.2" ]; then
    rm -rf "$HOME/Library/Application Support/JetBrains/IntelliJIdea2026.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/JetBrains/IntelliJIdea2026.2" ]; then
    rm -f "$HOME/Library/Application Support/JetBrains/IntelliJIdea2026.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/JetBrains/IntelliJIdea2026.2
echo "Removing $HOME/Library/Caches/JetBrains/IntelliJIdea2026.2..."
if [ -d "$HOME/Library/Caches/JetBrains/IntelliJIdea2026.2" ]; then
    rm -rf "$HOME/Library/Caches/JetBrains/IntelliJIdea2026.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/JetBrains/IntelliJIdea2026.2" ]; then
    rm -f "$HOME/Library/Caches/JetBrains/IntelliJIdea2026.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/JetBrains/IntelliJIdea2026.2
echo "Removing $HOME/Library/Logs/JetBrains/IntelliJIdea2026.2..."
if [ -d "$HOME/Library/Logs/JetBrains/IntelliJIdea2026.2" ]; then
    rm -rf "$HOME/Library/Logs/JetBrains/IntelliJIdea2026.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/JetBrains/IntelliJIdea2026.2" ]; then
    rm -f "$HOME/Library/Logs/JetBrains/IntelliJIdea2026.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.jetbrains.intellij.plist
echo "Removing $HOME/Library/Preferences/com.jetbrains.intellij.plist..."
if [ -d "$HOME/Library/Preferences/com.jetbrains.intellij.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.jetbrains.intellij.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.jetbrains.intellij.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.jetbrains.intellij.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/IntelliJIdea2026.2
echo "Removing $HOME/Library/Preferences/IntelliJIdea2026.2..."
if [ -d "$HOME/Library/Preferences/IntelliJIdea2026.2" ]; then
    rm -rf "$HOME/Library/Preferences/IntelliJIdea2026.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/IntelliJIdea2026.2" ]; then
    rm -f "$HOME/Library/Preferences/IntelliJIdea2026.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/jetbrains.idea.*.plist
echo "Removing $HOME/Library/Preferences/jetbrains.idea.*.plist..."
if [ -d "$HOME/Library/Preferences/jetbrains.idea.*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/jetbrains.idea.*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/jetbrains.idea.*.plist" ]; then
    rm -f "$HOME/Library/Preferences/jetbrains.idea.*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.jetbrains.intellij.savedState
echo "Removing $HOME/Library/Saved Application State/com.jetbrains.intellij.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.jetbrains.intellij.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.jetbrains.intellij.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.jetbrains.intellij.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.jetbrains.intellij.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
