#!/bin/bash
# Uninstall script for Shifty
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Shifty..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Shifty if running..."
pkill -f "Shifty" 2>/dev/null || true

# Unload service io.natethompson.ShiftyHelper
echo "Unloading service io.natethompson.ShiftyHelper..."
launchctl unload -w /Library/LaunchAgents/io.natethompson.ShiftyHelper.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/io.natethompson.ShiftyHelper.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/io.natethompson.ShiftyHelper.plist 2>/dev/null || true

# Kill application with bundle ID io.natethompson.Shifty if running
echo "Stopping application with bundle ID io.natethompson.Shifty if running..."
killall -9 "io.natethompson.Shifty" 2>/dev/null || true

# Remove /Applications/Shifty.app
echo "Removing /Applications/Shifty.app..."
if [ -d "/Applications/Shifty.app" ]; then
    rm -rf "/Applications/Shifty.app" 2>/dev/null || true
elif [ -f "/Applications/Shifty.app" ]; then
    rm -f "/Applications/Shifty.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/io.natethompson.ShiftyHelper
echo "Removing $HOME/Library/Application Scripts/io.natethompson.ShiftyHelper..."
if [ -d "$HOME/Library/Application Scripts/io.natethompson.ShiftyHelper" ]; then
    rm -rf "$HOME/Library/Application Scripts/io.natethompson.ShiftyHelper" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/io.natethompson.ShiftyHelper" ]; then
    rm -f "$HOME/Library/Application Scripts/io.natethompson.ShiftyHelper" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/io.natethompson.Shifty
echo "Removing $HOME/Library/Application Support/io.natethompson.Shifty..."
if [ -d "$HOME/Library/Application Support/io.natethompson.Shifty" ]; then
    rm -rf "$HOME/Library/Application Support/io.natethompson.Shifty" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/io.natethompson.Shifty" ]; then
    rm -f "$HOME/Library/Application Support/io.natethompson.Shifty" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.crashlytics.data/io.natethompson.Shifty
echo "Removing $HOME/Library/Caches/com.crashlytics.data/io.natethompson.Shifty..."
if [ -d "$HOME/Library/Caches/com.crashlytics.data/io.natethompson.Shifty" ]; then
    rm -rf "$HOME/Library/Caches/com.crashlytics.data/io.natethompson.Shifty" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.crashlytics.data/io.natethompson.Shifty" ]; then
    rm -f "$HOME/Library/Caches/com.crashlytics.data/io.natethompson.Shifty" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/io.fabric.sdk.mac.data/io.natethompson.Shifty
echo "Removing $HOME/Library/Caches/io.fabric.sdk.mac.data/io.natethompson.Shifty..."
if [ -d "$HOME/Library/Caches/io.fabric.sdk.mac.data/io.natethompson.Shifty" ]; then
    rm -rf "$HOME/Library/Caches/io.fabric.sdk.mac.data/io.natethompson.Shifty" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/io.fabric.sdk.mac.data/io.natethompson.Shifty" ]; then
    rm -f "$HOME/Library/Caches/io.fabric.sdk.mac.data/io.natethompson.Shifty" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/io.natethompson.Shifty
echo "Removing $HOME/Library/Caches/io.natethompson.Shifty..."
if [ -d "$HOME/Library/Caches/io.natethompson.Shifty" ]; then
    rm -rf "$HOME/Library/Caches/io.natethompson.Shifty" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/io.natethompson.Shifty" ]; then
    rm -f "$HOME/Library/Caches/io.natethompson.Shifty" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/io.natethompson.ShiftyHelper
echo "Removing $HOME/Library/Containers/io.natethompson.ShiftyHelper..."
if [ -d "$HOME/Library/Containers/io.natethompson.ShiftyHelper" ]; then
    rm -rf "$HOME/Library/Containers/io.natethompson.ShiftyHelper" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/io.natethompson.ShiftyHelper" ]; then
    rm -f "$HOME/Library/Containers/io.natethompson.ShiftyHelper" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/io.natethompson.Shifty.plist
echo "Removing $HOME/Library/Preferences/io.natethompson.Shifty.plist..."
if [ -d "$HOME/Library/Preferences/io.natethompson.Shifty.plist" ]; then
    rm -rf "$HOME/Library/Preferences/io.natethompson.Shifty.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/io.natethompson.Shifty.plist" ]; then
    rm -f "$HOME/Library/Preferences/io.natethompson.Shifty.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
