#!/bin/bash
# Uninstall script for Stoplight Studio
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Stoplight Studio..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Stoplight Studio if running..."
pkill -f "Stoplight Studio" 2>/dev/null || true

# Remove /Applications/Stoplight Studio.app
echo "Removing /Applications/Stoplight Studio.app..."
if [ -d "/Applications/Stoplight Studio.app" ]; then
    rm -rf "/Applications/Stoplight Studio.app" 2>/dev/null || true
elif [ -f "/Applications/Stoplight Studio.app" ]; then
    rm -f "/Applications/Stoplight Studio.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Stoplight Studio
echo "Removing $HOME/Library/Application Support/Stoplight Studio..."
if [ -d "$HOME/Library/Application Support/Stoplight Studio" ]; then
    rm -rf "$HOME/Library/Application Support/Stoplight Studio" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Stoplight Studio" ]; then
    rm -f "$HOME/Library/Application Support/Stoplight Studio" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Stoplight Studio
echo "Removing $HOME/Library/Logs/Stoplight Studio..."
if [ -d "$HOME/Library/Logs/Stoplight Studio" ]; then
    rm -rf "$HOME/Library/Logs/Stoplight Studio" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Stoplight Studio" ]; then
    rm -f "$HOME/Library/Logs/Stoplight Studio" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.stoplight.studio.plist
echo "Removing $HOME/Library/Preferences/com.stoplight.studio.plist..."
if [ -d "$HOME/Library/Preferences/com.stoplight.studio.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.stoplight.studio.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.stoplight.studio.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.stoplight.studio.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.stoplight.studio.savedState
echo "Removing $HOME/Library/Saved Application State/com.stoplight.studio.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.stoplight.studio.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.stoplight.studio.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.stoplight.studio.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.stoplight.studio.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
