#!/bin/bash
# Uninstall script for WineHQ-stable
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling WineHQ-stable..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping WineHQ-stable if running..."
pkill -f "WineHQ-stable" 2>/dev/null || true

# Remove /Applications/Wine Stable.app
echo "Removing /Applications/Wine Stable.app..."
if [ -d "/Applications/Wine Stable.app" ]; then
    rm -rf "/Applications/Wine Stable.app" 2>/dev/null || true
elif [ -f "/Applications/Wine Stable.app" ]; then
    rm -f "/Applications/Wine Stable.app" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/start/bin/appdb
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/start/bin/appdb..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/start/bin/appdb" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/start/bin/appdb" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/start/bin/winehelp
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/start/bin/winehelp..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/start/bin/winehelp" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/start/bin/winehelp" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/msidb
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/msidb..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/msidb" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/msidb" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/msiexec
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/msiexec..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/msiexec" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/msiexec" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/notepad
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/notepad..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/notepad" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/notepad" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/regedit
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/regedit..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/regedit" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/regedit" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/regsvr32
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/regsvr32..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/regsvr32" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/regsvr32" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wine
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wine..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wine" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wine" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winecfg
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winecfg..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winecfg" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winecfg" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wineconsole
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wineconsole..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wineconsole" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wineconsole" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winedbg
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winedbg..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winedbg" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winedbg" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winefile
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winefile..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winefile" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winefile" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winemine
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winemine..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winemine" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winemine" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winepath
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winepath..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winepath" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/winepath" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wineserver
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wineserver..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wineserver" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wineserver" 2>/dev/null || true
fi

# Remove binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wineboot
echo "Removing binary /Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wineboot..."
if [ -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wineboot" ]; then
    rm -f "/Applications/WineHQ-stable.app/Wine Stable.app/Contents/Resources/wine/bin/wineboot" 2>/dev/null || true
fi

# Remove $HOME/.local/share/applications/wine*
echo "Removing $HOME/.local/share/applications/wine*..."
if [ -d "$HOME/.local/share/applications/wine*" ]; then
    rm -rf "$HOME/.local/share/applications/wine*" 2>/dev/null || true
elif [ -f "$HOME/.local/share/applications/wine*" ]; then
    rm -f "$HOME/.local/share/applications/wine*" 2>/dev/null || true
fi

# Remove $HOME/.local/share/icons/hicolor/**/application-x-wine*
echo "Removing $HOME/.local/share/icons/hicolor/**/application-x-wine*..."
if [ -d "$HOME/.local/share/icons/hicolor/**/application-x-wine*" ]; then
    rm -rf "$HOME/.local/share/icons/hicolor/**/application-x-wine*" 2>/dev/null || true
elif [ -f "$HOME/.local/share/icons/hicolor/**/application-x-wine*" ]; then
    rm -f "$HOME/.local/share/icons/hicolor/**/application-x-wine*" 2>/dev/null || true
fi

# Remove $HOME/.local/share/mime/application/x-wine*
echo "Removing $HOME/.local/share/mime/application/x-wine*..."
if [ -d "$HOME/.local/share/mime/application/x-wine*" ]; then
    rm -rf "$HOME/.local/share/mime/application/x-wine*" 2>/dev/null || true
elif [ -f "$HOME/.local/share/mime/application/x-wine*" ]; then
    rm -f "$HOME/.local/share/mime/application/x-wine*" 2>/dev/null || true
fi

# Remove $HOME/.local/share/mime/packages/x-wine*
echo "Removing $HOME/.local/share/mime/packages/x-wine*..."
if [ -d "$HOME/.local/share/mime/packages/x-wine*" ]; then
    rm -rf "$HOME/.local/share/mime/packages/x-wine*" 2>/dev/null || true
elif [ -f "$HOME/.local/share/mime/packages/x-wine*" ]; then
    rm -f "$HOME/.local/share/mime/packages/x-wine*" 2>/dev/null || true
fi

# Remove $HOME/.wine
echo "Removing $HOME/.wine..."
if [ -d "$HOME/.wine" ]; then
    rm -rf "$HOME/.wine" 2>/dev/null || true
elif [ -f "$HOME/.wine" ]; then
    rm -f "$HOME/.wine" 2>/dev/null || true
fi

# Remove $HOME/.wine32
echo "Removing $HOME/.wine32..."
if [ -d "$HOME/.wine32" ]; then
    rm -rf "$HOME/.wine32" 2>/dev/null || true
elif [ -f "$HOME/.wine32" ]; then
    rm -f "$HOME/.wine32" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/org.winehq.wine-stable.wine.savedState
echo "Removing $HOME/Library/Saved Application State/org.winehq.wine-stable.wine.savedState..."
if [ -d "$HOME/Library/Saved Application State/org.winehq.wine-stable.wine.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/org.winehq.wine-stable.wine.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/org.winehq.wine-stable.wine.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/org.winehq.wine-stable.wine.savedState" 2>/dev/null || true
fi

# Remove $HOME/.local/share/applications
echo "Removing $HOME/.local/share/applications..."
if [ -d "$HOME/.local/share/applications" ]; then
    rm -rf "$HOME/.local/share/applications" 2>/dev/null || true
elif [ -f "$HOME/.local/share/applications" ]; then
    rm -f "$HOME/.local/share/applications" 2>/dev/null || true
fi

# Remove $HOME/.local/share/icons
echo "Removing $HOME/.local/share/icons..."
if [ -d "$HOME/.local/share/icons" ]; then
    rm -rf "$HOME/.local/share/icons" 2>/dev/null || true
elif [ -f "$HOME/.local/share/icons" ]; then
    rm -f "$HOME/.local/share/icons" 2>/dev/null || true
fi

# Remove $HOME/.local/share/mime
echo "Removing $HOME/.local/share/mime..."
if [ -d "$HOME/.local/share/mime" ]; then
    rm -rf "$HOME/.local/share/mime" 2>/dev/null || true
elif [ -f "$HOME/.local/share/mime" ]; then
    rm -f "$HOME/.local/share/mime" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
