#!/bin/bash
# Uninstall script for WhatSize
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling WhatSize..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping WhatSize if running..."
pkill -f "WhatSize" 2>/dev/null || true

# Unload service com.id-design.v8.whatsizehelper
echo "Unloading service com.id-design.v8.whatsizehelper..."
launchctl unload -w /Library/LaunchAgents/com.id-design.v8.whatsizehelper.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.id-design.v8.whatsizehelper.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.id-design.v8.whatsizehelper.plist 2>/dev/null || true

# Remove $HOME/Library/Application Support/WhatSize
echo "Removing $HOME/Library/Application Support/WhatSize..."
if [ -d "$HOME/Library/Application Support/WhatSize" ]; then
    rm -rf "$HOME/Library/Application Support/WhatSize" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/WhatSize" ]; then
    rm -f "$HOME/Library/Application Support/WhatSize" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.id-design.v8.whatsize
echo "Removing $HOME/Library/Caches/com.id-design.v8.whatsize..."
if [ -d "$HOME/Library/Caches/com.id-design.v8.whatsize" ]; then
    rm -rf "$HOME/Library/Caches/com.id-design.v8.whatsize" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.id-design.v8.whatsize" ]; then
    rm -f "$HOME/Library/Caches/com.id-design.v8.whatsize" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.id-design.v8.whatsize
echo "Removing $HOME/Library/HTTPStorages/com.id-design.v8.whatsize..."
if [ -d "$HOME/Library/HTTPStorages/com.id-design.v8.whatsize" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.id-design.v8.whatsize" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.id-design.v8.whatsize" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.id-design.v8.whatsize" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/WhatSize
echo "Removing $HOME/Library/Logs/WhatSize..."
if [ -d "$HOME/Library/Logs/WhatSize" ]; then
    rm -rf "$HOME/Library/Logs/WhatSize" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/WhatSize" ]; then
    rm -f "$HOME/Library/Logs/WhatSize" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.id-design.v8.whatsize.plist
echo "Removing $HOME/Library/Preferences/com.id-design.v8.whatsize.plist..."
if [ -d "$HOME/Library/Preferences/com.id-design.v8.whatsize.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.id-design.v8.whatsize.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.id-design.v8.whatsize.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.id-design.v8.whatsize.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.id-design.v8.whatsize.savedState
echo "Removing $HOME/Library/Saved Application State/com.id-design.v8.whatsize.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.id-design.v8.whatsize.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.id-design.v8.whatsize.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.id-design.v8.whatsize.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.id-design.v8.whatsize.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.id-design.v8.whatsize
echo "Removing $HOME/Library/WebKit/com.id-design.v8.whatsize..."
if [ -d "$HOME/Library/WebKit/com.id-design.v8.whatsize" ]; then
    rm -rf "$HOME/Library/WebKit/com.id-design.v8.whatsize" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.id-design.v8.whatsize" ]; then
    rm -f "$HOME/Library/WebKit/com.id-design.v8.whatsize" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
