#!/bin/bash
# Uninstall script for Mem
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Mem..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Mem if running..."
pkill -f "Mem" 2>/dev/null || true

# Remove /Applications/Mem.app
echo "Removing /Applications/Mem.app..."
if [ -d "/Applications/Mem.app" ]; then
    rm -rf "/Applications/Mem.app" 2>/dev/null || true
elif [ -f "/Applications/Mem.app" ]; then
    rm -f "/Applications/Mem.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/mem
echo "Removing $HOME/Library/Application Support/mem..."
if [ -d "$HOME/Library/Application Support/mem" ]; then
    rm -rf "$HOME/Library/Application Support/mem" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/mem" ]; then
    rm -f "$HOME/Library/Application Support/mem" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/org.memlabs.Mem.plist
echo "Removing $HOME/Library/Preferences/org.memlabs.Mem.plist..."
if [ -d "$HOME/Library/Preferences/org.memlabs.Mem.plist" ]; then
    rm -rf "$HOME/Library/Preferences/org.memlabs.Mem.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/org.memlabs.Mem.plist" ]; then
    rm -f "$HOME/Library/Preferences/org.memlabs.Mem.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/org.memlabs.Mem.savedState
echo "Removing $HOME/Library/Saved Application State/org.memlabs.Mem.savedState..."
if [ -d "$HOME/Library/Saved Application State/org.memlabs.Mem.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/org.memlabs.Mem.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/org.memlabs.Mem.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/org.memlabs.Mem.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
