#!/bin/bash
# Uninstall script for Backlog
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Backlog..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Backlog if running..."
pkill -f "Backlog" 2>/dev/null || true

# Remove /Applications/Backlog-darwin-x64/Backlog.app
echo "Removing /Applications/Backlog-darwin-x64/Backlog.app..."
if [ -d "/Applications/Backlog-darwin-x64/Backlog.app" ]; then
    rm -rf "/Applications/Backlog-darwin-x64/Backlog.app" 2>/dev/null || true
elif [ -f "/Applications/Backlog-darwin-x64/Backlog.app" ]; then
    rm -f "/Applications/Backlog-darwin-x64/Backlog.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Backlog
echo "Removing $HOME/Library/Application Support/Backlog..."
if [ -d "$HOME/Library/Application Support/Backlog" ]; then
    rm -rf "$HOME/Library/Application Support/Backlog" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Backlog" ]; then
    rm -f "$HOME/Library/Application Support/Backlog" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
