#!/bin/bash
# Uninstall script for DataGraph
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling DataGraph..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping DataGraph if running..."
pkill -f "DataGraph" 2>/dev/null || true

# Remove /Applications/DataGraph.app
echo "Removing /Applications/DataGraph.app..."
if [ -d "/Applications/DataGraph.app" ]; then
    rm -rf "/Applications/DataGraph.app" 2>/dev/null || true
elif [ -f "/Applications/DataGraph.app" ]; then
    rm -f "/Applications/DataGraph.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.visualdatatools.datagraph.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.visualdatatools.datagraph.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.visualdatatools.datagraph.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.visualdatatools.datagraph.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.visualdatatools.datagraph.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.visualdatatools.datagraph.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.visualdatatools.datagraph
echo "Removing $HOME/Library/Application Support/com.visualdatatools.datagraph..."
if [ -d "$HOME/Library/Application Support/com.visualdatatools.datagraph" ]; then
    rm -rf "$HOME/Library/Application Support/com.visualdatatools.datagraph" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.visualdatatools.datagraph" ]; then
    rm -f "$HOME/Library/Application Support/com.visualdatatools.datagraph" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/DataGraph
echo "Removing $HOME/Library/Application Support/DataGraph..."
if [ -d "$HOME/Library/Application Support/DataGraph" ]; then
    rm -rf "$HOME/Library/Application Support/DataGraph" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/DataGraph" ]; then
    rm -f "$HOME/Library/Application Support/DataGraph" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.visualdatatools.datagraph
echo "Removing $HOME/Library/Caches/com.visualdatatools.datagraph..."
if [ -d "$HOME/Library/Caches/com.visualdatatools.datagraph" ]; then
    rm -rf "$HOME/Library/Caches/com.visualdatatools.datagraph" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.visualdatatools.datagraph" ]; then
    rm -f "$HOME/Library/Caches/com.visualdatatools.datagraph" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.visualdatatools.datagraph
echo "Removing $HOME/Library/HTTPStorages/com.visualdatatools.datagraph..."
if [ -d "$HOME/Library/HTTPStorages/com.visualdatatools.datagraph" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.visualdatatools.datagraph" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.visualdatatools.datagraph" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.visualdatatools.datagraph" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.visualdatatools.datagraph.plist
echo "Removing $HOME/Library/Preferences/com.visualdatatools.datagraph.plist..."
if [ -d "$HOME/Library/Preferences/com.visualdatatools.datagraph.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.visualdatatools.datagraph.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.visualdatatools.datagraph.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.visualdatatools.datagraph.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.visualdatatools.datagraph.savedState
echo "Removing $HOME/Library/Saved Application State/com.visualdatatools.datagraph.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.visualdatatools.datagraph.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.visualdatatools.datagraph.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.visualdatatools.datagraph.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.visualdatatools.datagraph.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
