#!/bin/bash
# Uninstall script for Insta360 Link Controller
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Insta360 Link Controller..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Insta360 Link Controller if running..."
pkill -f "Insta360 Link Controller" 2>/dev/null || true

# Kill application with bundle ID com.insta360.linkcontroller if running
echo "Stopping application with bundle ID com.insta360.linkcontroller if running..."
killall -9 "com.insta360.linkcontroller" 2>/dev/null || true

# Remove $HOME/Library/Application Support/Insta360/Insta360 Link Controller
echo "Removing $HOME/Library/Application Support/Insta360/Insta360 Link Controller..."
if [ -d "$HOME/Library/Application Support/Insta360/Insta360 Link Controller" ]; then
    rm -rf "$HOME/Library/Application Support/Insta360/Insta360 Link Controller" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Insta360/Insta360 Link Controller" ]; then
    rm -f "$HOME/Library/Application Support/Insta360/Insta360 Link Controller" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.insta360.linkcontroller
echo "Removing $HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.insta360.linkcontroller..."
if [ -d "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.insta360.linkcontroller" ]; then
    rm -rf "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.insta360.linkcontroller" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.insta360.linkcontroller" ]; then
    rm -f "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.insta360.linkcontroller" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/Insta360/Insta360 Link Controller
echo "Removing $HOME/Library/Caches/Insta360/Insta360 Link Controller..."
if [ -d "$HOME/Library/Caches/Insta360/Insta360 Link Controller" ]; then
    rm -rf "$HOME/Library/Caches/Insta360/Insta360 Link Controller" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/Insta360/Insta360 Link Controller" ]; then
    rm -f "$HOME/Library/Caches/Insta360/Insta360 Link Controller" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.insta360.linkcontroller.savedState
echo "Removing $HOME/Library/Saved Application State/com.insta360.linkcontroller.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.insta360.linkcontroller.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.insta360.linkcontroller.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.insta360.linkcontroller.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.insta360.linkcontroller.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
