#!/bin/bash
# Uninstall script for Zwift
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Zwift..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Zwift if running..."
pkill -f "Zwift" 2>/dev/null || true

# Kill application with bundle ID com.zwift.ZwiftLauncher if running
echo "Stopping application with bundle ID com.zwift.ZwiftLauncher if running..."
killall -9 "com.zwift.ZwiftLauncher" 2>/dev/null || true

# Remove $HOME/Library/Application Support/Zwift
echo "Removing $HOME/Library/Application Support/Zwift..."
if [ -d "$HOME/Library/Application Support/Zwift" ]; then
    rm -rf "$HOME/Library/Application Support/Zwift" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Zwift" ]; then
    rm -f "$HOME/Library/Application Support/Zwift" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
