#!/bin/bash
# Uninstall script for PopChar X
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling PopChar X..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping PopChar X if running..."
pkill -f "PopChar X" 2>/dev/null || true

# Remove /Applications/PopChar.app
echo "Removing /Applications/PopChar.app..."
if [ -d "/Applications/PopChar.app" ]; then
    rm -rf "/Applications/PopChar.app" 2>/dev/null || true
elif [ -f "/Applications/PopChar.app" ]; then
    rm -f "/Applications/PopChar.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/PopChar
echo "Removing $HOME/Library/Application Support/PopChar..."
if [ -d "$HOME/Library/Application Support/PopChar" ]; then
    rm -rf "$HOME/Library/Application Support/PopChar" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/PopChar" ]; then
    rm -f "$HOME/Library/Application Support/PopChar" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.macility.popchar3
echo "Removing $HOME/Library/Caches/com.macility.popchar3..."
if [ -d "$HOME/Library/Caches/com.macility.popchar3" ]; then
    rm -rf "$HOME/Library/Caches/com.macility.popchar3" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.macility.popchar3" ]; then
    rm -f "$HOME/Library/Caches/com.macility.popchar3" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.macility.popchar3
echo "Removing $HOME/Library/HTTPStorages/com.macility.popchar3..."
if [ -d "$HOME/Library/HTTPStorages/com.macility.popchar3" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.macility.popchar3" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.macility.popchar3" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.macility.popchar3" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.macility.popchar3.plist
echo "Removing $HOME/Library/Preferences/com.macility.popchar3.plist..."
if [ -d "$HOME/Library/Preferences/com.macility.popchar3.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.macility.popchar3.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.macility.popchar3.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.macility.popchar3.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
