#!/bin/bash
# Uninstall script for gPodder
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling gPodder..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping gPodder if running..."
pkill -f "gPodder" 2>/dev/null || true

# Remove /Applications/gPodder.app
echo "Removing /Applications/gPodder.app..."
if [ -d "/Applications/gPodder.app" ]; then
    rm -rf "/Applications/gPodder.app" 2>/dev/null || true
elif [ -f "/Applications/gPodder.app" ]; then
    rm -f "/Applications/gPodder.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/gPodder
echo "Removing $HOME/Library/Application Support/gPodder..."
if [ -d "$HOME/Library/Application Support/gPodder" ]; then
    rm -rf "$HOME/Library/Application Support/gPodder" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/gPodder" ]; then
    rm -f "$HOME/Library/Application Support/gPodder" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
