#!/bin/bash
# Uninstall script for EagleFiler
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling EagleFiler..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping EagleFiler if running..."
pkill -f "EagleFiler" 2>/dev/null || true

# Remove /Applications/EagleFiler.app
echo "Removing /Applications/EagleFiler.app..."
if [ -d "/Applications/EagleFiler.app" ]; then
    rm -rf "/Applications/EagleFiler.app" 2>/dev/null || true
elif [ -f "/Applications/EagleFiler.app" ]; then
    rm -f "/Applications/EagleFiler.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.c-command.EagleFiler.EagleFilerShare
echo "Removing $HOME/Library/Application Scripts/com.c-command.EagleFiler.EagleFilerShare..."
if [ -d "$HOME/Library/Application Scripts/com.c-command.EagleFiler.EagleFilerShare" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.c-command.EagleFiler.EagleFilerShare" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.c-command.EagleFiler.EagleFilerShare" ]; then
    rm -f "$HOME/Library/Application Scripts/com.c-command.EagleFiler.EagleFilerShare" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.c-command.eaglefiler.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.c-command.eaglefiler.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.c-command.eaglefiler.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.c-command.eaglefiler.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.c-command.eaglefiler.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.c-command.eaglefiler.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/EagleFiler
echo "Removing $HOME/Library/Application Support/EagleFiler..."
if [ -d "$HOME/Library/Application Support/EagleFiler" ]; then
    rm -rf "$HOME/Library/Application Support/EagleFiler" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/EagleFiler" ]; then
    rm -f "$HOME/Library/Application Support/EagleFiler" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.c-command.EagleFiler
echo "Removing $HOME/Library/Caches/com.c-command.EagleFiler..."
if [ -d "$HOME/Library/Caches/com.c-command.EagleFiler" ]; then
    rm -rf "$HOME/Library/Caches/com.c-command.EagleFiler" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.c-command.EagleFiler" ]; then
    rm -f "$HOME/Library/Caches/com.c-command.EagleFiler" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.c-command.EagleFiler.EagleFilerShare
echo "Removing $HOME/Library/Containers/com.c-command.EagleFiler.EagleFilerShare..."
if [ -d "$HOME/Library/Containers/com.c-command.EagleFiler.EagleFilerShare" ]; then
    rm -rf "$HOME/Library/Containers/com.c-command.EagleFiler.EagleFilerShare" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.c-command.EagleFiler.EagleFilerShare" ]; then
    rm -f "$HOME/Library/Containers/com.c-command.EagleFiler.EagleFilerShare" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.c-command.EagleFiler
echo "Removing $HOME/Library/HTTPStorages/com.c-command.EagleFiler..."
if [ -d "$HOME/Library/HTTPStorages/com.c-command.EagleFiler" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.c-command.EagleFiler" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.c-command.EagleFiler" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.c-command.EagleFiler" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/EagleFiler
echo "Removing $HOME/Library/Logs/EagleFiler..."
if [ -d "$HOME/Library/Logs/EagleFiler" ]; then
    rm -rf "$HOME/Library/Logs/EagleFiler" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/EagleFiler" ]; then
    rm -f "$HOME/Library/Logs/EagleFiler" 2>/dev/null || true
fi

# Remove $HOME/Library/PDF Services/Save PDF to EagleFiler
echo "Removing $HOME/Library/PDF Services/Save PDF to EagleFiler..."
if [ -d "$HOME/Library/PDF Services/Save PDF to EagleFiler" ]; then
    rm -rf "$HOME/Library/PDF Services/Save PDF to EagleFiler" 2>/dev/null || true
elif [ -f "$HOME/Library/PDF Services/Save PDF to EagleFiler" ]; then
    rm -f "$HOME/Library/PDF Services/Save PDF to EagleFiler" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.c-command.EagleFiler.plist
echo "Removing $HOME/Library/Preferences/com.c-command.EagleFiler.plist..."
if [ -d "$HOME/Library/Preferences/com.c-command.EagleFiler.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.c-command.EagleFiler.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.c-command.EagleFiler.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.c-command.EagleFiler.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.c-command.EagleFiler.savedState
echo "Removing $HOME/Library/Saved Application State/com.c-command.EagleFiler.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.c-command.EagleFiler.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.c-command.EagleFiler.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.c-command.EagleFiler.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.c-command.EagleFiler.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
