#!/bin/bash
# Uninstall script for IconJar
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling IconJar..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping IconJar if running..."
pkill -f "IconJar" 2>/dev/null || true

# Remove /Applications/IconJar.app
echo "Removing /Applications/IconJar.app..."
if [ -d "/Applications/IconJar.app" ]; then
    rm -rf "/Applications/IconJar.app" 2>/dev/null || true
elif [ -f "/Applications/IconJar.app" ]; then
    rm -f "/Applications/IconJar.app" 2>/dev/null || true
fi

# Remove /Users/Shared/IconJar
echo "Removing /Users/Shared/IconJar..."
if [ -d "/Users/Shared/IconJar" ]; then
    rm -rf "/Users/Shared/IconJar" 2>/dev/null || true
elif [ -f "/Users/Shared/IconJar" ]; then
    rm -f "/Users/Shared/IconJar" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/IconJar
echo "Removing $HOME/Library/Application Support/IconJar..."
if [ -d "$HOME/Library/Application Support/IconJar" ]; then
    rm -rf "$HOME/Library/Application Support/IconJar" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/IconJar" ]; then
    rm -f "$HOME/Library/Application Support/IconJar" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.iconjar.iconjar.plist
echo "Removing $HOME/Library/Preferences/com.iconjar.iconjar.plist..."
if [ -d "$HOME/Library/Preferences/com.iconjar.iconjar.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.iconjar.iconjar.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.iconjar.iconjar.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.iconjar.iconjar.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
