#!/bin/bash
# Uninstall script for SwiftBar
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling SwiftBar..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping SwiftBar if running..."
pkill -f "SwiftBar" 2>/dev/null || true

# Remove /Applications/SwiftBar.app
echo "Removing /Applications/SwiftBar.app..."
if [ -d "/Applications/SwiftBar.app" ]; then
    rm -rf "/Applications/SwiftBar.app" 2>/dev/null || true
elif [ -f "/Applications/SwiftBar.app" ]; then
    rm -f "/Applications/SwiftBar.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.ameba.SwiftBar-LaunchAtLoginHelper
echo "Removing $HOME/Library/Application Scripts/com.ameba.SwiftBar-LaunchAtLoginHelper..."
if [ -d "$HOME/Library/Application Scripts/com.ameba.SwiftBar-LaunchAtLoginHelper" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.ameba.SwiftBar-LaunchAtLoginHelper" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.ameba.SwiftBar-LaunchAtLoginHelper" ]; then
    rm -f "$HOME/Library/Application Scripts/com.ameba.SwiftBar-LaunchAtLoginHelper" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.ameba.SwiftBar
echo "Removing $HOME/Library/Caches/com.ameba.SwiftBar..."
if [ -d "$HOME/Library/Caches/com.ameba.SwiftBar" ]; then
    rm -rf "$HOME/Library/Caches/com.ameba.SwiftBar" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.ameba.SwiftBar" ]; then
    rm -f "$HOME/Library/Caches/com.ameba.SwiftBar" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.ameba.SwiftBar-LaunchAtLoginHelper
echo "Removing $HOME/Library/Containers/com.ameba.SwiftBar-LaunchAtLoginHelper..."
if [ -d "$HOME/Library/Containers/com.ameba.SwiftBar-LaunchAtLoginHelper" ]; then
    rm -rf "$HOME/Library/Containers/com.ameba.SwiftBar-LaunchAtLoginHelper" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.ameba.SwiftBar-LaunchAtLoginHelper" ]; then
    rm -f "$HOME/Library/Containers/com.ameba.SwiftBar-LaunchAtLoginHelper" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.ameba.SwiftBar.plist
echo "Removing $HOME/Library/Preferences/com.ameba.SwiftBar.plist..."
if [ -d "$HOME/Library/Preferences/com.ameba.SwiftBar.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.ameba.SwiftBar.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.ameba.SwiftBar.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.ameba.SwiftBar.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
