#!/bin/bash
# Uninstall script for Autodesk Fusion 360
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Autodesk Fusion 360..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Autodesk Fusion 360 if running..."
pkill -f "Autodesk Fusion 360" 2>/dev/null || true

# Kill application with bundle ID com.autodesk.dls.streamer.scriptapp.Autodesk-Fusion if running
echo "Stopping application with bundle ID com.autodesk.dls.streamer.scriptapp.Autodesk-Fusion if running..."
killall -9 "com.autodesk.dls.streamer.scriptapp.Autodesk-Fusion" 2>/dev/null || true

# Kill application with bundle ID com.autodesk.fusion if running
echo "Stopping application with bundle ID com.autodesk.fusion if running..."
killall -9 "com.autodesk.fusion" 2>/dev/null || true

# Remove /Users/Shared/Autodesk
echo "Removing /Users/Shared/Autodesk..."
if [ -d "/Users/Shared/Autodesk" ]; then
    rm -rf "/Users/Shared/Autodesk" 2>/dev/null || true
elif [ -f "/Users/Shared/Autodesk" ]; then
    rm -f "/Users/Shared/Autodesk" 2>/dev/null || true
fi

# Remove $HOME/.config/Autodesk
echo "Removing $HOME/.config/Autodesk..."
if [ -d "$HOME/.config/Autodesk" ]; then
    rm -rf "$HOME/.config/Autodesk" 2>/dev/null || true
elif [ -f "$HOME/.config/Autodesk" ]; then
    rm -f "$HOME/.config/Autodesk" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Autodesk
echo "Removing $HOME/Library/Application Support/Autodesk..."
if [ -d "$HOME/Library/Application Support/Autodesk" ]; then
    rm -rf "$HOME/Library/Application Support/Autodesk" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Autodesk" ]; then
    rm -f "$HOME/Library/Application Support/Autodesk" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Fusion 360
echo "Removing $HOME/Library/Application Support/Fusion 360..."
if [ -d "$HOME/Library/Application Support/Fusion 360" ]; then
    rm -rf "$HOME/Library/Application Support/Fusion 360" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Fusion 360" ]; then
    rm -f "$HOME/Library/Application Support/Fusion 360" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Fusion
echo "Removing $HOME/Library/Application Support/Fusion..."
if [ -d "$HOME/Library/Application Support/Fusion" ]; then
    rm -rf "$HOME/Library/Application Support/Fusion" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Fusion" ]; then
    rm -f "$HOME/Library/Application Support/Fusion" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.autodesk.AdskIdentityManager
echo "Removing $HOME/Library/Caches/com.autodesk.AdskIdentityManager..."
if [ -d "$HOME/Library/Caches/com.autodesk.AdskIdentityManager" ]; then
    rm -rf "$HOME/Library/Caches/com.autodesk.AdskIdentityManager" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.autodesk.AdskIdentityManager" ]; then
    rm -f "$HOME/Library/Caches/com.autodesk.AdskIdentityManager" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.autodesk.fusion360
echo "Removing $HOME/Library/Caches/com.autodesk.fusion360..."
if [ -d "$HOME/Library/Caches/com.autodesk.fusion360" ]; then
    rm -rf "$HOME/Library/Caches/com.autodesk.fusion360" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.autodesk.fusion360" ]; then
    rm -f "$HOME/Library/Caches/com.autodesk.fusion360" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.autodesk.fusion360.senddmp
echo "Removing $HOME/Library/Caches/com.autodesk.fusion360.senddmp..."
if [ -d "$HOME/Library/Caches/com.autodesk.fusion360.senddmp" ]; then
    rm -rf "$HOME/Library/Caches/com.autodesk.fusion360.senddmp" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.autodesk.fusion360.senddmp" ]; then
    rm -f "$HOME/Library/Caches/com.autodesk.fusion360.senddmp" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.Autodesk.streamer
echo "Removing $HOME/Library/Caches/com.Autodesk.streamer..."
if [ -d "$HOME/Library/Caches/com.Autodesk.streamer" ]; then
    rm -rf "$HOME/Library/Caches/com.Autodesk.streamer" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.Autodesk.streamer" ]; then
    rm -f "$HOME/Library/Caches/com.Autodesk.streamer" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/Fusion
echo "Removing $HOME/Library/Caches/Fusion..."
if [ -d "$HOME/Library/Caches/Fusion" ]; then
    rm -rf "$HOME/Library/Caches/Fusion" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/Fusion" ]; then
    rm -f "$HOME/Library/Caches/Fusion" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.autodesk.fusion360
echo "Removing $HOME/Library/HTTPStorages/com.autodesk.fusion360..."
if [ -d "$HOME/Library/HTTPStorages/com.autodesk.fusion360" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.autodesk.fusion360" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.autodesk.fusion360" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.autodesk.fusion360" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.autodesk.fusion360.binarycookies
echo "Removing $HOME/Library/HTTPStorages/com.autodesk.fusion360.binarycookies..."
if [ -d "$HOME/Library/HTTPStorages/com.autodesk.fusion360.binarycookies" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.autodesk.fusion360.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.autodesk.fusion360.binarycookies" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.autodesk.fusion360.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.autodesk.fusion360.senddmp
echo "Removing $HOME/Library/HTTPStorages/com.autodesk.fusion360.senddmp..."
if [ -d "$HOME/Library/HTTPStorages/com.autodesk.fusion360.senddmp" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.autodesk.fusion360.senddmp" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.autodesk.fusion360.senddmp" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.autodesk.fusion360.senddmp" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.Autodesk.streamer
echo "Removing $HOME/Library/HTTPStorages/com.Autodesk.streamer..."
if [ -d "$HOME/Library/HTTPStorages/com.Autodesk.streamer" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.Autodesk.streamer" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.Autodesk.streamer" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.Autodesk.streamer" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/autodesk.webdeploy.streamer.log
echo "Removing $HOME/Library/Logs/autodesk.webdeploy.streamer.log..."
if [ -d "$HOME/Library/Logs/autodesk.webdeploy.streamer.log" ]; then
    rm -rf "$HOME/Library/Logs/autodesk.webdeploy.streamer.log" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/autodesk.webdeploy.streamer.log" ]; then
    rm -f "$HOME/Library/Logs/autodesk.webdeploy.streamer.log" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.autodesk.adskidentitymanager.Autodesk Identity Manager.plist
echo "Removing $HOME/Library/Preferences/com.autodesk.adskidentitymanager.Autodesk Identity Manager.plist..."
if [ -d "$HOME/Library/Preferences/com.autodesk.adskidentitymanager.Autodesk Identity Manager.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.autodesk.adskidentitymanager.Autodesk Identity Manager.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.autodesk.adskidentitymanager.Autodesk Identity Manager.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.autodesk.adskidentitymanager.Autodesk Identity Manager.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.autodesk.EAGLE 9.7.0.plist
echo "Removing $HOME/Library/Preferences/com.autodesk.EAGLE 9.7.0.plist..."
if [ -d "$HOME/Library/Preferences/com.autodesk.EAGLE 9.7.0.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.autodesk.EAGLE 9.7.0.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.autodesk.EAGLE 9.7.0.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.autodesk.EAGLE 9.7.0.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.autodesk.fusion360.plist
echo "Removing $HOME/Library/Preferences/com.autodesk.fusion360.plist..."
if [ -d "$HOME/Library/Preferences/com.autodesk.fusion360.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.autodesk.fusion360.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.autodesk.fusion360.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.autodesk.fusion360.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.autodesk.fusion360.savedState
echo "Removing $HOME/Library/Saved Application State/com.autodesk.fusion360.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.autodesk.fusion360.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.autodesk.fusion360.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.autodesk.fusion360.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.autodesk.fusion360.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.Autodesk.streamer.savedState
echo "Removing $HOME/Library/Saved Application State/com.Autodesk.streamer.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.Autodesk.streamer.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.Autodesk.streamer.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.Autodesk.streamer.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.Autodesk.streamer.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.autodesk.AdskIdentityManager
echo "Removing $HOME/Library/WebKit/com.autodesk.AdskIdentityManager..."
if [ -d "$HOME/Library/WebKit/com.autodesk.AdskIdentityManager" ]; then
    rm -rf "$HOME/Library/WebKit/com.autodesk.AdskIdentityManager" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.autodesk.AdskIdentityManager" ]; then
    rm -f "$HOME/Library/WebKit/com.autodesk.AdskIdentityManager" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
