#!/bin/bash
# Uninstall script for Numi
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Numi..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Numi if running..."
pkill -f "Numi" 2>/dev/null || true

# Unload service com.dmitrynikolaev.numi3helper
echo "Unloading service com.dmitrynikolaev.numi3helper..."
launchctl unload -w /Library/LaunchAgents/com.dmitrynikolaev.numi3helper.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.dmitrynikolaev.numi3helper.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.dmitrynikolaev.numi3helper.plist 2>/dev/null || true

# Kill application with bundle ID com.dmitrynikolaev.numi if running
echo "Stopping application with bundle ID com.dmitrynikolaev.numi if running..."
killall -9 "com.dmitrynikolaev.numi" 2>/dev/null || true

# Remove /Applications/Numi.app
echo "Removing /Applications/Numi.app..."
if [ -d "/Applications/Numi.app" ]; then
    rm -rf "/Applications/Numi.app" 2>/dev/null || true
elif [ -f "/Applications/Numi.app" ]; then
    rm -f "/Applications/Numi.app" 2>/dev/null || true
fi

# Remove /Users/Shared/Numi
echo "Removing /Users/Shared/Numi..."
if [ -d "/Users/Shared/Numi" ]; then
    rm -rf "/Users/Shared/Numi" 2>/dev/null || true
elif [ -f "/Users/Shared/Numi" ]; then
    rm -f "/Users/Shared/Numi" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.dmitrynikolaev.numi
echo "Removing $HOME/Library/Application Support/com.dmitrynikolaev.numi..."
if [ -d "$HOME/Library/Application Support/com.dmitrynikolaev.numi" ]; then
    rm -rf "$HOME/Library/Application Support/com.dmitrynikolaev.numi" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.dmitrynikolaev.numi" ]; then
    rm -f "$HOME/Library/Application Support/com.dmitrynikolaev.numi" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/CrashReporter/Numi_*.plist
echo "Removing $HOME/Library/Application Support/CrashReporter/Numi_*.plist..."
if [ -d "$HOME/Library/Application Support/CrashReporter/Numi_*.plist" ]; then
    rm -rf "$HOME/Library/Application Support/CrashReporter/Numi_*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/CrashReporter/Numi_*.plist" ]; then
    rm -f "$HOME/Library/Application Support/CrashReporter/Numi_*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Numi
echo "Removing $HOME/Library/Application Support/Numi..."
if [ -d "$HOME/Library/Application Support/Numi" ]; then
    rm -rf "$HOME/Library/Application Support/Numi" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Numi" ]; then
    rm -f "$HOME/Library/Application Support/Numi" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.crashlytics.data/com.dmitrynikolaev.numi
echo "Removing $HOME/Library/Caches/com.crashlytics.data/com.dmitrynikolaev.numi..."
if [ -d "$HOME/Library/Caches/com.crashlytics.data/com.dmitrynikolaev.numi" ]; then
    rm -rf "$HOME/Library/Caches/com.crashlytics.data/com.dmitrynikolaev.numi" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.crashlytics.data/com.dmitrynikolaev.numi" ]; then
    rm -f "$HOME/Library/Caches/com.crashlytics.data/com.dmitrynikolaev.numi" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.dmitrynikolaev.numi
echo "Removing $HOME/Library/Caches/com.dmitrynikolaev.numi..."
if [ -d "$HOME/Library/Caches/com.dmitrynikolaev.numi" ]; then
    rm -rf "$HOME/Library/Caches/com.dmitrynikolaev.numi" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.dmitrynikolaev.numi" ]; then
    rm -f "$HOME/Library/Caches/com.dmitrynikolaev.numi" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/io.fabric.sdk.mac.data/com.dmitrynikolaev.numi
echo "Removing $HOME/Library/Caches/io.fabric.sdk.mac.data/com.dmitrynikolaev.numi..."
if [ -d "$HOME/Library/Caches/io.fabric.sdk.mac.data/com.dmitrynikolaev.numi" ]; then
    rm -rf "$HOME/Library/Caches/io.fabric.sdk.mac.data/com.dmitrynikolaev.numi" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/io.fabric.sdk.mac.data/com.dmitrynikolaev.numi" ]; then
    rm -f "$HOME/Library/Caches/io.fabric.sdk.mac.data/com.dmitrynikolaev.numi" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.dmitrynikolaev.numi.NumiExtension
echo "Removing $HOME/Library/Containers/com.dmitrynikolaev.numi.NumiExtension..."
if [ -d "$HOME/Library/Containers/com.dmitrynikolaev.numi.NumiExtension" ]; then
    rm -rf "$HOME/Library/Containers/com.dmitrynikolaev.numi.NumiExtension" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.dmitrynikolaev.numi.NumiExtension" ]; then
    rm -f "$HOME/Library/Containers/com.dmitrynikolaev.numi.NumiExtension" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.dmitrynikolaev.numi.plist
echo "Removing $HOME/Library/Preferences/com.dmitrynikolaev.numi.plist..."
if [ -d "$HOME/Library/Preferences/com.dmitrynikolaev.numi.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.dmitrynikolaev.numi.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.dmitrynikolaev.numi.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.dmitrynikolaev.numi.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
