#!/bin/bash
# Uninstall script for Douyin
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Douyin..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Douyin if running..."
pkill -f "Douyin" 2>/dev/null || true

# Remove /Applications/抖音.app
echo "Removing /Applications/抖音.app..."
if [ -d "/Applications/抖音.app" ]; then
    rm -rf "/Applications/抖音.app" 2>/dev/null || true
elif [ -f "/Applications/抖音.app" ]; then
    rm -f "/Applications/抖音.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.bytedance.douyin.desktop.*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.bytedance.douyin.desktop.*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.bytedance.douyin.desktop.*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.bytedance.douyin.desktop.*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.bytedance.douyin.desktop.*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.bytedance.douyin.desktop.*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.bytedance.douyin.desktop
echo "Removing $HOME/Library/Caches/com.bytedance.douyin.desktop..."
if [ -d "$HOME/Library/Caches/com.bytedance.douyin.desktop" ]; then
    rm -rf "$HOME/Library/Caches/com.bytedance.douyin.desktop" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.bytedance.douyin.desktop" ]; then
    rm -f "$HOME/Library/Caches/com.bytedance.douyin.desktop" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.bytedance.douyin.desktop
echo "Removing $HOME/Library/HTTPStorages/com.bytedance.douyin.desktop..."
if [ -d "$HOME/Library/HTTPStorages/com.bytedance.douyin.desktop" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.bytedance.douyin.desktop" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.bytedance.douyin.desktop" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.bytedance.douyin.desktop" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/douyin
echo "Removing $HOME/Library/Logs/douyin..."
if [ -d "$HOME/Library/Logs/douyin" ]; then
    rm -rf "$HOME/Library/Logs/douyin" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/douyin" ]; then
    rm -f "$HOME/Library/Logs/douyin" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.bytedance.douyin.desktop.plist
echo "Removing $HOME/Library/Preferences/com.bytedance.douyin.desktop.plist..."
if [ -d "$HOME/Library/Preferences/com.bytedance.douyin.desktop.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.bytedance.douyin.desktop.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.bytedance.douyin.desktop.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.bytedance.douyin.desktop.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.bytedance.douyin.desktop.savedState
echo "Removing $HOME/Library/Saved Application State/com.bytedance.douyin.desktop.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.bytedance.douyin.desktop.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.bytedance.douyin.desktop.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.bytedance.douyin.desktop.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.bytedance.douyin.desktop.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/抖音
echo "Removing $HOME/Library/Application Support/抖音..."
if [ -d "$HOME/Library/Application Support/抖音" ]; then
    rm -rf "$HOME/Library/Application Support/抖音" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/抖音" ]; then
    rm -f "$HOME/Library/Application Support/抖音" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
