#!/bin/bash
# Uninstall script for BankID Security Application (Sweden)
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling BankID Security Application (Sweden)..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping BankID Security Application (Sweden) if running..."
pkill -f "BankID Security Application (Sweden)" 2>/dev/null || true

# Remove $HOME/Library/Application Support/BankID
echo "Removing $HOME/Library/Application Support/BankID..."
if [ -d "$HOME/Library/Application Support/BankID" ]; then
    rm -rf "$HOME/Library/Application Support/BankID" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/BankID" ]; then
    rm -f "$HOME/Library/Application Support/BankID" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
