#!/bin/bash
# Uninstall script for Ungoogled Chromium
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Ungoogled Chromium..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Ungoogled Chromium if running..."
pkill -f "Ungoogled Chromium" 2>/dev/null || true

# Remove /Applications/Chromium.app
echo "Removing /Applications/Chromium.app..."
if [ -d "/Applications/Chromium.app" ]; then
    rm -rf "/Applications/Chromium.app" 2>/dev/null || true
elif [ -f "/Applications/Chromium.app" ]; then
    rm -f "/Applications/Chromium.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Chromium
echo "Removing $HOME/Library/Application Support/Chromium..."
if [ -d "$HOME/Library/Application Support/Chromium" ]; then
    rm -rf "$HOME/Library/Application Support/Chromium" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Chromium" ]; then
    rm -f "$HOME/Library/Application Support/Chromium" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/Chromium
echo "Removing $HOME/Library/Caches/Chromium..."
if [ -d "$HOME/Library/Caches/Chromium" ]; then
    rm -rf "$HOME/Library/Caches/Chromium" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/Chromium" ]; then
    rm -f "$HOME/Library/Caches/Chromium" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/org.chromium.Chromium.plist
echo "Removing $HOME/Library/Preferences/org.chromium.Chromium.plist..."
if [ -d "$HOME/Library/Preferences/org.chromium.Chromium.plist" ]; then
    rm -rf "$HOME/Library/Preferences/org.chromium.Chromium.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/org.chromium.Chromium.plist" ]; then
    rm -f "$HOME/Library/Preferences/org.chromium.Chromium.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/org.chromium.Chromium.savedState
echo "Removing $HOME/Library/Saved Application State/org.chromium.Chromium.savedState..."
if [ -d "$HOME/Library/Saved Application State/org.chromium.Chromium.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/org.chromium.Chromium.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/org.chromium.Chromium.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/org.chromium.Chromium.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
