#!/bin/bash
# Uninstall script for CleanClip
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling CleanClip..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping CleanClip if running..."
pkill -f "CleanClip" 2>/dev/null || true

# Remove /Applications/CleanClip.app
echo "Removing /Applications/CleanClip.app..."
if [ -d "/Applications/CleanClip.app" ]; then
    rm -rf "/Applications/CleanClip.app" 2>/dev/null || true
elif [ -f "/Applications/CleanClip.app" ]; then
    rm -f "/Applications/CleanClip.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/CleanClip
echo "Removing $HOME/Library/Application Support/CleanClip..."
if [ -d "$HOME/Library/Application Support/CleanClip" ]; then
    rm -rf "$HOME/Library/Application Support/CleanClip" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/CleanClip" ]; then
    rm -f "$HOME/Library/Application Support/CleanClip" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.antiless.cleanclip.mac
echo "Removing $HOME/Library/Caches/com.antiless.cleanclip.mac..."
if [ -d "$HOME/Library/Caches/com.antiless.cleanclip.mac" ]; then
    rm -rf "$HOME/Library/Caches/com.antiless.cleanclip.mac" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.antiless.cleanclip.mac" ]; then
    rm -f "$HOME/Library/Caches/com.antiless.cleanclip.mac" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.antiless.cleanclip.mac.plist
echo "Removing $HOME/Library/Preferences/com.antiless.cleanclip.mac.plist..."
if [ -d "$HOME/Library/Preferences/com.antiless.cleanclip.mac.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.antiless.cleanclip.mac.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.antiless.cleanclip.mac.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.antiless.cleanclip.mac.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
