#!/bin/bash
# Uninstall script for Extraterm
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Extraterm..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Extraterm if running..."
pkill -f "Extraterm" 2>/dev/null || true

# Remove /Applications/ExtratermQt.app
echo "Removing /Applications/ExtratermQt.app..."
if [ -d "/Applications/ExtratermQt.app" ]; then
    rm -rf "/Applications/ExtratermQt.app" 2>/dev/null || true
elif [ -f "/Applications/ExtratermQt.app" ]; then
    rm -f "/Applications/ExtratermQt.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/extraterm
echo "Removing $HOME/Library/Application Support/extraterm..."
if [ -d "$HOME/Library/Application Support/extraterm" ]; then
    rm -rf "$HOME/Library/Application Support/extraterm" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/extraterm" ]; then
    rm -f "$HOME/Library/Application Support/extraterm" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.electron.extraterm*.plist
echo "Removing $HOME/Library/Preferences/com.electron.extraterm*.plist..."
if [ -d "$HOME/Library/Preferences/com.electron.extraterm*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.electron.extraterm*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.electron.extraterm*.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.electron.extraterm*.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
