#!/bin/bash
# Uninstall script for Rambox
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Rambox..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Rambox if running..."
pkill -f "Rambox" 2>/dev/null || true

# Remove /Applications/Rambox.app
echo "Removing /Applications/Rambox.app..."
if [ -d "/Applications/Rambox.app" ]; then
    rm -rf "/Applications/Rambox.app" 2>/dev/null || true
elif [ -f "/Applications/Rambox.app" ]; then
    rm -f "/Applications/Rambox.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/CrashReporter/Rambox Helper_*.plist
echo "Removing $HOME/Library/Application Support/CrashReporter/Rambox Helper_*.plist..."
if [ -d "$HOME/Library/Application Support/CrashReporter/Rambox Helper_*.plist" ]; then
    rm -rf "$HOME/Library/Application Support/CrashReporter/Rambox Helper_*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/CrashReporter/Rambox Helper_*.plist" ]; then
    rm -f "$HOME/Library/Application Support/CrashReporter/Rambox Helper_*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/CrashReporter/Rambox_*.plist
echo "Removing $HOME/Library/Application Support/CrashReporter/Rambox_*.plist..."
if [ -d "$HOME/Library/Application Support/CrashReporter/Rambox_*.plist" ]; then
    rm -rf "$HOME/Library/Application Support/CrashReporter/Rambox_*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/CrashReporter/Rambox_*.plist" ]; then
    rm -f "$HOME/Library/Application Support/CrashReporter/Rambox_*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Rambox
echo "Removing $HOME/Library/Application Support/Rambox..."
if [ -d "$HOME/Library/Application Support/Rambox" ]; then
    rm -rf "$HOME/Library/Application Support/Rambox" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Rambox" ]; then
    rm -f "$HOME/Library/Application Support/Rambox" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.grupovrs.ramboxce
echo "Removing $HOME/Library/Caches/com.grupovrs.ramboxce..."
if [ -d "$HOME/Library/Caches/com.grupovrs.ramboxce" ]; then
    rm -rf "$HOME/Library/Caches/com.grupovrs.ramboxce" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.grupovrs.ramboxce" ]; then
    rm -f "$HOME/Library/Caches/com.grupovrs.ramboxce" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.grupovrs.ramboxce.ShipIt
echo "Removing $HOME/Library/Caches/com.grupovrs.ramboxce.ShipIt..."
if [ -d "$HOME/Library/Caches/com.grupovrs.ramboxce.ShipIt" ]; then
    rm -rf "$HOME/Library/Caches/com.grupovrs.ramboxce.ShipIt" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.grupovrs.ramboxce.ShipIt" ]; then
    rm -f "$HOME/Library/Caches/com.grupovrs.ramboxce.ShipIt" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.saenzramiro.rambox
echo "Removing $HOME/Library/Caches/com.saenzramiro.rambox..."
if [ -d "$HOME/Library/Caches/com.saenzramiro.rambox" ]; then
    rm -rf "$HOME/Library/Caches/com.saenzramiro.rambox" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.saenzramiro.rambox" ]; then
    rm -f "$HOME/Library/Caches/com.saenzramiro.rambox" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Rambox
echo "Removing $HOME/Library/Logs/Rambox..."
if [ -d "$HOME/Library/Logs/Rambox" ]; then
    rm -rf "$HOME/Library/Logs/Rambox" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Rambox" ]; then
    rm -f "$HOME/Library/Logs/Rambox" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/ByHost/com.grupovrs.ramboxce.ShipIt.*.plist
echo "Removing $HOME/Library/Preferences/ByHost/com.grupovrs.ramboxce.ShipIt.*.plist..."
if [ -d "$HOME/Library/Preferences/ByHost/com.grupovrs.ramboxce.ShipIt.*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/ByHost/com.grupovrs.ramboxce.ShipIt.*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/ByHost/com.grupovrs.ramboxce.ShipIt.*.plist" ]; then
    rm -f "$HOME/Library/Preferences/ByHost/com.grupovrs.ramboxce.ShipIt.*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.grupovrs.ramboxce.helper.plist
echo "Removing $HOME/Library/Preferences/com.grupovrs.ramboxce.helper.plist..."
if [ -d "$HOME/Library/Preferences/com.grupovrs.ramboxce.helper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.grupovrs.ramboxce.helper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.grupovrs.ramboxce.helper.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.grupovrs.ramboxce.helper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.grupovrs.ramboxce.plist
echo "Removing $HOME/Library/Preferences/com.grupovrs.ramboxce.plist..."
if [ -d "$HOME/Library/Preferences/com.grupovrs.ramboxce.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.grupovrs.ramboxce.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.grupovrs.ramboxce.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.grupovrs.ramboxce.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.saenzramiro.rambox.helper.plist
echo "Removing $HOME/Library/Preferences/com.saenzramiro.rambox.helper.plist..."
if [ -d "$HOME/Library/Preferences/com.saenzramiro.rambox.helper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.saenzramiro.rambox.helper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.saenzramiro.rambox.helper.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.saenzramiro.rambox.helper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.saenzramiro.rambox.plist
echo "Removing $HOME/Library/Preferences/com.saenzramiro.rambox.plist..."
if [ -d "$HOME/Library/Preferences/com.saenzramiro.rambox.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.saenzramiro.rambox.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.saenzramiro.rambox.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.saenzramiro.rambox.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.grupovrs.ramboxce.savedState
echo "Removing $HOME/Library/Saved Application State/com.grupovrs.ramboxce.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.grupovrs.ramboxce.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.grupovrs.ramboxce.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.grupovrs.ramboxce.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.grupovrs.ramboxce.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.saenzramiro.rambox.savedState
echo "Removing $HOME/Library/Saved Application State/com.saenzramiro.rambox.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.saenzramiro.rambox.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.saenzramiro.rambox.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.saenzramiro.rambox.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.saenzramiro.rambox.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.saenzramiro.rambox
echo "Removing $HOME/Library/WebKit/com.saenzramiro.rambox..."
if [ -d "$HOME/Library/WebKit/com.saenzramiro.rambox" ]; then
    rm -rf "$HOME/Library/WebKit/com.saenzramiro.rambox" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.saenzramiro.rambox" ]; then
    rm -f "$HOME/Library/WebKit/com.saenzramiro.rambox" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
