#!/bin/bash
# Uninstall script for Dorico
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Dorico..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Dorico if running..."
pkill -f "Dorico" 2>/dev/null || true

# Kill application with bundle ID com.steinberg.AudioFileHandler.MPG3 if running
echo "Stopping application with bundle ID com.steinberg.AudioFileHandler.MPG3 if running..."
killall -9 "com.steinberg.AudioFileHandler.MPG3" 2>/dev/null || true

# Kill application with bundle ID com.steinberg.AudioFileHandler.Xiph if running
echo "Stopping application with bundle ID com.steinberg.AudioFileHandler.Xiph if running..."
killall -9 "com.steinberg.AudioFileHandler.Xiph" 2>/dev/null || true

# Kill application with bundle ID com.steinberg.baios if running
echo "Stopping application with bundle ID com.steinberg.baios if running..."
killall -9 "com.steinberg.baios" 2>/dev/null || true

# Kill application with bundle ID com.steinberg.CoreAudio2ASIO if running
echo "Stopping application with bundle ID com.steinberg.CoreAudio2ASIO if running..."
killall -9 "com.steinberg.CoreAudio2ASIO" 2>/dev/null || true

# Kill application with bundle ID com.steinberg.dorico6 if running
echo "Stopping application with bundle ID com.steinberg.dorico6 if running..."
killall -9 "com.steinberg.dorico6" 2>/dev/null || true

# Kill application with bundle ID com.steinberg.dorico.* if running
echo "Stopping application with bundle ID com.steinberg.dorico.* if running..."
killall -9 "com.steinberg.dorico.*" 2>/dev/null || true

# Kill application with bundle ID com.steinberg.mediaservice if running
echo "Stopping application with bundle ID com.steinberg.mediaservice if running..."
killall -9 "com.steinberg.mediaservice" 2>/dev/null || true

# Kill application with bundle ID com.steinberg.videoengine if running
echo "Stopping application with bundle ID com.steinberg.videoengine if running..."
killall -9 "com.steinberg.videoengine" 2>/dev/null || true

# Kill application with bundle ID com.steinberg.vst3.doricobeep if running
echo "Stopping application with bundle ID com.steinberg.vst3.doricobeep if running..."
killall -9 "com.steinberg.vst3.doricobeep" 2>/dev/null || true

# Kill application with bundle ID com.steinberg.vst3.pluginset.vstaudioengine if running
echo "Stopping application with bundle ID com.steinberg.vst3.pluginset.vstaudioengine if running..."
killall -9 "com.steinberg.vst3.pluginset.vstaudioengine" 2>/dev/null || true

# Kill application with bundle ID com.steinberg.vst3.vstaudioengine if running
echo "Stopping application with bundle ID com.steinberg.vst3.vstaudioengine if running..."
killall -9 "com.steinberg.vst3.vstaudioengine" 2>/dev/null || true

# Kill application with bundle ID com.steinberg.VSTPlugManager if running
echo "Stopping application with bundle ID com.steinberg.VSTPlugManager if running..."
killall -9 "com.steinberg.VSTPlugManager" 2>/dev/null || true

# Kill application with bundle ID net.steinberg.crashlog-uploader if running
echo "Stopping application with bundle ID net.steinberg.crashlog-uploader if running..."
killall -9 "net.steinberg.crashlog-uploader" 2>/dev/null || true

# Kill application with bundle ID net.steinberg.dorico_extractaudio if running
echo "Stopping application with bundle ID net.steinberg.dorico_extractaudio if running..."
killall -9 "net.steinberg.dorico_extractaudio" 2>/dev/null || true

# Remove /Library/Application Support/Steinberg/Dorico 6
echo "Removing /Library/Application Support/Steinberg/Dorico 6..."
if [ -d "/Library/Application Support/Steinberg/Dorico 6" ]; then
    rm -rf "/Library/Application Support/Steinberg/Dorico 6" 2>/dev/null || true
elif [ -f "/Library/Application Support/Steinberg/Dorico 6" ]; then
    rm -f "/Library/Application Support/Steinberg/Dorico 6" 2>/dev/null || true
fi

# Remove /Users/Shared/Dorico Example Projects
echo "Removing /Users/Shared/Dorico Example Projects..."
if [ -d "/Users/Shared/Dorico Example Projects" ]; then
    rm -rf "/Users/Shared/Dorico Example Projects" 2>/dev/null || true
elif [ -f "/Users/Shared/Dorico Example Projects" ]; then
    rm -f "/Users/Shared/Dorico Example Projects" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.steinberg.dorico*
echo "Removing $HOME/Library/Application Scripts/com.steinberg.dorico*..."
if [ -d "$HOME/Library/Application Scripts/com.steinberg.dorico*" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.steinberg.dorico*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.steinberg.dorico*" ]; then
    rm -f "$HOME/Library/Application Scripts/com.steinberg.dorico*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/CloudDocs/session/containers/iCloud.com.steinberg.iosdorico*
echo "Removing $HOME/Library/Application Support/CloudDocs/session/containers/iCloud.com.steinberg.iosdorico*..."
if [ -d "$HOME/Library/Application Support/CloudDocs/session/containers/iCloud.com.steinberg.iosdorico*" ]; then
    rm -rf "$HOME/Library/Application Support/CloudDocs/session/containers/iCloud.com.steinberg.iosdorico*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/CloudDocs/session/containers/iCloud.com.steinberg.iosdorico*" ]; then
    rm -f "$HOME/Library/Application Support/CloudDocs/session/containers/iCloud.com.steinberg.iosdorico*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.steinberg.dorico6.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.steinberg.dorico6.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.steinberg.dorico6.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.steinberg.dorico6.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.steinberg.dorico6.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.steinberg.dorico6.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Steinberg/Dorico 6
echo "Removing $HOME/Library/Application Support/Steinberg/Dorico 6..."
if [ -d "$HOME/Library/Application Support/Steinberg/Dorico 6" ]; then
    rm -rf "$HOME/Library/Application Support/Steinberg/Dorico 6" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Steinberg/Dorico 6" ]; then
    rm -f "$HOME/Library/Application Support/Steinberg/Dorico 6" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/Dorico 6
echo "Removing $HOME/Library/Caches/Dorico 6..."
if [ -d "$HOME/Library/Caches/Dorico 6" ]; then
    rm -rf "$HOME/Library/Caches/Dorico 6" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/Dorico 6" ]; then
    rm -f "$HOME/Library/Caches/Dorico 6" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/Steinberg/Dorico
echo "Removing $HOME/Library/Caches/Steinberg/Dorico..."
if [ -d "$HOME/Library/Caches/Steinberg/Dorico" ]; then
    rm -rf "$HOME/Library/Caches/Steinberg/Dorico" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/Steinberg/Dorico" ]; then
    rm -f "$HOME/Library/Caches/Steinberg/Dorico" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.steinberg.dorico*
echo "Removing $HOME/Library/Containers/com.steinberg.dorico*..."
if [ -d "$HOME/Library/Containers/com.steinberg.dorico*" ]; then
    rm -rf "$HOME/Library/Containers/com.steinberg.dorico*" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.steinberg.dorico*" ]; then
    rm -f "$HOME/Library/Containers/com.steinberg.dorico*" 2>/dev/null || true
fi

# Remove $HOME/Library/Mobile Documents/iCloud~com~steinberg~iosdorico
echo "Removing $HOME/Library/Mobile Documents/iCloud~com~steinberg~iosdorico..."
if [ -d "$HOME/Library/Mobile Documents/iCloud~com~steinberg~iosdorico" ]; then
    rm -rf "$HOME/Library/Mobile Documents/iCloud~com~steinberg~iosdorico" 2>/dev/null || true
elif [ -f "$HOME/Library/Mobile Documents/iCloud~com~steinberg~iosdorico" ]; then
    rm -f "$HOME/Library/Mobile Documents/iCloud~com~steinberg~iosdorico" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.steinberg-dorico6.dialogGeometry.plist
echo "Removing $HOME/Library/Preferences/com.steinberg-dorico6.dialogGeometry.plist..."
if [ -d "$HOME/Library/Preferences/com.steinberg-dorico6.dialogGeometry.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.steinberg-dorico6.dialogGeometry.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.steinberg-dorico6.dialogGeometry.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.steinberg-dorico6.dialogGeometry.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.steinberg.dorico6.plist
echo "Removing $HOME/Library/Preferences/com.steinberg.dorico6.plist..."
if [ -d "$HOME/Library/Preferences/com.steinberg.dorico6.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.steinberg.dorico6.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.steinberg.dorico6.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.steinberg.dorico6.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/Dorico 6 AudioEngine
echo "Removing $HOME/Library/Preferences/Dorico 6 AudioEngine..."
if [ -d "$HOME/Library/Preferences/Dorico 6 AudioEngine" ]; then
    rm -rf "$HOME/Library/Preferences/Dorico 6 AudioEngine" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/Dorico 6 AudioEngine" ]; then
    rm -f "$HOME/Library/Preferences/Dorico 6 AudioEngine" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.steinberg.dorico6.savedState
echo "Removing $HOME/Library/Saved Application State/com.steinberg.dorico6.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.steinberg.dorico6.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.steinberg.dorico6.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.steinberg.dorico6.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.steinberg.dorico6.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
