#!/bin/bash
# Uninstall script for BackupLoupe
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling BackupLoupe..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping BackupLoupe if running..."
pkill -f "BackupLoupe" 2>/dev/null || true

# Remove /Applications/BackupLoupe.app
echo "Removing /Applications/BackupLoupe.app..."
if [ -d "/Applications/BackupLoupe.app" ]; then
    rm -rf "/Applications/BackupLoupe.app" 2>/dev/null || true
elif [ -f "/Applications/BackupLoupe.app" ]; then
    rm -f "/Applications/BackupLoupe.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/BackupLoupe
echo "Removing $HOME/Library/Application Support/BackupLoupe..."
if [ -d "$HOME/Library/Application Support/BackupLoupe" ]; then
    rm -rf "$HOME/Library/Application Support/BackupLoupe" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/BackupLoupe" ]; then
    rm -f "$HOME/Library/Application Support/BackupLoupe" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.helpd/Generated/BackupLoupe*
echo "Removing $HOME/Library/Caches/com.apple.helpd/Generated/BackupLoupe*..."
if [ -d "$HOME/Library/Caches/com.apple.helpd/Generated/BackupLoupe*" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.helpd/Generated/BackupLoupe*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.helpd/Generated/BackupLoupe*" ]; then
    rm -f "$HOME/Library/Caches/com.apple.helpd/Generated/BackupLoupe*" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.soma-zone.BackupLoupe.plist
echo "Removing $HOME/Library/Preferences/com.soma-zone.BackupLoupe.plist..."
if [ -d "$HOME/Library/Preferences/com.soma-zone.BackupLoupe.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.soma-zone.BackupLoupe.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.soma-zone.BackupLoupe.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.soma-zone.BackupLoupe.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
