#!/bin/bash
# Uninstall script for Camunda Modeler
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Camunda Modeler..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Camunda Modeler if running..."
pkill -f "Camunda Modeler" 2>/dev/null || true

# Remove /Applications/Camunda Modeler.app
echo "Removing /Applications/Camunda Modeler.app..."
if [ -d "/Applications/Camunda Modeler.app" ]; then
    rm -rf "/Applications/Camunda Modeler.app" 2>/dev/null || true
elif [ -f "/Applications/Camunda Modeler.app" ]; then
    rm -f "/Applications/Camunda Modeler.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/camunda-modeler
echo "Removing $HOME/Library/Application Support/camunda-modeler..."
if [ -d "$HOME/Library/Application Support/camunda-modeler" ]; then
    rm -rf "$HOME/Library/Application Support/camunda-modeler" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/camunda-modeler" ]; then
    rm -f "$HOME/Library/Application Support/camunda-modeler" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Camunda Modeler
echo "Removing $HOME/Library/Logs/Camunda Modeler..."
if [ -d "$HOME/Library/Logs/Camunda Modeler" ]; then
    rm -rf "$HOME/Library/Logs/Camunda Modeler" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Camunda Modeler" ]; then
    rm -f "$HOME/Library/Logs/Camunda Modeler" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.camunda.CamundaModeler.plist
echo "Removing $HOME/Library/Preferences/com.camunda.CamundaModeler.plist..."
if [ -d "$HOME/Library/Preferences/com.camunda.CamundaModeler.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.camunda.CamundaModeler.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.camunda.CamundaModeler.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.camunda.CamundaModeler.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.camunda.CamundaModeler.savedState
echo "Removing $HOME/Library/Saved Application State/com.camunda.CamundaModeler.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.camunda.CamundaModeler.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.camunda.CamundaModeler.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.camunda.CamundaModeler.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.camunda.CamundaModeler.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
