#!/bin/bash
# Uninstall script for Ferdium
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Ferdium..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Ferdium if running..."
pkill -f "Ferdium" 2>/dev/null || true

# Kill application with bundle ID com.ferdium.ferdium-app if running
echo "Stopping application with bundle ID com.ferdium.ferdium-app if running..."
killall -9 "com.ferdium.ferdium-app" 2>/dev/null || true

# Remove /Applications/Ferdium.app
echo "Removing /Applications/Ferdium.app..."
if [ -d "/Applications/Ferdium.app" ]; then
    rm -rf "/Applications/Ferdium.app" 2>/dev/null || true
elif [ -f "/Applications/Ferdium.app" ]; then
    rm -f "/Applications/Ferdium.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Caches/ferdium-updater
echo "Removing $HOME/Library/Application Support/Caches/ferdium-updater..."
if [ -d "$HOME/Library/Application Support/Caches/ferdium-updater" ]; then
    rm -rf "$HOME/Library/Application Support/Caches/ferdium-updater" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Caches/ferdium-updater" ]; then
    rm -f "$HOME/Library/Application Support/Caches/ferdium-updater" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Ferdium
echo "Removing $HOME/Library/Application Support/Ferdium..."
if [ -d "$HOME/Library/Application Support/Ferdium" ]; then
    rm -rf "$HOME/Library/Application Support/Ferdium" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Ferdium" ]; then
    rm -f "$HOME/Library/Application Support/Ferdium" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.ferdium.ferdium-app
echo "Removing $HOME/Library/Caches/com.ferdium.ferdium-app..."
if [ -d "$HOME/Library/Caches/com.ferdium.ferdium-app" ]; then
    rm -rf "$HOME/Library/Caches/com.ferdium.ferdium-app" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.ferdium.ferdium-app" ]; then
    rm -f "$HOME/Library/Caches/com.ferdium.ferdium-app" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.ferdium.ferdium-app.ShipIt
echo "Removing $HOME/Library/Caches/com.ferdium.ferdium-app.ShipIt..."
if [ -d "$HOME/Library/Caches/com.ferdium.ferdium-app.ShipIt" ]; then
    rm -rf "$HOME/Library/Caches/com.ferdium.ferdium-app.ShipIt" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.ferdium.ferdium-app.ShipIt" ]; then
    rm -f "$HOME/Library/Caches/com.ferdium.ferdium-app.ShipIt" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Ferdium
echo "Removing $HOME/Library/Logs/Ferdium..."
if [ -d "$HOME/Library/Logs/Ferdium" ]; then
    rm -rf "$HOME/Library/Logs/Ferdium" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Ferdium" ]; then
    rm -f "$HOME/Library/Logs/Ferdium" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/ByHost/com.ferdium.ferdium-app.ShipIt.*.plist
echo "Removing $HOME/Library/Preferences/ByHost/com.ferdium.ferdium-app.ShipIt.*.plist..."
if [ -d "$HOME/Library/Preferences/ByHost/com.ferdium.ferdium-app.ShipIt.*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/ByHost/com.ferdium.ferdium-app.ShipIt.*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/ByHost/com.ferdium.ferdium-app.ShipIt.*.plist" ]; then
    rm -f "$HOME/Library/Preferences/ByHost/com.ferdium.ferdium-app.ShipIt.*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.electron.ferdium.helper.plist
echo "Removing $HOME/Library/Preferences/com.electron.ferdium.helper.plist..."
if [ -d "$HOME/Library/Preferences/com.electron.ferdium.helper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.electron.ferdium.helper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.electron.ferdium.helper.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.electron.ferdium.helper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.electron.ferdium.plist
echo "Removing $HOME/Library/Preferences/com.electron.ferdium.plist..."
if [ -d "$HOME/Library/Preferences/com.electron.ferdium.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.electron.ferdium.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.electron.ferdium.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.electron.ferdium.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.ferdium.ferdium-app.plist
echo "Removing $HOME/Library/Preferences/com.ferdium.ferdium-app.plist..."
if [ -d "$HOME/Library/Preferences/com.ferdium.ferdium-app.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.ferdium.ferdium-app.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.ferdium.ferdium-app.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.ferdium.ferdium-app.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.ferdium.ferdium-app.savedState
echo "Removing $HOME/Library/Saved Application State/com.ferdium.ferdium-app.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.ferdium.ferdium-app.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.ferdium.ferdium-app.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.ferdium.ferdium-app.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.ferdium.ferdium-app.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
