#!/bin/bash
# Uninstall script for Mactracker
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Mactracker..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Mactracker if running..."
pkill -f "Mactracker" 2>/dev/null || true

# Remove /Applications/Mactracker.app
echo "Removing /Applications/Mactracker.app..."
if [ -d "/Applications/Mactracker.app" ]; then
    rm -rf "/Applications/Mactracker.app" 2>/dev/null || true
elif [ -f "/Applications/Mactracker.app" ]; then
    rm -f "/Applications/Mactracker.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.mactrackerapp.Mactracker
echo "Removing $HOME/Library/Application Support/com.mactrackerapp.Mactracker..."
if [ -d "$HOME/Library/Application Support/com.mactrackerapp.Mactracker" ]; then
    rm -rf "$HOME/Library/Application Support/com.mactrackerapp.Mactracker" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.mactrackerapp.Mactracker" ]; then
    rm -f "$HOME/Library/Application Support/com.mactrackerapp.Mactracker" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.mactrackerapp.Mactracker
echo "Removing $HOME/Library/Caches/com.mactrackerapp.Mactracker..."
if [ -d "$HOME/Library/Caches/com.mactrackerapp.Mactracker" ]; then
    rm -rf "$HOME/Library/Caches/com.mactrackerapp.Mactracker" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.mactrackerapp.Mactracker" ]; then
    rm -f "$HOME/Library/Caches/com.mactrackerapp.Mactracker" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.mactrackerapp.Mactracker.plist
echo "Removing $HOME/Library/Preferences/com.mactrackerapp.Mactracker.plist..."
if [ -d "$HOME/Library/Preferences/com.mactrackerapp.Mactracker.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.mactrackerapp.Mactracker.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.mactrackerapp.Mactracker.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.mactrackerapp.Mactracker.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.mactrackerapp.Mactracker.savedState
echo "Removing $HOME/Library/Saved Application State/com.mactrackerapp.Mactracker.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.mactrackerapp.Mactracker.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.mactrackerapp.Mactracker.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.mactrackerapp.Mactracker.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.mactrackerapp.Mactracker.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
