#!/bin/bash
# Uninstall script for OK JSON
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling OK JSON..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping OK JSON if running..."
pkill -f "OK JSON" 2>/dev/null || true

# Remove /Applications/OK JSON.app
echo "Removing /Applications/OK JSON.app..."
if [ -d "/Applications/OK JSON.app" ]; then
    rm -rf "/Applications/OK JSON.app" 2>/dev/null || true
elif [ -f "/Applications/OK JSON.app" ]; then
    rm -f "/Applications/OK JSON.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/net.shinystone.OKJSON
echo "Removing $HOME/Library/Containers/net.shinystone.OKJSON..."
if [ -d "$HOME/Library/Containers/net.shinystone.OKJSON" ]; then
    rm -rf "$HOME/Library/Containers/net.shinystone.OKJSON" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/net.shinystone.OKJSON" ]; then
    rm -f "$HOME/Library/Containers/net.shinystone.OKJSON" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/group.net.shinystone.OKJSON
echo "Removing $HOME/Library/Group Containers/group.net.shinystone.OKJSON..."
if [ -d "$HOME/Library/Group Containers/group.net.shinystone.OKJSON" ]; then
    rm -rf "$HOME/Library/Group Containers/group.net.shinystone.OKJSON" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/group.net.shinystone.OKJSON" ]; then
    rm -f "$HOME/Library/Group Containers/group.net.shinystone.OKJSON" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
