#!/bin/bash
# Uninstall script for AlDente
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling AlDente..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping AlDente if running..."
pkill -f "AlDente" 2>/dev/null || true

# Unload service com.apphousekitchen.aldente-pro.helper
echo "Unloading service com.apphousekitchen.aldente-pro.helper..."
launchctl unload -w /Library/LaunchAgents/com.apphousekitchen.aldente-pro.helper.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.apphousekitchen.aldente-pro.helper.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.apphousekitchen.aldente-pro.helper.plist 2>/dev/null || true

# Kill application with bundle ID com.apphousekitchen.aldente-pro if running
echo "Stopping application with bundle ID com.apphousekitchen.aldente-pro if running..."
killall -9 "com.apphousekitchen.aldente-pro" 2>/dev/null || true

# Remove /Applications/AlDente.app
echo "Removing /Applications/AlDente.app..."
if [ -d "/Applications/AlDente.app" ]; then
    rm -rf "/Applications/AlDente.app" 2>/dev/null || true
elif [ -f "/Applications/AlDente.app" ]; then
    rm -f "/Applications/AlDente.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/AlDente
echo "Removing $HOME/Library/Application Support/AlDente..."
if [ -d "$HOME/Library/Application Support/AlDente" ]; then
    rm -rf "$HOME/Library/Application Support/AlDente" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/AlDente" ]; then
    rm -f "$HOME/Library/Application Support/AlDente" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apphousekitchen.aldente-pro
echo "Removing $HOME/Library/Caches/com.apphousekitchen.aldente-pro..."
if [ -d "$HOME/Library/Caches/com.apphousekitchen.aldente-pro" ]; then
    rm -rf "$HOME/Library/Caches/com.apphousekitchen.aldente-pro" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apphousekitchen.aldente-pro" ]; then
    rm -f "$HOME/Library/Caches/com.apphousekitchen.aldente-pro" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.apphousekitchen.aldente-pro
echo "Removing $HOME/Library/HTTPStorages/com.apphousekitchen.aldente-pro..."
if [ -d "$HOME/Library/HTTPStorages/com.apphousekitchen.aldente-pro" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.apphousekitchen.aldente-pro" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.apphousekitchen.aldente-pro" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.apphousekitchen.aldente-pro" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.apphousekitchen.aldente-pro.binarycookies
echo "Removing $HOME/Library/HTTPStorages/com.apphousekitchen.aldente-pro.binarycookies..."
if [ -d "$HOME/Library/HTTPStorages/com.apphousekitchen.aldente-pro.binarycookies" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.apphousekitchen.aldente-pro.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.apphousekitchen.aldente-pro.binarycookies" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.apphousekitchen.aldente-pro.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.apphousekitchen.aldente-pro.plist
echo "Removing $HOME/Library/Preferences/com.apphousekitchen.aldente-pro.plist..."
if [ -d "$HOME/Library/Preferences/com.apphousekitchen.aldente-pro.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.apphousekitchen.aldente-pro.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.apphousekitchen.aldente-pro.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.apphousekitchen.aldente-pro.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.apphousekitchen.aldente-pro_backup.plist
echo "Removing $HOME/Library/Preferences/com.apphousekitchen.aldente-pro_backup.plist..."
if [ -d "$HOME/Library/Preferences/com.apphousekitchen.aldente-pro_backup.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.apphousekitchen.aldente-pro_backup.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.apphousekitchen.aldente-pro_backup.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.apphousekitchen.aldente-pro_backup.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.apphousekitchen.aldente-pro_stats.sqlite3
echo "Removing $HOME/Library/Preferences/com.apphousekitchen.aldente-pro_stats.sqlite3..."
if [ -d "$HOME/Library/Preferences/com.apphousekitchen.aldente-pro_stats.sqlite3" ]; then
    rm -rf "$HOME/Library/Preferences/com.apphousekitchen.aldente-pro_stats.sqlite3" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.apphousekitchen.aldente-pro_stats.sqlite3" ]; then
    rm -f "$HOME/Library/Preferences/com.apphousekitchen.aldente-pro_stats.sqlite3" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
