#!/bin/bash
# Uninstall script for Deckset
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Deckset..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Deckset if running..."
pkill -f "Deckset" 2>/dev/null || true

# Remove /Applications/Deckset.app
echo "Removing /Applications/Deckset.app..."
if [ -d "/Applications/Deckset.app" ]; then
    rm -rf "/Applications/Deckset.app" 2>/dev/null || true
elif [ -f "/Applications/Deckset.app" ]; then
    rm -f "/Applications/Deckset.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.unsignedinteger.deckset-paddle.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.unsignedinteger.deckset-paddle.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.unsignedinteger.deckset-paddle.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.unsignedinteger.deckset-paddle.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.unsignedinteger.deckset-paddle.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.unsignedinteger.deckset-paddle.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.unsignedinteger.Deckset-Paddle
echo "Removing $HOME/Library/Application Support/com.unsignedinteger.Deckset-Paddle..."
if [ -d "$HOME/Library/Application Support/com.unsignedinteger.Deckset-Paddle" ]; then
    rm -rf "$HOME/Library/Application Support/com.unsignedinteger.Deckset-Paddle" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.unsignedinteger.Deckset-Paddle" ]; then
    rm -f "$HOME/Library/Application Support/com.unsignedinteger.Deckset-Paddle" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Deckset
echo "Removing $HOME/Library/Application Support/Deckset..."
if [ -d "$HOME/Library/Application Support/Deckset" ]; then
    rm -rf "$HOME/Library/Application Support/Deckset" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Deckset" ]; then
    rm -f "$HOME/Library/Application Support/Deckset" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.helpd/Generated/com.unsignedinteger.Deckset.Helpbook*
echo "Removing $HOME/Library/Caches/com.apple.helpd/Generated/com.unsignedinteger.Deckset.Helpbook*..."
if [ -d "$HOME/Library/Caches/com.apple.helpd/Generated/com.unsignedinteger.Deckset.Helpbook*" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.helpd/Generated/com.unsignedinteger.Deckset.Helpbook*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.helpd/Generated/com.unsignedinteger.Deckset.Helpbook*" ]; then
    rm -f "$HOME/Library/Caches/com.apple.helpd/Generated/com.unsignedinteger.Deckset.Helpbook*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.unsignedinteger.Deckset-Paddle
echo "Removing $HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.unsignedinteger.Deckset-Paddle..."
if [ -d "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.unsignedinteger.Deckset-Paddle" ]; then
    rm -rf "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.unsignedinteger.Deckset-Paddle" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.unsignedinteger.Deckset-Paddle" ]; then
    rm -f "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.unsignedinteger.Deckset-Paddle" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.unsignedinteger.Deckset-Paddle
echo "Removing $HOME/Library/Caches/com.unsignedinteger.Deckset-Paddle..."
if [ -d "$HOME/Library/Caches/com.unsignedinteger.Deckset-Paddle" ]; then
    rm -rf "$HOME/Library/Caches/com.unsignedinteger.Deckset-Paddle" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.unsignedinteger.Deckset-Paddle" ]; then
    rm -f "$HOME/Library/Caches/com.unsignedinteger.Deckset-Paddle" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.unsignedinteger.Deckset-Paddle*
echo "Removing $HOME/Library/HTTPStorages/com.unsignedinteger.Deckset-Paddle*..."
if [ -d "$HOME/Library/HTTPStorages/com.unsignedinteger.Deckset-Paddle*" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.unsignedinteger.Deckset-Paddle*" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.unsignedinteger.Deckset-Paddle*" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.unsignedinteger.Deckset-Paddle*" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.unsignedinteger.Deckset-Paddle.plist
echo "Removing $HOME/Library/Preferences/com.unsignedinteger.Deckset-Paddle.plist..."
if [ -d "$HOME/Library/Preferences/com.unsignedinteger.Deckset-Paddle.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.unsignedinteger.Deckset-Paddle.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.unsignedinteger.Deckset-Paddle.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.unsignedinteger.Deckset-Paddle.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.unsignedinteger.Deckset-Paddle.savedState
echo "Removing $HOME/Library/Saved Application State/com.unsignedinteger.Deckset-Paddle.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.unsignedinteger.Deckset-Paddle.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.unsignedinteger.Deckset-Paddle.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.unsignedinteger.Deckset-Paddle.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.unsignedinteger.Deckset-Paddle.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
