#!/bin/bash
# Uninstall script for Blender
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Blender..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Blender if running..."
pkill -f "Blender" 2>/dev/null || true

# Remove /Applications/Blender.app
echo "Removing /Applications/Blender.app..."
if [ -d "/Applications/Blender.app" ]; then
    rm -rf "/Applications/Blender.app" 2>/dev/null || true
elif [ -f "/Applications/Blender.app" ]; then
    rm -f "/Applications/Blender.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Blender
echo "Removing $HOME/Library/Application Support/Blender..."
if [ -d "$HOME/Library/Application Support/Blender" ]; then
    rm -rf "$HOME/Library/Application Support/Blender" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Blender" ]; then
    rm -f "$HOME/Library/Application Support/Blender" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/org.blenderfoundation.blender.savedState
echo "Removing $HOME/Library/Saved Application State/org.blenderfoundation.blender.savedState..."
if [ -d "$HOME/Library/Saved Application State/org.blenderfoundation.blender.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/org.blenderfoundation.blender.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/org.blenderfoundation.blender.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/org.blenderfoundation.blender.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
