#!/bin/bash
# Uninstall script for Hopper Disassembler
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Hopper Disassembler..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Hopper Disassembler if running..."
pkill -f "Hopper Disassembler" 2>/dev/null || true

# Remove /Applications/Hopper Disassembler.app
echo "Removing /Applications/Hopper Disassembler.app..."
if [ -d "/Applications/Hopper Disassembler.app" ]; then
    rm -rf "/Applications/Hopper Disassembler.app" 2>/dev/null || true
elif [ -f "/Applications/Hopper Disassembler.app" ]; then
    rm -f "/Applications/Hopper Disassembler.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.cryptic-apps.hopper-web-4.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.cryptic-apps.hopper-web-4.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.cryptic-apps.hopper-web-4.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.cryptic-apps.hopper-web-4.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.cryptic-apps.hopper-web-4.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.cryptic-apps.hopper-web-4.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Hopper Disassembler v4
echo "Removing $HOME/Library/Application Support/Hopper Disassembler v4..."
if [ -d "$HOME/Library/Application Support/Hopper Disassembler v4" ]; then
    rm -rf "$HOME/Library/Application Support/Hopper Disassembler v4" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Hopper Disassembler v4" ]; then
    rm -f "$HOME/Library/Application Support/Hopper Disassembler v4" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Hopper
echo "Removing $HOME/Library/Application Support/Hopper..."
if [ -d "$HOME/Library/Application Support/Hopper" ]; then
    rm -rf "$HOME/Library/Application Support/Hopper" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Hopper" ]; then
    rm -f "$HOME/Library/Application Support/Hopper" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.helpd/Generated/com.cryptic-apps.hopper-web-4.help*
echo "Removing $HOME/Library/Caches/com.apple.helpd/Generated/com.cryptic-apps.hopper-web-4.help*..."
if [ -d "$HOME/Library/Caches/com.apple.helpd/Generated/com.cryptic-apps.hopper-web-4.help*" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.helpd/Generated/com.cryptic-apps.hopper-web-4.help*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.helpd/Generated/com.cryptic-apps.hopper-web-4.help*" ]; then
    rm -f "$HOME/Library/Caches/com.apple.helpd/Generated/com.cryptic-apps.hopper-web-4.help*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.cryptic-apps.hopper-web-4
echo "Removing $HOME/Library/Caches/com.cryptic-apps.hopper-web-4..."
if [ -d "$HOME/Library/Caches/com.cryptic-apps.hopper-web-4" ]; then
    rm -rf "$HOME/Library/Caches/com.cryptic-apps.hopper-web-4" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.cryptic-apps.hopper-web-4" ]; then
    rm -f "$HOME/Library/Caches/com.cryptic-apps.hopper-web-4" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.cryptic-apps.hopper-web-4
echo "Removing $HOME/Library/HTTPStorages/com.cryptic-apps.hopper-web-4..."
if [ -d "$HOME/Library/HTTPStorages/com.cryptic-apps.hopper-web-4" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.cryptic-apps.hopper-web-4" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.cryptic-apps.hopper-web-4" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.cryptic-apps.hopper-web-4" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.cryptic-apps.hopper-web-4.plist
echo "Removing $HOME/Library/Preferences/com.cryptic-apps.hopper-web-4.plist..."
if [ -d "$HOME/Library/Preferences/com.cryptic-apps.hopper-web-4.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.cryptic-apps.hopper-web-4.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.cryptic-apps.hopper-web-4.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.cryptic-apps.hopper-web-4.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.cryptic-apps.hopper-web-4.savedState
echo "Removing $HOME/Library/Saved Application State/com.cryptic-apps.hopper-web-4.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.cryptic-apps.hopper-web-4.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.cryptic-apps.hopper-web-4.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.cryptic-apps.hopper-web-4.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.cryptic-apps.hopper-web-4.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
