#!/bin/bash
# Uninstall script for Mellel
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Mellel..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Mellel if running..."
pkill -f "Mellel" 2>/dev/null || true

# Remove /Applications/Mellel 6.app
echo "Removing /Applications/Mellel 6.app..."
if [ -d "/Applications/Mellel 6.app" ]; then
    rm -rf "/Applications/Mellel 6.app" 2>/dev/null || true
elif [ -f "/Applications/Mellel 6.app" ]; then
    rm -f "/Applications/Mellel 6.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.redlex.mellel
echo "Removing $HOME/Library/Application Scripts/com.redlex.mellel..."
if [ -d "$HOME/Library/Application Scripts/com.redlex.mellel" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.redlex.mellel" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.redlex.mellel" ]; then
    rm -f "$HOME/Library/Application Scripts/com.redlex.mellel" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.redlex.mellel6
echo "Removing $HOME/Library/Application Support/com.redlex.mellel6..."
if [ -d "$HOME/Library/Application Support/com.redlex.mellel6" ]; then
    rm -rf "$HOME/Library/Application Support/com.redlex.mellel6" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.redlex.mellel6" ]; then
    rm -f "$HOME/Library/Application Support/com.redlex.mellel6" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Mellel 6
echo "Removing $HOME/Library/Application Support/Mellel 6..."
if [ -d "$HOME/Library/Application Support/Mellel 6" ]; then
    rm -rf "$HOME/Library/Application Support/Mellel 6" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Mellel 6" ]; then
    rm -f "$HOME/Library/Application Support/Mellel 6" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.redlex.mellel6
echo "Removing $HOME/Library/Caches/com.redlex.mellel6..."
if [ -d "$HOME/Library/Caches/com.redlex.mellel6" ]; then
    rm -rf "$HOME/Library/Caches/com.redlex.mellel6" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.redlex.mellel6" ]; then
    rm -f "$HOME/Library/Caches/com.redlex.mellel6" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.redlex.mellel6
echo "Removing $HOME/Library/HTTPStorages/com.redlex.mellel6..."
if [ -d "$HOME/Library/HTTPStorages/com.redlex.mellel6" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.redlex.mellel6" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.redlex.mellel6" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.redlex.mellel6" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.redlex.mellel6.binarycookies
echo "Removing $HOME/Library/HTTPStorages/com.redlex.mellel6.binarycookies..."
if [ -d "$HOME/Library/HTTPStorages/com.redlex.mellel6.binarycookies" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.redlex.mellel6.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.redlex.mellel6.binarycookies" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.redlex.mellel6.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.redlex.mellel6.plist
echo "Removing $HOME/Library/Preferences/com.redlex.mellel6.plist..."
if [ -d "$HOME/Library/Preferences/com.redlex.mellel6.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.redlex.mellel6.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.redlex.mellel6.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.redlex.mellel6.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.redlex.mellel6.savedState
echo "Removing $HOME/Library/Saved Application State/com.redlex.mellel6.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.redlex.mellel6.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.redlex.mellel6.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.redlex.mellel6.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.redlex.mellel6.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.redlex.MellelUpdater.savedState
echo "Removing $HOME/Library/Saved Application State/com.redlex.MellelUpdater.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.redlex.MellelUpdater.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.redlex.MellelUpdater.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.redlex.MellelUpdater.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.redlex.MellelUpdater.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
