#!/bin/bash
# Uninstall script for Roon
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Roon..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Roon if running..."
pkill -f "Roon" 2>/dev/null || true

# Kill application with bundle ID RoonServer if running
echo "Stopping application with bundle ID RoonServer if running..."
killall -9 "RoonServer" 2>/dev/null || true

# Remove /Applications/Roon.app
echo "Removing /Applications/Roon.app..."
if [ -d "/Applications/Roon.app" ]; then
    rm -rf "/Applications/Roon.app" 2>/dev/null || true
elif [ -f "/Applications/Roon.app" ]; then
    rm -f "/Applications/Roon.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Roon
echo "Removing $HOME/Library/Roon..."
if [ -d "$HOME/Library/Roon" ]; then
    rm -rf "$HOME/Library/Roon" 2>/dev/null || true
elif [ -f "$HOME/Library/Roon" ]; then
    rm -f "$HOME/Library/Roon" 2>/dev/null || true
fi

# Remove $HOME/Library/RoonGoer
echo "Removing $HOME/Library/RoonGoer..."
if [ -d "$HOME/Library/RoonGoer" ]; then
    rm -rf "$HOME/Library/RoonGoer" 2>/dev/null || true
elif [ -f "$HOME/Library/RoonGoer" ]; then
    rm -f "$HOME/Library/RoonGoer" 2>/dev/null || true
fi

# Remove $HOME/Library/RoonServer
echo "Removing $HOME/Library/RoonServer..."
if [ -d "$HOME/Library/RoonServer" ]; then
    rm -rf "$HOME/Library/RoonServer" 2>/dev/null || true
elif [ -f "$HOME/Library/RoonServer" ]; then
    rm -f "$HOME/Library/RoonServer" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.roon.Roon.savedState
echo "Removing $HOME/Library/Saved Application State/com.roon.Roon.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.roon.Roon.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.roon.Roon.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.roon.Roon.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.roon.Roon.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
