#!/bin/bash
# Uninstall script for Keka
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Keka..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Keka if running..."
pkill -f "Keka" 2>/dev/null || true

# Remove /Applications/Keka.app
echo "Removing /Applications/Keka.app..."
if [ -d "/Applications/Keka.app" ]; then
    rm -rf "/Applications/Keka.app" 2>/dev/null || true
elif [ -f "/Applications/Keka.app" ]; then
    rm -f "/Applications/Keka.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/*.group.com.aone.keka
echo "Removing $HOME/Library/Application Scripts/*.group.com.aone.keka..."
if [ -d "$HOME/Library/Application Scripts/*.group.com.aone.keka" ]; then
    rm -rf "$HOME/Library/Application Scripts/*.group.com.aone.keka" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/*.group.com.aone.keka" ]; then
    rm -f "$HOME/Library/Application Scripts/*.group.com.aone.keka" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.aone.keka
echo "Removing $HOME/Library/Application Scripts/com.aone.keka..."
if [ -d "$HOME/Library/Application Scripts/com.aone.keka" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.aone.keka" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.aone.keka" ]; then
    rm -f "$HOME/Library/Application Scripts/com.aone.keka" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.aone.keka.KekaFinderIntegration
echo "Removing $HOME/Library/Application Scripts/com.aone.keka.KekaFinderIntegration..."
if [ -d "$HOME/Library/Application Scripts/com.aone.keka.KekaFinderIntegration" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.aone.keka.KekaFinderIntegration" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.aone.keka.KekaFinderIntegration" ]; then
    rm -f "$HOME/Library/Application Scripts/com.aone.keka.KekaFinderIntegration" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.aone.keka.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.aone.keka.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.aone.keka.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.aone.keka.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.aone.keka.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.aone.keka.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Keka
echo "Removing $HOME/Library/Application Support/Keka..."
if [ -d "$HOME/Library/Application Support/Keka" ]; then
    rm -rf "$HOME/Library/Application Support/Keka" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Keka" ]; then
    rm -f "$HOME/Library/Application Support/Keka" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.aone.keka
echo "Removing $HOME/Library/Caches/com.aone.keka..."
if [ -d "$HOME/Library/Caches/com.aone.keka" ]; then
    rm -rf "$HOME/Library/Caches/com.aone.keka" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.aone.keka" ]; then
    rm -f "$HOME/Library/Caches/com.aone.keka" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.aone.keka
echo "Removing $HOME/Library/Containers/com.aone.keka..."
if [ -d "$HOME/Library/Containers/com.aone.keka" ]; then
    rm -rf "$HOME/Library/Containers/com.aone.keka" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.aone.keka" ]; then
    rm -f "$HOME/Library/Containers/com.aone.keka" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.aone.keka.KekaFinderIntegration
echo "Removing $HOME/Library/Containers/com.aone.keka.KekaFinderIntegration..."
if [ -d "$HOME/Library/Containers/com.aone.keka.KekaFinderIntegration" ]; then
    rm -rf "$HOME/Library/Containers/com.aone.keka.KekaFinderIntegration" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.aone.keka.KekaFinderIntegration" ]; then
    rm -f "$HOME/Library/Containers/com.aone.keka.KekaFinderIntegration" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/*.group.com.aone.keka
echo "Removing $HOME/Library/Group Containers/*.group.com.aone.keka..."
if [ -d "$HOME/Library/Group Containers/*.group.com.aone.keka" ]; then
    rm -rf "$HOME/Library/Group Containers/*.group.com.aone.keka" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/*.group.com.aone.keka" ]; then
    rm -f "$HOME/Library/Group Containers/*.group.com.aone.keka" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.aone.keka.plist
echo "Removing $HOME/Library/Preferences/com.aone.keka.plist..."
if [ -d "$HOME/Library/Preferences/com.aone.keka.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.aone.keka.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.aone.keka.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.aone.keka.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.aone.keka.savedState
echo "Removing $HOME/Library/Saved Application State/com.aone.keka.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.aone.keka.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.aone.keka.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.aone.keka.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.aone.keka.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
