#!/bin/bash
# Uninstall script for Mullvad Browser
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Mullvad Browser..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Mullvad Browser if running..."
pkill -f "Mullvad Browser" 2>/dev/null || true

# Kill application with bundle ID net.mullvad.mullvadbrowser if running
echo "Stopping application with bundle ID net.mullvad.mullvadbrowser if running..."
killall -9 "net.mullvad.mullvadbrowser" 2>/dev/null || true

# Remove /Applications/Mullvad Browser.app
echo "Removing /Applications/Mullvad Browser.app..."
if [ -d "/Applications/Mullvad Browser.app" ]; then
    rm -rf "/Applications/Mullvad Browser.app" 2>/dev/null || true
elif [ -f "/Applications/Mullvad Browser.app" ]; then
    rm -f "/Applications/Mullvad Browser.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/MullvadBrowser
echo "Removing $HOME/Library/Application Support/MullvadBrowser..."
if [ -d "$HOME/Library/Application Support/MullvadBrowser" ]; then
    rm -rf "$HOME/Library/Application Support/MullvadBrowser" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/MullvadBrowser" ]; then
    rm -f "$HOME/Library/Application Support/MullvadBrowser" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/MullvadBrowser
echo "Removing $HOME/Library/Caches/MullvadBrowser..."
if [ -d "$HOME/Library/Caches/MullvadBrowser" ]; then
    rm -rf "$HOME/Library/Caches/MullvadBrowser" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/MullvadBrowser" ]; then
    rm -f "$HOME/Library/Caches/MullvadBrowser" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/net.mullvad.mullvadbrowser.plist
echo "Removing $HOME/Library/Preferences/net.mullvad.mullvadbrowser.plist..."
if [ -d "$HOME/Library/Preferences/net.mullvad.mullvadbrowser.plist" ]; then
    rm -rf "$HOME/Library/Preferences/net.mullvad.mullvadbrowser.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/net.mullvad.mullvadbrowser.plist" ]; then
    rm -f "$HOME/Library/Preferences/net.mullvad.mullvadbrowser.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/net.mullvad.mullvadbrowser.savedState
echo "Removing $HOME/Library/Saved Application State/net.mullvad.mullvadbrowser.savedState..."
if [ -d "$HOME/Library/Saved Application State/net.mullvad.mullvadbrowser.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/net.mullvad.mullvadbrowser.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/net.mullvad.mullvadbrowser.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/net.mullvad.mullvadbrowser.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
