#!/bin/bash
# Uninstall script for Sound Control
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Sound Control..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Sound Control if running..."
pkill -f "Sound Control" 2>/dev/null || true

# Unload service com.static.soundsiphon.inputagent
echo "Unloading service com.static.soundsiphon.inputagent..."
launchctl unload -w /Library/LaunchAgents/com.static.soundsiphon.inputagent.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.static.soundsiphon.inputagent.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.static.soundsiphon.inputagent.plist 2>/dev/null || true

# Unload service com.staticz.audio.soundsiphon.playeragent
echo "Unloading service com.staticz.audio.soundsiphon.playeragent..."
launchctl unload -w /Library/LaunchAgents/com.staticz.audio.soundsiphon.playeragent.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.staticz.audio.soundsiphon.playeragent.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.staticz.audio.soundsiphon.playeragent.plist 2>/dev/null || true

# Unload service com.staticz.soundsiphon.bridgedaemon
echo "Unloading service com.staticz.soundsiphon.bridgedaemon..."
launchctl unload -w /Library/LaunchAgents/com.staticz.soundsiphon.bridgedaemon.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.staticz.soundsiphon.bridgedaemon.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.staticz.soundsiphon.bridgedaemon.plist 2>/dev/null || true

# Kill application with bundle ID com.staticz.SoundControl if running
echo "Stopping application with bundle ID com.staticz.SoundControl if running..."
killall -9 "com.staticz.SoundControl" 2>/dev/null || true

# Remove /Applications/Sound Control.app
echo "Removing /Applications/Sound Control.app..."
if [ -d "/Applications/Sound Control.app" ]; then
    rm -rf "/Applications/Sound Control.app" 2>/dev/null || true
elif [ -f "/Applications/Sound Control.app" ]; then
    rm -f "/Applications/Sound Control.app" 2>/dev/null || true
fi

# Remove /Library/Audio/Plug-Ins/HAL/_SoundSiphon.driver
echo "Removing /Library/Audio/Plug-Ins/HAL/_SoundSiphon.driver..."
if [ -d "/Library/Audio/Plug-Ins/HAL/_SoundSiphon.driver" ]; then
    rm -rf "/Library/Audio/Plug-Ins/HAL/_SoundSiphon.driver" 2>/dev/null || true
elif [ -f "/Library/Audio/Plug-Ins/HAL/_SoundSiphon.driver" ]; then
    rm -f "/Library/Audio/Plug-Ins/HAL/_SoundSiphon.driver" 2>/dev/null || true
fi

# Remove /Library/LaunchAgents/com.staticz.soundsiphon.inputagent.plist
echo "Removing /Library/LaunchAgents/com.staticz.soundsiphon.inputagent.plist..."
if [ -d "/Library/LaunchAgents/com.staticz.soundsiphon.inputagent.plist" ]; then
    rm -rf "/Library/LaunchAgents/com.staticz.soundsiphon.inputagent.plist" 2>/dev/null || true
elif [ -f "/Library/LaunchAgents/com.staticz.soundsiphon.inputagent.plist" ]; then
    rm -f "/Library/LaunchAgents/com.staticz.soundsiphon.inputagent.plist" 2>/dev/null || true
fi

# Remove /Library/LaunchAgents/com.staticz.soundsiphon.playeragent.plist
echo "Removing /Library/LaunchAgents/com.staticz.soundsiphon.playeragent.plist..."
if [ -d "/Library/LaunchAgents/com.staticz.soundsiphon.playeragent.plist" ]; then
    rm -rf "/Library/LaunchAgents/com.staticz.soundsiphon.playeragent.plist" 2>/dev/null || true
elif [ -f "/Library/LaunchAgents/com.staticz.soundsiphon.playeragent.plist" ]; then
    rm -f "/Library/LaunchAgents/com.staticz.soundsiphon.playeragent.plist" 2>/dev/null || true
fi

# Remove /Library/LaunchDaemons/com.staticz.soundsiphon.bridgedaemon.plist
echo "Removing /Library/LaunchDaemons/com.staticz.soundsiphon.bridgedaemon.plist..."
if [ -d "/Library/LaunchDaemons/com.staticz.soundsiphon.bridgedaemon.plist" ]; then
    rm -rf "/Library/LaunchDaemons/com.staticz.soundsiphon.bridgedaemon.plist" 2>/dev/null || true
elif [ -f "/Library/LaunchDaemons/com.staticz.soundsiphon.bridgedaemon.plist" ]; then
    rm -f "/Library/LaunchDaemons/com.staticz.soundsiphon.bridgedaemon.plist" 2>/dev/null || true
fi

# Remove /Library/Preferences/Audio/Data/_SoundSiphon.driver
echo "Removing /Library/Preferences/Audio/Data/_SoundSiphon.driver..."
if [ -d "/Library/Preferences/Audio/Data/_SoundSiphon.driver" ]; then
    rm -rf "/Library/Preferences/Audio/Data/_SoundSiphon.driver" 2>/dev/null || true
elif [ -f "/Library/Preferences/Audio/Data/_SoundSiphon.driver" ]; then
    rm -f "/Library/Preferences/Audio/Data/_SoundSiphon.driver" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.staticz.SoundControl
echo "Removing $HOME/Library/Application Support/com.staticz.SoundControl..."
if [ -d "$HOME/Library/Application Support/com.staticz.SoundControl" ]; then
    rm -rf "$HOME/Library/Application Support/com.staticz.SoundControl" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.staticz.SoundControl" ]; then
    rm -f "$HOME/Library/Application Support/com.staticz.SoundControl" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.staticz.SoundControl
echo "Removing $HOME/Library/Caches/com.staticz.SoundControl..."
if [ -d "$HOME/Library/Caches/com.staticz.SoundControl" ]; then
    rm -rf "$HOME/Library/Caches/com.staticz.SoundControl" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.staticz.SoundControl" ]; then
    rm -f "$HOME/Library/Caches/com.staticz.SoundControl" 2>/dev/null || true
fi

# Remove $HOME/Library/Cookies/com.staticz.SoundControl.binarycookies
echo "Removing $HOME/Library/Cookies/com.staticz.SoundControl.binarycookies..."
if [ -d "$HOME/Library/Cookies/com.staticz.SoundControl.binarycookies" ]; then
    rm -rf "$HOME/Library/Cookies/com.staticz.SoundControl.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/Cookies/com.staticz.SoundControl.binarycookies" ]; then
    rm -f "$HOME/Library/Cookies/com.staticz.SoundControl.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Cookies/com.staticz.SoundControl.binarycookies*
echo "Removing $HOME/Library/Cookies/com.staticz.SoundControl.binarycookies*..."
if [ -d "$HOME/Library/Cookies/com.staticz.SoundControl.binarycookies*" ]; then
    rm -rf "$HOME/Library/Cookies/com.staticz.SoundControl.binarycookies*" 2>/dev/null || true
elif [ -f "$HOME/Library/Cookies/com.staticz.SoundControl.binarycookies*" ]; then
    rm -f "$HOME/Library/Cookies/com.staticz.SoundControl.binarycookies*" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.staticz.SoundControl.binarycookies
echo "Removing $HOME/Library/HTTPStorages/com.staticz.SoundControl.binarycookies..."
if [ -d "$HOME/Library/HTTPStorages/com.staticz.SoundControl.binarycookies" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.staticz.SoundControl.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.staticz.SoundControl.binarycookies" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.staticz.SoundControl.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.staticz.SoundControl.plist
echo "Removing $HOME/Library/Preferences/com.staticz.SoundControl.plist..."
if [ -d "$HOME/Library/Preferences/com.staticz.SoundControl.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.staticz.SoundControl.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.staticz.SoundControl.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.staticz.SoundControl.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.staticz.soundsiphon.playeragent.plist
echo "Removing $HOME/Library/Preferences/com.staticz.soundsiphon.playeragent.plist..."
if [ -d "$HOME/Library/Preferences/com.staticz.soundsiphon.playeragent.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.staticz.soundsiphon.playeragent.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.staticz.soundsiphon.playeragent.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.staticz.soundsiphon.playeragent.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
