#!/bin/bash
# Uninstall script for Boostnote.Next
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Boostnote.Next..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Boostnote.Next if running..."
pkill -f "Boostnote.Next" 2>/dev/null || true

# Remove /Applications/Boost Note.app
echo "Removing /Applications/Boost Note.app..."
if [ -d "/Applications/Boost Note.app" ]; then
    rm -rf "/Applications/Boost Note.app" 2>/dev/null || true
elif [ -f "/Applications/Boost Note.app" ]; then
    rm -f "/Applications/Boost Note.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Boost Note
echo "Removing $HOME/Library/Application Support/Boost Note..."
if [ -d "$HOME/Library/Application Support/Boost Note" ]; then
    rm -rf "$HOME/Library/Application Support/Boost Note" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Boost Note" ]; then
    rm -f "$HOME/Library/Application Support/Boost Note" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.boostio.boostnote.plist
echo "Removing $HOME/Library/Preferences/com.boostio.boostnote.plist..."
if [ -d "$HOME/Library/Preferences/com.boostio.boostnote.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.boostio.boostnote.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.boostio.boostnote.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.boostio.boostnote.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.boostio.boostnote.savedState
echo "Removing $HOME/Library/Saved Application State/com.boostio.boostnote.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.boostio.boostnote.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.boostio.boostnote.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.boostio.boostnote.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.boostio.boostnote.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
