#!/bin/bash
# Uninstall script for squash
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling squash..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping squash if running..."
pkill -f "squash" 2>/dev/null || true

# Remove /Applications/Squash.app
echo "Removing /Applications/Squash.app..."
if [ -d "/Applications/Squash.app" ]; then
    rm -rf "/Applications/Squash.app" 2>/dev/null || true
elif [ -f "/Applications/Squash.app" ]; then
    rm -f "/Applications/Squash.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.realmacsoftware.squash3
echo "Removing $HOME/Library/Application Scripts/com.realmacsoftware.squash3..."
if [ -d "$HOME/Library/Application Scripts/com.realmacsoftware.squash3" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.realmacsoftware.squash3" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.realmacsoftware.squash3" ]; then
    rm -f "$HOME/Library/Application Scripts/com.realmacsoftware.squash3" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.realmacsoftware.squash3
echo "Removing $HOME/Library/Containers/com.realmacsoftware.squash3..."
if [ -d "$HOME/Library/Containers/com.realmacsoftware.squash3" ]; then
    rm -rf "$HOME/Library/Containers/com.realmacsoftware.squash3" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.realmacsoftware.squash3" ]; then
    rm -f "$HOME/Library/Containers/com.realmacsoftware.squash3" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
