#!/bin/bash
# Uninstall script for Netron
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Netron..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Netron if running..."
pkill -f "Netron" 2>/dev/null || true

# Remove /Applications/Netron.app
echo "Removing /Applications/Netron.app..."
if [ -d "/Applications/Netron.app" ]; then
    rm -rf "/Applications/Netron.app" 2>/dev/null || true
elif [ -f "/Applications/Netron.app" ]; then
    rm -f "/Applications/Netron.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Netron
echo "Removing $HOME/Library/Application Support/Netron..."
if [ -d "$HOME/Library/Application Support/Netron" ]; then
    rm -rf "$HOME/Library/Application Support/Netron" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Netron" ]; then
    rm -f "$HOME/Library/Application Support/Netron" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.lutzroeder.netron.plist
echo "Removing $HOME/Library/Preferences/com.lutzroeder.netron.plist..."
if [ -d "$HOME/Library/Preferences/com.lutzroeder.netron.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.lutzroeder.netron.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.lutzroeder.netron.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.lutzroeder.netron.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.lutzroeder.netron.savedState
echo "Removing $HOME/Library/Saved Application State/com.lutzroeder.netron.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.lutzroeder.netron.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.lutzroeder.netron.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.lutzroeder.netron.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.lutzroeder.netron.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
