#!/bin/bash
# Uninstall script for FluidVoice
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling FluidVoice..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping FluidVoice if running..."
pkill -f "FluidVoice" 2>/dev/null || true

# Remove /Applications/FluidVoice.app
echo "Removing /Applications/FluidVoice.app..."
if [ -d "/Applications/FluidVoice.app" ]; then
    rm -rf "/Applications/FluidVoice.app" 2>/dev/null || true
elif [ -f "/Applications/FluidVoice.app" ]; then
    rm -f "/Applications/FluidVoice.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/FluidAudio
echo "Removing $HOME/Library/Application Support/FluidAudio..."
if [ -d "$HOME/Library/Application Support/FluidAudio" ]; then
    rm -rf "$HOME/Library/Application Support/FluidAudio" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/FluidAudio" ]; then
    rm -f "$HOME/Library/Application Support/FluidAudio" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/FluidVoice
echo "Removing $HOME/Library/Application Support/FluidVoice..."
if [ -d "$HOME/Library/Application Support/FluidVoice" ]; then
    rm -rf "$HOME/Library/Application Support/FluidVoice" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/FluidVoice" ]; then
    rm -f "$HOME/Library/Application Support/FluidVoice" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.FluidApp.app
echo "Removing $HOME/Library/Caches/com.FluidApp.app..."
if [ -d "$HOME/Library/Caches/com.FluidApp.app" ]; then
    rm -rf "$HOME/Library/Caches/com.FluidApp.app" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.FluidApp.app" ]; then
    rm -f "$HOME/Library/Caches/com.FluidApp.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/FluidAudio
echo "Removing $HOME/Library/Caches/FluidAudio..."
if [ -d "$HOME/Library/Caches/FluidAudio" ]; then
    rm -rf "$HOME/Library/Caches/FluidAudio" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/FluidAudio" ]; then
    rm -f "$HOME/Library/Caches/FluidAudio" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Fluid
echo "Removing $HOME/Library/Logs/Fluid..."
if [ -d "$HOME/Library/Logs/Fluid" ]; then
    rm -rf "$HOME/Library/Logs/Fluid" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Fluid" ]; then
    rm -f "$HOME/Library/Logs/Fluid" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.FluidApp.app.plist
echo "Removing $HOME/Library/Preferences/com.FluidApp.app.plist..."
if [ -d "$HOME/Library/Preferences/com.FluidApp.app.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.FluidApp.app.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.FluidApp.app.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.FluidApp.app.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
