#!/bin/bash
# Uninstall script for MakeMKV
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling MakeMKV..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping MakeMKV if running..."
pkill -f "MakeMKV" 2>/dev/null || true

# Remove /Applications/MakeMKV.app
echo "Removing /Applications/MakeMKV.app..."
if [ -d "/Applications/MakeMKV.app" ]; then
    rm -rf "/Applications/MakeMKV.app" 2>/dev/null || true
elif [ -f "/Applications/MakeMKV.app" ]; then
    rm -f "/Applications/MakeMKV.app" 2>/dev/null || true
fi

# Remove binary /Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/makemkvcon
echo "Removing binary /Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/makemkvcon..."
if [ -f "/Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/makemkvcon" ]; then
    rm -f "/Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/makemkvcon" 2>/dev/null || true
fi

# Remove binary /Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/mmccextr
echo "Removing binary /Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/mmccextr..."
if [ -f "/Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/mmccextr" ]; then
    rm -f "/Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/mmccextr" 2>/dev/null || true
fi

# Remove binary /Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/mmgplsrv
echo "Removing binary /Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/mmgplsrv..."
if [ -f "/Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/mmgplsrv" ]; then
    rm -f "/Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/mmgplsrv" 2>/dev/null || true
fi

# Remove binary /Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/sdftool
echo "Removing binary /Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/sdftool..."
if [ -f "/Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/sdftool" ]; then
    rm -f "/Applications/MakeMKV.app/MakeMKV.app/Contents/MacOS/sdftool" 2>/dev/null || true
fi

# Remove $HOME/Library/MakeMKV
echo "Removing $HOME/Library/MakeMKV..."
if [ -d "$HOME/Library/MakeMKV" ]; then
    rm -rf "$HOME/Library/MakeMKV" 2>/dev/null || true
elif [ -f "$HOME/Library/MakeMKV" ]; then
    rm -f "$HOME/Library/MakeMKV" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.makemkv.MakeMKV.plist
echo "Removing $HOME/Library/Preferences/com.makemkv.MakeMKV.plist..."
if [ -d "$HOME/Library/Preferences/com.makemkv.MakeMKV.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.makemkv.MakeMKV.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.makemkv.MakeMKV.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.makemkv.MakeMKV.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.makemkv.MakeMKV.savedState
echo "Removing $HOME/Library/Saved Application State/com.makemkv.MakeMKV.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.makemkv.MakeMKV.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.makemkv.MakeMKV.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.makemkv.MakeMKV.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.makemkv.MakeMKV.savedState" 2>/dev/null || true
fi

# Remove $HOME/Movies/.MakeMKV
echo "Removing $HOME/Movies/.MakeMKV..."
if [ -d "$HOME/Movies/.MakeMKV" ]; then
    rm -rf "$HOME/Movies/.MakeMKV" 2>/dev/null || true
elif [ -f "$HOME/Movies/.MakeMKV" ]; then
    rm -f "$HOME/Movies/.MakeMKV" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
