#!/bin/bash
# Uninstall script for RoboForm
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling RoboForm..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping RoboForm if running..."
pkill -f "RoboForm" 2>/dev/null || true

# Remove /Applications/RoboForm.app
echo "Removing /Applications/RoboForm.app..."
if [ -d "/Applications/RoboForm.app" ]; then
    rm -rf "/Applications/RoboForm.app" 2>/dev/null || true
elif [ -f "/Applications/RoboForm.app" ]; then
    rm -f "/Applications/RoboForm.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/*.com.SiberSystems.RoboForm
echo "Removing $HOME/Library/Application Scripts/*.com.SiberSystems.RoboForm..."
if [ -d "$HOME/Library/Application Scripts/*.com.SiberSystems.RoboForm" ]; then
    rm -rf "$HOME/Library/Application Scripts/*.com.SiberSystems.RoboForm" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/*.com.SiberSystems.RoboForm" ]; then
    rm -f "$HOME/Library/Application Scripts/*.com.SiberSystems.RoboForm" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.SiberSystems.RoboForm.safari-companion*
echo "Removing $HOME/Library/Application Scripts/com.SiberSystems.RoboForm.safari-companion*..."
if [ -d "$HOME/Library/Application Scripts/com.SiberSystems.RoboForm.safari-companion*" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.SiberSystems.RoboForm.safari-companion*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.SiberSystems.RoboForm.safari-companion*" ]; then
    rm -f "$HOME/Library/Application Scripts/com.SiberSystems.RoboForm.safari-companion*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.sibersystems.RoboFormMac.RFCredentialProvider
echo "Removing $HOME/Library/Application Scripts/com.sibersystems.RoboFormMac.RFCredentialProvider..."
if [ -d "$HOME/Library/Application Scripts/com.sibersystems.RoboFormMac.RFCredentialProvider" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.sibersystems.RoboFormMac.RFCredentialProvider" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.sibersystems.RoboFormMac.RFCredentialProvider" ]; then
    rm -f "$HOME/Library/Application Scripts/com.sibersystems.RoboFormMac.RFCredentialProvider" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.sibersystems.RoboFormMac.SafariAppExtension
echo "Removing $HOME/Library/Application Scripts/com.sibersystems.RoboFormMac.SafariAppExtension..."
if [ -d "$HOME/Library/Application Scripts/com.sibersystems.RoboFormMac.SafariAppExtension" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.sibersystems.RoboFormMac.SafariAppExtension" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.sibersystems.RoboFormMac.SafariAppExtension" ]; then
    rm -f "$HOME/Library/Application Scripts/com.sibersystems.RoboFormMac.SafariAppExtension" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.SiberSystems.RoboForm
echo "Removing $HOME/Library/Application Support/com.SiberSystems.RoboForm..."
if [ -d "$HOME/Library/Application Support/com.SiberSystems.RoboForm" ]; then
    rm -rf "$HOME/Library/Application Support/com.SiberSystems.RoboForm" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.SiberSystems.RoboForm" ]; then
    rm -f "$HOME/Library/Application Support/com.SiberSystems.RoboForm" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.SiberSystems.RoboForm.RoboFormService
echo "Removing $HOME/Library/Application Support/com.SiberSystems.RoboForm.RoboFormService..."
if [ -d "$HOME/Library/Application Support/com.SiberSystems.RoboForm.RoboFormService" ]; then
    rm -rf "$HOME/Library/Application Support/com.SiberSystems.RoboForm.RoboFormService" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.SiberSystems.RoboForm.RoboFormService" ]; then
    rm -f "$HOME/Library/Application Support/com.SiberSystems.RoboForm.RoboFormService" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.sibersystems.RoboFormMac
echo "Removing $HOME/Library/Application Support/com.sibersystems.RoboFormMac..."
if [ -d "$HOME/Library/Application Support/com.sibersystems.RoboFormMac" ]; then
    rm -rf "$HOME/Library/Application Support/com.sibersystems.RoboFormMac" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.sibersystems.RoboFormMac" ]; then
    rm -f "$HOME/Library/Application Support/com.sibersystems.RoboFormMac" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/RoboForm
echo "Removing $HOME/Library/Application Support/RoboForm..."
if [ -d "$HOME/Library/Application Support/RoboForm" ]; then
    rm -rf "$HOME/Library/Application Support/RoboForm" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/RoboForm" ]; then
    rm -f "$HOME/Library/Application Support/RoboForm" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.crashlytics.data/com.SiberSystems.RoboForm
echo "Removing $HOME/Library/Caches/com.crashlytics.data/com.SiberSystems.RoboForm..."
if [ -d "$HOME/Library/Caches/com.crashlytics.data/com.SiberSystems.RoboForm" ]; then
    rm -rf "$HOME/Library/Caches/com.crashlytics.data/com.SiberSystems.RoboForm" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.crashlytics.data/com.SiberSystems.RoboForm" ]; then
    rm -f "$HOME/Library/Caches/com.crashlytics.data/com.SiberSystems.RoboForm" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.crashlytics.data/com.SiberSystems.RoboForm.RoboFormService
echo "Removing $HOME/Library/Caches/com.crashlytics.data/com.SiberSystems.RoboForm.RoboFormService..."
if [ -d "$HOME/Library/Caches/com.crashlytics.data/com.SiberSystems.RoboForm.RoboFormService" ]; then
    rm -rf "$HOME/Library/Caches/com.crashlytics.data/com.SiberSystems.RoboForm.RoboFormService" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.crashlytics.data/com.SiberSystems.RoboForm.RoboFormService" ]; then
    rm -f "$HOME/Library/Caches/com.crashlytics.data/com.SiberSystems.RoboForm.RoboFormService" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.SiberSystems.RoboForm
echo "Removing $HOME/Library/Caches/com.SiberSystems.RoboForm..."
if [ -d "$HOME/Library/Caches/com.SiberSystems.RoboForm" ]; then
    rm -rf "$HOME/Library/Caches/com.SiberSystems.RoboForm" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.SiberSystems.RoboForm" ]; then
    rm -f "$HOME/Library/Caches/com.SiberSystems.RoboForm" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.SiberSystems.RoboForm.RoboFormService
echo "Removing $HOME/Library/Caches/com.SiberSystems.RoboForm.RoboFormService..."
if [ -d "$HOME/Library/Caches/com.SiberSystems.RoboForm.RoboFormService" ]; then
    rm -rf "$HOME/Library/Caches/com.SiberSystems.RoboForm.RoboFormService" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.SiberSystems.RoboForm.RoboFormService" ]; then
    rm -f "$HOME/Library/Caches/com.SiberSystems.RoboForm.RoboFormService" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.sibersystems.RoboFormMac
echo "Removing $HOME/Library/Caches/com.sibersystems.RoboFormMac..."
if [ -d "$HOME/Library/Caches/com.sibersystems.RoboFormMac" ]; then
    rm -rf "$HOME/Library/Caches/com.sibersystems.RoboFormMac" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.sibersystems.RoboFormMac" ]; then
    rm -f "$HOME/Library/Caches/com.sibersystems.RoboFormMac" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/io.fabric.sdk.mac.data/com.SiberSystems.RoboForm
echo "Removing $HOME/Library/Caches/io.fabric.sdk.mac.data/com.SiberSystems.RoboForm..."
if [ -d "$HOME/Library/Caches/io.fabric.sdk.mac.data/com.SiberSystems.RoboForm" ]; then
    rm -rf "$HOME/Library/Caches/io.fabric.sdk.mac.data/com.SiberSystems.RoboForm" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/io.fabric.sdk.mac.data/com.SiberSystems.RoboForm" ]; then
    rm -f "$HOME/Library/Caches/io.fabric.sdk.mac.data/com.SiberSystems.RoboForm" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/io.fabric.sdk.mac.data/com.SiberSystems.RoboForm.RoboFormService
echo "Removing $HOME/Library/Caches/io.fabric.sdk.mac.data/com.SiberSystems.RoboForm.RoboFormService..."
if [ -d "$HOME/Library/Caches/io.fabric.sdk.mac.data/com.SiberSystems.RoboForm.RoboFormService" ]; then
    rm -rf "$HOME/Library/Caches/io.fabric.sdk.mac.data/com.SiberSystems.RoboForm.RoboFormService" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/io.fabric.sdk.mac.data/com.SiberSystems.RoboForm.RoboFormService" ]; then
    rm -f "$HOME/Library/Caches/io.fabric.sdk.mac.data/com.SiberSystems.RoboForm.RoboFormService" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.SiberSystems.RoboForm.safari-companion*
echo "Removing $HOME/Library/Containers/com.SiberSystems.RoboForm.safari-companion*..."
if [ -d "$HOME/Library/Containers/com.SiberSystems.RoboForm.safari-companion*" ]; then
    rm -rf "$HOME/Library/Containers/com.SiberSystems.RoboForm.safari-companion*" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.SiberSystems.RoboForm.safari-companion*" ]; then
    rm -f "$HOME/Library/Containers/com.SiberSystems.RoboForm.safari-companion*" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.sibersystems.RoboFormMac.RFCredentialProvider
echo "Removing $HOME/Library/Containers/com.sibersystems.RoboFormMac.RFCredentialProvider..."
if [ -d "$HOME/Library/Containers/com.sibersystems.RoboFormMac.RFCredentialProvider" ]; then
    rm -rf "$HOME/Library/Containers/com.sibersystems.RoboFormMac.RFCredentialProvider" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.sibersystems.RoboFormMac.RFCredentialProvider" ]; then
    rm -f "$HOME/Library/Containers/com.sibersystems.RoboFormMac.RFCredentialProvider" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.sibersystems.RoboFormMac.SafariAppExtension
echo "Removing $HOME/Library/Containers/com.sibersystems.RoboFormMac.SafariAppExtension..."
if [ -d "$HOME/Library/Containers/com.sibersystems.RoboFormMac.SafariAppExtension" ]; then
    rm -rf "$HOME/Library/Containers/com.sibersystems.RoboFormMac.SafariAppExtension" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.sibersystems.RoboFormMac.SafariAppExtension" ]; then
    rm -f "$HOME/Library/Containers/com.sibersystems.RoboFormMac.SafariAppExtension" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/*.com.SiberSystems.RoboForm
echo "Removing $HOME/Library/Group Containers/*.com.SiberSystems.RoboForm..."
if [ -d "$HOME/Library/Group Containers/*.com.SiberSystems.RoboForm" ]; then
    rm -rf "$HOME/Library/Group Containers/*.com.SiberSystems.RoboForm" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/*.com.SiberSystems.RoboForm" ]; then
    rm -f "$HOME/Library/Group Containers/*.com.SiberSystems.RoboForm" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.SiberSystems.RoboForm
echo "Removing $HOME/Library/HTTPStorages/com.SiberSystems.RoboForm..."
if [ -d "$HOME/Library/HTTPStorages/com.SiberSystems.RoboForm" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.SiberSystems.RoboForm" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.SiberSystems.RoboForm" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.SiberSystems.RoboForm" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.sibersystems.RoboFormMac
echo "Removing $HOME/Library/HTTPStorages/com.sibersystems.RoboFormMac..."
if [ -d "$HOME/Library/HTTPStorages/com.sibersystems.RoboFormMac" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.sibersystems.RoboFormMac" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.sibersystems.RoboFormMac" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.sibersystems.RoboFormMac" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.SiberSystems.RoboForm.plist
echo "Removing $HOME/Library/Preferences/com.SiberSystems.RoboForm.plist..."
if [ -d "$HOME/Library/Preferences/com.SiberSystems.RoboForm.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.SiberSystems.RoboForm.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.SiberSystems.RoboForm.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.SiberSystems.RoboForm.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.sibersystems.RoboFormMac.plist
echo "Removing $HOME/Library/Preferences/com.sibersystems.RoboFormMac.plist..."
if [ -d "$HOME/Library/Preferences/com.sibersystems.RoboFormMac.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.sibersystems.RoboFormMac.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.sibersystems.RoboFormMac.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.sibersystems.RoboFormMac.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.SiberSystems.RoboForm.savedState
echo "Removing $HOME/Library/Saved Application State/com.SiberSystems.RoboForm.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.SiberSystems.RoboForm.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.SiberSystems.RoboForm.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.SiberSystems.RoboForm.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.SiberSystems.RoboForm.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.sibersystems.RoboFormMac
echo "Removing $HOME/Library/WebKit/com.sibersystems.RoboFormMac..."
if [ -d "$HOME/Library/WebKit/com.sibersystems.RoboFormMac" ]; then
    rm -rf "$HOME/Library/WebKit/com.sibersystems.RoboFormMac" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.sibersystems.RoboFormMac" ]; then
    rm -f "$HOME/Library/WebKit/com.sibersystems.RoboFormMac" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
