#!/bin/bash
# Uninstall script for Taskade
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Taskade..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Taskade if running..."
pkill -f "Taskade" 2>/dev/null || true

# Remove /Applications/Taskade.app
echo "Removing /Applications/Taskade.app..."
if [ -d "/Applications/Taskade.app" ]; then
    rm -rf "/Applications/Taskade.app" 2>/dev/null || true
elif [ -f "/Applications/Taskade.app" ]; then
    rm -f "/Applications/Taskade.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/taskade
echo "Removing $HOME/Library/Application Support/taskade..."
if [ -d "$HOME/Library/Application Support/taskade" ]; then
    rm -rf "$HOME/Library/Application Support/taskade" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/taskade" ]; then
    rm -f "$HOME/Library/Application Support/taskade" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.taskade.plist
echo "Removing $HOME/Library/Preferences/com.taskade.plist..."
if [ -d "$HOME/Library/Preferences/com.taskade.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.taskade.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.taskade.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.taskade.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.taskade.savedState
echo "Removing $HOME/Library/Saved Application State/com.taskade.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.taskade.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.taskade.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.taskade.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.taskade.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
