#!/bin/bash
# Uninstall script for Superhuman
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Superhuman..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Superhuman if running..."
pkill -f "Superhuman" 2>/dev/null || true

# Remove /Applications/Superhuman.app
echo "Removing /Applications/Superhuman.app..."
if [ -d "/Applications/Superhuman.app" ]; then
    rm -rf "/Applications/Superhuman.app" 2>/dev/null || true
elif [ -f "/Applications/Superhuman.app" ]; then
    rm -f "/Applications/Superhuman.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Superhuman
echo "Removing $HOME/Library/Application Support/Superhuman..."
if [ -d "$HOME/Library/Application Support/Superhuman" ]; then
    rm -rf "$HOME/Library/Application Support/Superhuman" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Superhuman" ]; then
    rm -f "$HOME/Library/Application Support/Superhuman" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.superhuman.electron*
echo "Removing $HOME/Library/Caches/com.superhuman.electron*..."
if [ -d "$HOME/Library/Caches/com.superhuman.electron*" ]; then
    rm -rf "$HOME/Library/Caches/com.superhuman.electron*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.superhuman.electron*" ]; then
    rm -f "$HOME/Library/Caches/com.superhuman.electron*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/Superhuman
echo "Removing $HOME/Library/Caches/Superhuman..."
if [ -d "$HOME/Library/Caches/Superhuman" ]; then
    rm -rf "$HOME/Library/Caches/Superhuman" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/Superhuman" ]; then
    rm -f "$HOME/Library/Caches/Superhuman" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Superhuman
echo "Removing $HOME/Library/Logs/Superhuman..."
if [ -d "$HOME/Library/Logs/Superhuman" ]; then
    rm -rf "$HOME/Library/Logs/Superhuman" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Superhuman" ]; then
    rm -f "$HOME/Library/Logs/Superhuman" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.superhuman.electron.*
echo "Removing $HOME/Library/Preferences/com.superhuman.electron.*..."
if [ -d "$HOME/Library/Preferences/com.superhuman.electron.*" ]; then
    rm -rf "$HOME/Library/Preferences/com.superhuman.electron.*" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.superhuman.electron.*" ]; then
    rm -f "$HOME/Library/Preferences/com.superhuman.electron.*" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.superhuman.mail.plist
echo "Removing $HOME/Library/Preferences/com.superhuman.mail.plist..."
if [ -d "$HOME/Library/Preferences/com.superhuman.mail.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.superhuman.mail.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.superhuman.mail.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.superhuman.mail.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.superhuman.electron.savedState
echo "Removing $HOME/Library/Saved Application State/com.superhuman.electron.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.superhuman.electron.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.superhuman.electron.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.superhuman.electron.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.superhuman.electron.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
