#!/bin/bash
# Uninstall script for Permute
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Permute..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Permute if running..."
pkill -f "Permute" 2>/dev/null || true

# Remove /Applications/Permute 4.app
echo "Removing /Applications/Permute 4.app..."
if [ -d "/Applications/Permute 4.app" ]; then
    rm -rf "/Applications/Permute 4.app" 2>/dev/null || true
elif [ -f "/Applications/Permute 4.app" ]; then
    rm -f "/Applications/Permute 4.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/*.com.charliemonroe.eney
echo "Removing $HOME/Library/Application Scripts/*.com.charliemonroe.eney..."
if [ -d "$HOME/Library/Application Scripts/*.com.charliemonroe.eney" ]; then
    rm -rf "$HOME/Library/Application Scripts/*.com.charliemonroe.eney" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/*.com.charliemonroe.eney" ]; then
    rm -f "$HOME/Library/Application Scripts/*.com.charliemonroe.eney" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/*com.charliemonroe.Permute*
echo "Removing $HOME/Library/Application Scripts/*com.charliemonroe.Permute*..."
if [ -d "$HOME/Library/Application Scripts/*com.charliemonroe.Permute*" ]; then
    rm -rf "$HOME/Library/Application Scripts/*com.charliemonroe.Permute*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/*com.charliemonroe.Permute*" ]; then
    rm -f "$HOME/Library/Application Scripts/*com.charliemonroe.Permute*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.helpd/Generated/com.charliemonroe.Permute-4*
echo "Removing $HOME/Library/Caches/com.apple.helpd/Generated/com.charliemonroe.Permute-4*..."
if [ -d "$HOME/Library/Caches/com.apple.helpd/Generated/com.charliemonroe.Permute-4*" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.helpd/Generated/com.charliemonroe.Permute-4*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.helpd/Generated/com.charliemonroe.Permute-4*" ]; then
    rm -f "$HOME/Library/Caches/com.apple.helpd/Generated/com.charliemonroe.Permute-4*" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.charliemonroe.Permute-4
echo "Removing $HOME/Library/Containers/com.charliemonroe.Permute-4..."
if [ -d "$HOME/Library/Containers/com.charliemonroe.Permute-4" ]; then
    rm -rf "$HOME/Library/Containers/com.charliemonroe.Permute-4" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.charliemonroe.Permute-4" ]; then
    rm -f "$HOME/Library/Containers/com.charliemonroe.Permute-4" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.charliemonroe.Permute.MetadataProcessor
echo "Removing $HOME/Library/Containers/com.charliemonroe.Permute.MetadataProcessor..."
if [ -d "$HOME/Library/Containers/com.charliemonroe.Permute.MetadataProcessor" ]; then
    rm -rf "$HOME/Library/Containers/com.charliemonroe.Permute.MetadataProcessor" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.charliemonroe.Permute.MetadataProcessor" ]; then
    rm -f "$HOME/Library/Containers/com.charliemonroe.Permute.MetadataProcessor" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/*.com.charliemonroe.Permute*
echo "Removing $HOME/Library/Group Containers/*.com.charliemonroe.Permute*..."
if [ -d "$HOME/Library/Group Containers/*.com.charliemonroe.Permute*" ]; then
    rm -rf "$HOME/Library/Group Containers/*.com.charliemonroe.Permute*" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/*.com.charliemonroe.Permute*" ]; then
    rm -f "$HOME/Library/Group Containers/*.com.charliemonroe.Permute*" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.charliemonroe.Permute-4.plist
echo "Removing $HOME/Library/Preferences/com.charliemonroe.Permute-4.plist..."
if [ -d "$HOME/Library/Preferences/com.charliemonroe.Permute-4.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.charliemonroe.Permute-4.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.charliemonroe.Permute-4.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.charliemonroe.Permute-4.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
