#!/bin/bash
# Uninstall script for Firecamp
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Firecamp..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Firecamp if running..."
pkill -f "Firecamp" 2>/dev/null || true

# Remove /Applications/Firecamp.app
echo "Removing /Applications/Firecamp.app..."
if [ -d "/Applications/Firecamp.app" ]; then
    rm -rf "/Applications/Firecamp.app" 2>/dev/null || true
elif [ -f "/Applications/Firecamp.app" ]; then
    rm -f "/Applications/Firecamp.app" 2>/dev/null || true
fi

# Remove $HOME/.firecamp
echo "Removing $HOME/.firecamp..."
if [ -d "$HOME/.firecamp" ]; then
    rm -rf "$HOME/.firecamp" 2>/dev/null || true
elif [ -f "$HOME/.firecamp" ]; then
    rm -f "$HOME/.firecamp" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/firecamp
echo "Removing $HOME/Library/Application Support/firecamp..."
if [ -d "$HOME/Library/Application Support/firecamp" ]; then
    rm -rf "$HOME/Library/Application Support/firecamp" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/firecamp" ]; then
    rm -f "$HOME/Library/Application Support/firecamp" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.firecamp.app.plist
echo "Removing $HOME/Library/Preferences/com.firecamp.app.plist..."
if [ -d "$HOME/Library/Preferences/com.firecamp.app.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.firecamp.app.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.firecamp.app.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.firecamp.app.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
