#!/bin/bash
# Uninstall script for VyprVPN
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling VyprVPN..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping VyprVPN if running..."
pkill -f "VyprVPN" 2>/dev/null || true

# Unload service com.goldenfrog.resourcewatchdog
echo "Unloading service com.goldenfrog.resourcewatchdog..."
launchctl unload -w /Library/LaunchAgents/com.goldenfrog.resourcewatchdog.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.goldenfrog.resourcewatchdog.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.goldenfrog.resourcewatchdog.plist 2>/dev/null || true

# Unload service com.goldenfrog.VyprVPNUserAgent
echo "Unloading service com.goldenfrog.VyprVPNUserAgent..."
launchctl unload -w /Library/LaunchAgents/com.goldenfrog.VyprVPNUserAgent.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.goldenfrog.VyprVPNUserAgent.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.goldenfrog.VyprVPNUserAgent.plist 2>/dev/null || true

# Unload service vyprvpnservice
echo "Unloading service vyprvpnservice..."
launchctl unload -w /Library/LaunchAgents/vyprvpnservice.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/vyprvpnservice.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/vyprvpnservice.plist 2>/dev/null || true

# Kill application with bundle ID com.goldenfrog.VyprVPN* if running
echo "Stopping application with bundle ID com.goldenfrog.VyprVPN* if running..."
killall -9 "com.goldenfrog.VyprVPN*" 2>/dev/null || true

# Remove /Applications/VyprVPN.app
echo "Removing /Applications/VyprVPN.app..."
if [ -d "/Applications/VyprVPN.app" ]; then
    rm -rf "/Applications/VyprVPN.app" 2>/dev/null || true
elif [ -f "/Applications/VyprVPN.app" ]; then
    rm -f "/Applications/VyprVPN.app" 2>/dev/null || true
fi

# Remove /Library/LaunchDaemons/vyrpvpnservice.plist
echo "Removing /Library/LaunchDaemons/vyrpvpnservice.plist..."
if [ -d "/Library/LaunchDaemons/vyrpvpnservice.plist" ]; then
    rm -rf "/Library/LaunchDaemons/vyrpvpnservice.plist" 2>/dev/null || true
elif [ -f "/Library/LaunchDaemons/vyrpvpnservice.plist" ]; then
    rm -f "/Library/LaunchDaemons/vyrpvpnservice.plist" 2>/dev/null || true
fi

# Remove /Library/PrivilegedHelperTools/vyprvpnservice
echo "Removing /Library/PrivilegedHelperTools/vyprvpnservice..."
if [ -d "/Library/PrivilegedHelperTools/vyprvpnservice" ]; then
    rm -rf "/Library/PrivilegedHelperTools/vyprvpnservice" 2>/dev/null || true
elif [ -f "/Library/PrivilegedHelperTools/vyprvpnservice" ]; then
    rm -f "/Library/PrivilegedHelperTools/vyprvpnservice" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.goldenfrog.VyprVPN
echo "Removing $HOME/Library/Caches/com.goldenfrog.VyprVPN..."
if [ -d "$HOME/Library/Caches/com.goldenfrog.VyprVPN" ]; then
    rm -rf "$HOME/Library/Caches/com.goldenfrog.VyprVPN" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.goldenfrog.VyprVPN" ]; then
    rm -f "$HOME/Library/Caches/com.goldenfrog.VyprVPN" 2>/dev/null || true
fi

# Remove $HOME/Library/LaunchAgents/com.goldenfrog.VyprVPNUserAgent.plist
echo "Removing $HOME/Library/LaunchAgents/com.goldenfrog.VyprVPNUserAgent.plist..."
if [ -d "$HOME/Library/LaunchAgents/com.goldenfrog.VyprVPNUserAgent.plist" ]; then
    rm -rf "$HOME/Library/LaunchAgents/com.goldenfrog.VyprVPNUserAgent.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/LaunchAgents/com.goldenfrog.VyprVPNUserAgent.plist" ]; then
    rm -f "$HOME/Library/LaunchAgents/com.goldenfrog.VyprVPNUserAgent.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/GoldenFrog/VyprVPN.log
echo "Removing $HOME/Library/Logs/GoldenFrog/VyprVPN.log..."
if [ -d "$HOME/Library/Logs/GoldenFrog/VyprVPN.log" ]; then
    rm -rf "$HOME/Library/Logs/GoldenFrog/VyprVPN.log" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/GoldenFrog/VyprVPN.log" ]; then
    rm -f "$HOME/Library/Logs/GoldenFrog/VyprVPN.log" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.goldenfrog.VyprVPN.plist
echo "Removing $HOME/Library/Preferences/com.goldenfrog.VyprVPN.plist..."
if [ -d "$HOME/Library/Preferences/com.goldenfrog.VyprVPN.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.goldenfrog.VyprVPN.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.goldenfrog.VyprVPN.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.goldenfrog.VyprVPN.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
