#!/bin/bash
# Uninstall script for VueScan
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling VueScan..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping VueScan if running..."
pkill -f "VueScan" 2>/dev/null || true

# Remove /Applications/VueScan.app
echo "Removing /Applications/VueScan.app..."
if [ -d "/Applications/VueScan.app" ]; then
    rm -rf "/Applications/VueScan.app" 2>/dev/null || true
elif [ -f "/Applications/VueScan.app" ]; then
    rm -f "/Applications/VueScan.app" 2>/dev/null || true
fi

# Remove $HOME/.vuescanrc
echo "Removing $HOME/.vuescanrc..."
if [ -d "$HOME/.vuescanrc" ]; then
    rm -rf "$HOME/.vuescanrc" 2>/dev/null || true
elif [ -f "$HOME/.vuescanrc" ]; then
    rm -f "$HOME/.vuescanrc" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.hamrick.vuescan.plist
echo "Removing $HOME/Library/Preferences/com.hamrick.vuescan.plist..."
if [ -d "$HOME/Library/Preferences/com.hamrick.vuescan.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.hamrick.vuescan.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.hamrick.vuescan.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.hamrick.vuescan.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.hamrick.vuescan.savedState
echo "Removing $HOME/Library/Saved Application State/com.hamrick.vuescan.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.hamrick.vuescan.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.hamrick.vuescan.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.hamrick.vuescan.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.hamrick.vuescan.savedState" 2>/dev/null || true
fi

# Remove $HOME/Pictures/VueScan/vuescan.ini
echo "Removing $HOME/Pictures/VueScan/vuescan.ini..."
if [ -d "$HOME/Pictures/VueScan/vuescan.ini" ]; then
    rm -rf "$HOME/Pictures/VueScan/vuescan.ini" 2>/dev/null || true
elif [ -f "$HOME/Pictures/VueScan/vuescan.ini" ]; then
    rm -f "$HOME/Pictures/VueScan/vuescan.ini" 2>/dev/null || true
fi

# Remove $HOME/Pictures/VueScan/vuescan.log
echo "Removing $HOME/Pictures/VueScan/vuescan.log..."
if [ -d "$HOME/Pictures/VueScan/vuescan.log" ]; then
    rm -rf "$HOME/Pictures/VueScan/vuescan.log" 2>/dev/null || true
elif [ -f "$HOME/Pictures/VueScan/vuescan.log" ]; then
    rm -f "$HOME/Pictures/VueScan/vuescan.log" 2>/dev/null || true
fi

# Remove $HOME/Pictures/VueScan
echo "Removing $HOME/Pictures/VueScan..."
if [ -d "$HOME/Pictures/VueScan" ]; then
    rm -rf "$HOME/Pictures/VueScan" 2>/dev/null || true
elif [ -f "$HOME/Pictures/VueScan" ]; then
    rm -f "$HOME/Pictures/VueScan" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
