#!/bin/bash
# Uninstall script for redis-pro
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling redis-pro..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping redis-pro if running..."
pkill -f "redis-pro" 2>/dev/null || true

# Remove /Applications/redis-pro.app
echo "Removing /Applications/redis-pro.app..."
if [ -d "/Applications/redis-pro.app" ]; then
    rm -rf "/Applications/redis-pro.app" 2>/dev/null || true
elif [ -f "/Applications/redis-pro.app" ]; then
    rm -f "/Applications/redis-pro.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.cmushroom.redis-pro
echo "Removing $HOME/Library/Application Scripts/com.cmushroom.redis-pro..."
if [ -d "$HOME/Library/Application Scripts/com.cmushroom.redis-pro" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.cmushroom.redis-pro" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.cmushroom.redis-pro" ]; then
    rm -f "$HOME/Library/Application Scripts/com.cmushroom.redis-pro" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.cmushroom.redis-pro
echo "Removing $HOME/Library/Application Support/com.cmushroom.redis-pro..."
if [ -d "$HOME/Library/Application Support/com.cmushroom.redis-pro" ]; then
    rm -rf "$HOME/Library/Application Support/com.cmushroom.redis-pro" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.cmushroom.redis-pro" ]; then
    rm -f "$HOME/Library/Application Support/com.cmushroom.redis-pro" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.cmushroom.redis-pro
echo "Removing $HOME/Library/Caches/com.cmushroom.redis-pro..."
if [ -d "$HOME/Library/Caches/com.cmushroom.redis-pro" ]; then
    rm -rf "$HOME/Library/Caches/com.cmushroom.redis-pro" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.cmushroom.redis-pro" ]; then
    rm -f "$HOME/Library/Caches/com.cmushroom.redis-pro" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.cmushroom.redis-pro
echo "Removing $HOME/Library/Containers/com.cmushroom.redis-pro..."
if [ -d "$HOME/Library/Containers/com.cmushroom.redis-pro" ]; then
    rm -rf "$HOME/Library/Containers/com.cmushroom.redis-pro" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.cmushroom.redis-pro" ]; then
    rm -f "$HOME/Library/Containers/com.cmushroom.redis-pro" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.cmushroom.redis-pro.plist
echo "Removing $HOME/Library/Preferences/com.cmushroom.redis-pro.plist..."
if [ -d "$HOME/Library/Preferences/com.cmushroom.redis-pro.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.cmushroom.redis-pro.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.cmushroom.redis-pro.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.cmushroom.redis-pro.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.cmushroom.redis-pro.savedState
echo "Removing $HOME/Library/Saved Application State/com.cmushroom.redis-pro.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.cmushroom.redis-pro.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.cmushroom.redis-pro.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.cmushroom.redis-pro.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.cmushroom.redis-pro.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
