#!/bin/bash
# Uninstall script for Dymo Connect
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Dymo Connect..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Dymo Connect if running..."
pkill -f "Dymo Connect" 2>/dev/null || true

# Unload service com.dymo.dcd.webservice
echo "Unloading service com.dymo.dcd.webservice..."
launchctl unload -w /Library/LaunchAgents/com.dymo.dcd.webservice.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.dymo.dcd.webservice.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.dymo.dcd.webservice.plist 2>/dev/null || true

# Unload service com.dymo.pnpd
echo "Unloading service com.dymo.pnpd..."
launchctl unload -w /Library/LaunchAgents/com.dymo.pnpd.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.dymo.pnpd.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.dymo.pnpd.plist 2>/dev/null || true

# Kill application with bundle ID com.dymo.DYMO-WebApi-Mac-Host if running
echo "Stopping application with bundle ID com.dymo.DYMO-WebApi-Mac-Host if running..."
killall -9 "com.dymo.DYMO-WebApi-Mac-Host" 2>/dev/null || true

# Remove $HOME/Library/Preferences/com.dymo.DYMO-WebApi-Mac-Host.plist
echo "Removing $HOME/Library/Preferences/com.dymo.DYMO-WebApi-Mac-Host.plist..."
if [ -d "$HOME/Library/Preferences/com.dymo.DYMO-WebApi-Mac-Host.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.dymo.DYMO-WebApi-Mac-Host.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.dymo.DYMO-WebApi-Mac-Host.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.dymo.DYMO-WebApi-Mac-Host.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
