#!/bin/bash
# Uninstall script for KiCad
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling KiCad..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping KiCad if running..."
pkill -f "KiCad" 2>/dev/null || true

# Remove binary /Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/idf2vrml
echo "Removing binary /Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/idf2vrml..."
if [ -f "/Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/idf2vrml" ]; then
    rm -f "/Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/idf2vrml" 2>/dev/null || true
fi

# Remove binary /Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/idfcyl
echo "Removing binary /Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/idfcyl..."
if [ -f "/Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/idfcyl" ]; then
    rm -f "/Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/idfcyl" 2>/dev/null || true
fi

# Remove binary /Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/kicad-cli
echo "Removing binary /Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/kicad-cli..."
if [ -f "/Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/kicad-cli" ]; then
    rm -f "/Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/kicad-cli" 2>/dev/null || true
fi

# Remove binary /Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/idfrect
echo "Removing binary /Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/idfrect..."
if [ -f "/Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/idfrect" ]; then
    rm -f "/Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/idfrect" 2>/dev/null || true
fi

# Remove binary /Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/dxf2idf
echo "Removing binary /Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/dxf2idf..."
if [ -f "/Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/dxf2idf" ]; then
    rm -f "/Applications/KiCad.app/KiCad/KiCad.app/Contents/MacOS/dxf2idf" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/kicad
echo "Removing $HOME/Library/Application Support/kicad..."
if [ -d "$HOME/Library/Application Support/kicad" ]; then
    rm -rf "$HOME/Library/Application Support/kicad" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/kicad" ]; then
    rm -f "$HOME/Library/Application Support/kicad" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/kicad
echo "Removing $HOME/Library/Preferences/kicad..."
if [ -d "$HOME/Library/Preferences/kicad" ]; then
    rm -rf "$HOME/Library/Preferences/kicad" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/kicad" ]; then
    rm -f "$HOME/Library/Preferences/kicad" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/org.kicad-pcb.*
echo "Removing $HOME/Library/Preferences/org.kicad-pcb.*..."
if [ -d "$HOME/Library/Preferences/org.kicad-pcb.*" ]; then
    rm -rf "$HOME/Library/Preferences/org.kicad-pcb.*" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/org.kicad-pcb.*" ]; then
    rm -f "$HOME/Library/Preferences/org.kicad-pcb.*" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/org.kicad-pcb.*
echo "Removing $HOME/Library/Saved Application State/org.kicad-pcb.*..."
if [ -d "$HOME/Library/Saved Application State/org.kicad-pcb.*" ]; then
    rm -rf "$HOME/Library/Saved Application State/org.kicad-pcb.*" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/org.kicad-pcb.*" ]; then
    rm -f "$HOME/Library/Saved Application State/org.kicad-pcb.*" 2>/dev/null || true
fi

# Remove /Library/Application Support/kicad
echo "Removing /Library/Application Support/kicad..."
if [ -d "/Library/Application Support/kicad" ]; then
    rm -rf "/Library/Application Support/kicad" 2>/dev/null || true
elif [ -f "/Library/Application Support/kicad" ]; then
    rm -f "/Library/Application Support/kicad" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
