#!/bin/bash
# Uninstall script for Ableton Live Lite
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Ableton Live Lite..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Ableton Live Lite if running..."
pkill -f "Ableton Live Lite" 2>/dev/null || true

# Kill application with bundle ID com.ableton.live if running
echo "Stopping application with bundle ID com.ableton.live if running..."
killall -9 "com.ableton.live" 2>/dev/null || true

# Remove /Applications/Ableton Live 12 Lite.app
echo "Removing /Applications/Ableton Live 12 Lite.app..."
if [ -d "/Applications/Ableton Live 12 Lite.app" ]; then
    rm -rf "/Applications/Ableton Live 12 Lite.app" 2>/dev/null || true
elif [ -f "/Applications/Ableton Live 12 Lite.app" ]; then
    rm -f "/Applications/Ableton Live 12 Lite.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Ableton
echo "Removing $HOME/Library/Application Support/Ableton..."
if [ -d "$HOME/Library/Application Support/Ableton" ]; then
    rm -rf "$HOME/Library/Application Support/Ableton" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Ableton" ]; then
    rm -f "$HOME/Library/Application Support/Ableton" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/CrashReporter/Ableton *_*.plist
echo "Removing $HOME/Library/Application Support/CrashReporter/Ableton *_*.plist..."
if [ -d "$HOME/Library/Application Support/CrashReporter/Ableton *_*.plist" ]; then
    rm -rf "$HOME/Library/Application Support/CrashReporter/Ableton *_*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/CrashReporter/Ableton *_*.plist" ]; then
    rm -f "$HOME/Library/Application Support/CrashReporter/Ableton *_*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/CrashReporter/Live_*.plist
echo "Removing $HOME/Library/Application Support/CrashReporter/Live_*.plist..."
if [ -d "$HOME/Library/Application Support/CrashReporter/Live_*.plist" ]; then
    rm -rf "$HOME/Library/Application Support/CrashReporter/Live_*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/CrashReporter/Live_*.plist" ]; then
    rm -f "$HOME/Library/Application Support/CrashReporter/Live_*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/Ableton
echo "Removing $HOME/Library/Caches/Ableton..."
if [ -d "$HOME/Library/Caches/Ableton" ]; then
    rm -rf "$HOME/Library/Caches/Ableton" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/Ableton" ]; then
    rm -f "$HOME/Library/Caches/Ableton" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/Ableton
echo "Removing $HOME/Library/Preferences/Ableton..."
if [ -d "$HOME/Library/Preferences/Ableton" ]; then
    rm -rf "$HOME/Library/Preferences/Ableton" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/Ableton" ]; then
    rm -f "$HOME/Library/Preferences/Ableton" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.ableton.live.plist*
echo "Removing $HOME/Library/Preferences/com.ableton.live.plist*..."
if [ -d "$HOME/Library/Preferences/com.ableton.live.plist*" ]; then
    rm -rf "$HOME/Library/Preferences/com.ableton.live.plist*" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.ableton.live.plist*" ]; then
    rm -f "$HOME/Library/Preferences/com.ableton.live.plist*" 2>/dev/null || true
fi

# Remove $HOME/Music/Ableton
echo "Removing $HOME/Music/Ableton..."
if [ -d "$HOME/Music/Ableton" ]; then
    rm -rf "$HOME/Music/Ableton" 2>/dev/null || true
elif [ -f "$HOME/Music/Ableton" ]; then
    rm -f "$HOME/Music/Ableton" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
