#!/bin/bash
# Uninstall script for Yippy
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Yippy..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Yippy if running..."
pkill -f "Yippy" 2>/dev/null || true

# Remove /Applications/Yippy.app
echo "Removing /Applications/Yippy.app..."
if [ -d "/Applications/Yippy.app" ]; then
    rm -rf "/Applications/Yippy.app" 2>/dev/null || true
elif [ -f "/Applications/Yippy.app" ]; then
    rm -f "/Applications/Yippy.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/MatthewDavidson.Yippy
echo "Removing $HOME/Library/Application Support/MatthewDavidson.Yippy..."
if [ -d "$HOME/Library/Application Support/MatthewDavidson.Yippy" ]; then
    rm -rf "$HOME/Library/Application Support/MatthewDavidson.Yippy" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/MatthewDavidson.Yippy" ]; then
    rm -f "$HOME/Library/Application Support/MatthewDavidson.Yippy" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
