#!/bin/bash
# Uninstall script for Jetbrains PyCharm Community Edition
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Jetbrains PyCharm Community Edition..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Jetbrains PyCharm Community Edition if running..."
pkill -f "Jetbrains PyCharm Community Edition" 2>/dev/null || true

# Remove /Applications/PyCharm CE.app
echo "Removing /Applications/PyCharm CE.app..."
if [ -d "/Applications/PyCharm CE.app" ]; then
    rm -rf "/Applications/PyCharm CE.app" 2>/dev/null || true
elif [ -f "/Applications/PyCharm CE.app" ]; then
    rm -f "/Applications/PyCharm CE.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/JetBrains/PyCharmCE2025.2
echo "Removing $HOME/Library/Application Support/JetBrains/PyCharmCE2025.2..."
if [ -d "$HOME/Library/Application Support/JetBrains/PyCharmCE2025.2" ]; then
    rm -rf "$HOME/Library/Application Support/JetBrains/PyCharmCE2025.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/JetBrains/PyCharmCE2025.2" ]; then
    rm -f "$HOME/Library/Application Support/JetBrains/PyCharmCE2025.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/PyCharm2025.2
echo "Removing $HOME/Library/Application Support/PyCharm2025.2..."
if [ -d "$HOME/Library/Application Support/PyCharm2025.2" ]; then
    rm -rf "$HOME/Library/Application Support/PyCharm2025.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/PyCharm2025.2" ]; then
    rm -f "$HOME/Library/Application Support/PyCharm2025.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.python/Applications/PyCharm CE.app
echo "Removing $HOME/Library/Caches/com.apple.python/Applications/PyCharm CE.app..."
if [ -d "$HOME/Library/Caches/com.apple.python/Applications/PyCharm CE.app" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.python/Applications/PyCharm CE.app" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.python/Applications/PyCharm CE.app" ]; then
    rm -f "$HOME/Library/Caches/com.apple.python/Applications/PyCharm CE.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/JetBrains/PyCharmCE2025.2
echo "Removing $HOME/Library/Caches/JetBrains/PyCharmCE2025.2..."
if [ -d "$HOME/Library/Caches/JetBrains/PyCharmCE2025.2" ]; then
    rm -rf "$HOME/Library/Caches/JetBrains/PyCharmCE2025.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/JetBrains/PyCharmCE2025.2" ]; then
    rm -f "$HOME/Library/Caches/JetBrains/PyCharmCE2025.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/PyCharm2025.2
echo "Removing $HOME/Library/Caches/PyCharm2025.2..."
if [ -d "$HOME/Library/Caches/PyCharm2025.2" ]; then
    rm -rf "$HOME/Library/Caches/PyCharm2025.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/PyCharm2025.2" ]; then
    rm -f "$HOME/Library/Caches/PyCharm2025.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/PyCharmCE2025.2
echo "Removing $HOME/Library/Caches/PyCharmCE2025.2..."
if [ -d "$HOME/Library/Caches/PyCharmCE2025.2" ]; then
    rm -rf "$HOME/Library/Caches/PyCharmCE2025.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/PyCharmCE2025.2" ]; then
    rm -f "$HOME/Library/Caches/PyCharmCE2025.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/JetBrains/PyCharmCE2025.2
echo "Removing $HOME/Library/Logs/JetBrains/PyCharmCE2025.2..."
if [ -d "$HOME/Library/Logs/JetBrains/PyCharmCE2025.2" ]; then
    rm -rf "$HOME/Library/Logs/JetBrains/PyCharmCE2025.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/JetBrains/PyCharmCE2025.2" ]; then
    rm -f "$HOME/Library/Logs/JetBrains/PyCharmCE2025.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/PyCharm2025.2
echo "Removing $HOME/Library/Logs/PyCharm2025.2..."
if [ -d "$HOME/Library/Logs/PyCharm2025.2" ]; then
    rm -rf "$HOME/Library/Logs/PyCharm2025.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/PyCharm2025.2" ]; then
    rm -f "$HOME/Library/Logs/PyCharm2025.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/PyCharmCE2025.2
echo "Removing $HOME/Library/Logs/PyCharmCE2025.2..."
if [ -d "$HOME/Library/Logs/PyCharmCE2025.2" ]; then
    rm -rf "$HOME/Library/Logs/PyCharmCE2025.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/PyCharmCE2025.2" ]; then
    rm -f "$HOME/Library/Logs/PyCharmCE2025.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.jetbrains.pycharm.ce.plist
echo "Removing $HOME/Library/Preferences/com.jetbrains.pycharm.ce.plist..."
if [ -d "$HOME/Library/Preferences/com.jetbrains.pycharm.ce.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.jetbrains.pycharm.ce.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.jetbrains.pycharm.ce.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.jetbrains.pycharm.ce.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/jetbrains.jetprofile.asset.plist
echo "Removing $HOME/Library/Preferences/jetbrains.jetprofile.asset.plist..."
if [ -d "$HOME/Library/Preferences/jetbrains.jetprofile.asset.plist" ]; then
    rm -rf "$HOME/Library/Preferences/jetbrains.jetprofile.asset.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/jetbrains.jetprofile.asset.plist" ]; then
    rm -f "$HOME/Library/Preferences/jetbrains.jetprofile.asset.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/PyCharm2025.2
echo "Removing $HOME/Library/Preferences/PyCharm2025.2..."
if [ -d "$HOME/Library/Preferences/PyCharm2025.2" ]; then
    rm -rf "$HOME/Library/Preferences/PyCharm2025.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/PyCharm2025.2" ]; then
    rm -f "$HOME/Library/Preferences/PyCharm2025.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/PyCharmCE2025.2
echo "Removing $HOME/Library/Preferences/PyCharmCE2025.2..."
if [ -d "$HOME/Library/Preferences/PyCharmCE2025.2" ]; then
    rm -rf "$HOME/Library/Preferences/PyCharmCE2025.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/PyCharmCE2025.2" ]; then
    rm -f "$HOME/Library/Preferences/PyCharmCE2025.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.jetbrains.pycharm.ce.savedState
echo "Removing $HOME/Library/Saved Application State/com.jetbrains.pycharm.ce.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.jetbrains.pycharm.ce.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.jetbrains.pycharm.ce.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.jetbrains.pycharm.ce.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.jetbrains.pycharm.ce.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.jetbrains.pycharm.savedState
echo "Removing $HOME/Library/Saved Application State/com.jetbrains.pycharm.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.jetbrains.pycharm.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.jetbrains.pycharm.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.jetbrains.pycharm.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.jetbrains.pycharm.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
