#!/bin/bash
# Uninstall script for Raindrop.io
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Raindrop.io..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Raindrop.io if running..."
pkill -f "Raindrop.io" 2>/dev/null || true

# Remove /Applications/Raindrop.io.app
echo "Removing /Applications/Raindrop.io.app..."
if [ -d "/Applications/Raindrop.io.app" ]; then
    rm -rf "/Applications/Raindrop.io.app" 2>/dev/null || true
elif [ -f "/Applications/Raindrop.io.app" ]; then
    rm -f "/Applications/Raindrop.io.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/io.raindrop.macapp.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/io.raindrop.macapp.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/io.raindrop.macapp.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/io.raindrop.macapp.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/io.raindrop.macapp.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/io.raindrop.macapp.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Raindrop.io
echo "Removing $HOME/Library/Application Support/Raindrop.io..."
if [ -d "$HOME/Library/Application Support/Raindrop.io" ]; then
    rm -rf "$HOME/Library/Application Support/Raindrop.io" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Raindrop.io" ]; then
    rm -f "$HOME/Library/Application Support/Raindrop.io" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.Safari/Extensions/Raindrop.io.safariextension
echo "Removing $HOME/Library/Caches/com.apple.Safari/Extensions/Raindrop.io.safariextension..."
if [ -d "$HOME/Library/Caches/com.apple.Safari/Extensions/Raindrop.io.safariextension" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.Safari/Extensions/Raindrop.io.safariextension" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.Safari/Extensions/Raindrop.io.safariextension" ]; then
    rm -f "$HOME/Library/Caches/com.apple.Safari/Extensions/Raindrop.io.safariextension" 2>/dev/null || true
fi

# Remove $HOME/Library/Cookies/io.raindrop.mac.binarycookies
echo "Removing $HOME/Library/Cookies/io.raindrop.mac.binarycookies..."
if [ -d "$HOME/Library/Cookies/io.raindrop.mac.binarycookies" ]; then
    rm -rf "$HOME/Library/Cookies/io.raindrop.mac.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/Cookies/io.raindrop.mac.binarycookies" ]; then
    rm -f "$HOME/Library/Cookies/io.raindrop.mac.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/io.raindrop.mac.helper.plist
echo "Removing $HOME/Library/Preferences/io.raindrop.mac.helper.plist..."
if [ -d "$HOME/Library/Preferences/io.raindrop.mac.helper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/io.raindrop.mac.helper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/io.raindrop.mac.helper.plist" ]; then
    rm -f "$HOME/Library/Preferences/io.raindrop.mac.helper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/io.raindrop.mac.plist
echo "Removing $HOME/Library/Preferences/io.raindrop.mac.plist..."
if [ -d "$HOME/Library/Preferences/io.raindrop.mac.plist" ]; then
    rm -rf "$HOME/Library/Preferences/io.raindrop.mac.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/io.raindrop.mac.plist" ]; then
    rm -f "$HOME/Library/Preferences/io.raindrop.mac.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/io.raindrop.macapp.plist
echo "Removing $HOME/Library/Preferences/io.raindrop.macapp.plist..."
if [ -d "$HOME/Library/Preferences/io.raindrop.macapp.plist" ]; then
    rm -rf "$HOME/Library/Preferences/io.raindrop.macapp.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/io.raindrop.macapp.plist" ]; then
    rm -f "$HOME/Library/Preferences/io.raindrop.macapp.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Safari/Extensions/Raindrop.io.safariextz
echo "Removing $HOME/Library/Safari/Extensions/Raindrop.io.safariextz..."
if [ -d "$HOME/Library/Safari/Extensions/Raindrop.io.safariextz" ]; then
    rm -rf "$HOME/Library/Safari/Extensions/Raindrop.io.safariextz" 2>/dev/null || true
elif [ -f "$HOME/Library/Safari/Extensions/Raindrop.io.safariextz" ]; then
    rm -f "$HOME/Library/Safari/Extensions/Raindrop.io.safariextz" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/io.raindrop.mac.savedState
echo "Removing $HOME/Library/Saved Application State/io.raindrop.mac.savedState..."
if [ -d "$HOME/Library/Saved Application State/io.raindrop.mac.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/io.raindrop.mac.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/io.raindrop.mac.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/io.raindrop.mac.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
