#!/bin/bash
# Uninstall script for Remote Buddy
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Remote Buddy..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Remote Buddy if running..."
pkill -f "Remote Buddy" 2>/dev/null || true

# Remove /Applications/Remote Buddy.app
echo "Removing /Applications/Remote Buddy.app..."
if [ -d "/Applications/Remote Buddy.app" ]; then
    rm -rf "/Applications/Remote Buddy.app" 2>/dev/null || true
elif [ -f "/Applications/Remote Buddy.app" ]; then
    rm -f "/Applications/Remote Buddy.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Remote Buddy
echo "Removing $HOME/Library/Application Support/Remote Buddy..."
if [ -d "$HOME/Library/Application Support/Remote Buddy" ]; then
    rm -rf "$HOME/Library/Application Support/Remote Buddy" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Remote Buddy" ]; then
    rm -f "$HOME/Library/Application Support/Remote Buddy" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.helpd/Generated/com.iospirit.RemoteBuddy.help*
echo "Removing $HOME/Library/Caches/com.apple.helpd/Generated/com.iospirit.RemoteBuddy.help*..."
if [ -d "$HOME/Library/Caches/com.apple.helpd/Generated/com.iospirit.RemoteBuddy.help*" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.helpd/Generated/com.iospirit.RemoteBuddy.help*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.helpd/Generated/com.iospirit.RemoteBuddy.help*" ]; then
    rm -f "$HOME/Library/Caches/com.apple.helpd/Generated/com.iospirit.RemoteBuddy.help*" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/ByHost/com.iospirit.RemoteBuddy.*
echo "Removing $HOME/Library/Preferences/ByHost/com.iospirit.RemoteBuddy.*..."
if [ -d "$HOME/Library/Preferences/ByHost/com.iospirit.RemoteBuddy.*" ]; then
    rm -rf "$HOME/Library/Preferences/ByHost/com.iospirit.RemoteBuddy.*" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/ByHost/com.iospirit.RemoteBuddy.*" ]; then
    rm -f "$HOME/Library/Preferences/ByHost/com.iospirit.RemoteBuddy.*" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.iospirit.RemoteBuddy.plist
echo "Removing $HOME/Library/Preferences/com.iospirit.RemoteBuddy.plist..."
if [ -d "$HOME/Library/Preferences/com.iospirit.RemoteBuddy.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.iospirit.RemoteBuddy.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.iospirit.RemoteBuddy.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.iospirit.RemoteBuddy.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.iospirit.RemoteBuddy.savedState
echo "Removing $HOME/Library/Saved Application State/com.iospirit.RemoteBuddy.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.iospirit.RemoteBuddy.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.iospirit.RemoteBuddy.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.iospirit.RemoteBuddy.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.iospirit.RemoteBuddy.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
