#!/bin/bash
# Uninstall script for Ghost Browser
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Ghost Browser..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Ghost Browser if running..."
pkill -f "Ghost Browser" 2>/dev/null || true

# Remove /Applications/Ghost Browser.app
echo "Removing /Applications/Ghost Browser.app..."
if [ -d "/Applications/Ghost Browser.app" ]; then
    rm -rf "/Applications/Ghost Browser.app" 2>/dev/null || true
elif [ -f "/Applications/Ghost Browser.app" ]; then
    rm -f "/Applications/Ghost Browser.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/GhostBrowser
echo "Removing $HOME/Library/Application Support/GhostBrowser..."
if [ -d "$HOME/Library/Application Support/GhostBrowser" ]; then
    rm -rf "$HOME/Library/Application Support/GhostBrowser" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/GhostBrowser" ]; then
    rm -f "$HOME/Library/Application Support/GhostBrowser" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/GhostBrowser
echo "Removing $HOME/Library/Caches/GhostBrowser..."
if [ -d "$HOME/Library/Caches/GhostBrowser" ]; then
    rm -rf "$HOME/Library/Caches/GhostBrowser" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/GhostBrowser" ]; then
    rm -f "$HOME/Library/Caches/GhostBrowser" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.ghostbrowser.gb1.plist
echo "Removing $HOME/Library/Preferences/com.ghostbrowser.gb1.plist..."
if [ -d "$HOME/Library/Preferences/com.ghostbrowser.gb1.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.ghostbrowser.gb1.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.ghostbrowser.gb1.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.ghostbrowser.gb1.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.ghostbrowser.gb1.savedState
echo "Removing $HOME/Library/Saved Application State/com.ghostbrowser.gb1.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.ghostbrowser.gb1.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.ghostbrowser.gb1.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.ghostbrowser.gb1.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.ghostbrowser.gb1.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
