#!/bin/bash
# Uninstall script for Scratch
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Scratch..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Scratch if running..."
pkill -f "Scratch" 2>/dev/null || true

# Remove /Applications/Scratch 3.app
echo "Removing /Applications/Scratch 3.app..."
if [ -d "/Applications/Scratch 3.app" ]; then
    rm -rf "/Applications/Scratch 3.app" 2>/dev/null || true
elif [ -f "/Applications/Scratch 3.app" ]; then
    rm -f "/Applications/Scratch 3.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Scratch
echo "Removing $HOME/Library/Application Support/Scratch..."
if [ -d "$HOME/Library/Application Support/Scratch" ]; then
    rm -rf "$HOME/Library/Application Support/Scratch" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Scratch" ]; then
    rm -f "$HOME/Library/Application Support/Scratch" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/edu.mit.scratch.scratch-desktop.plist
echo "Removing $HOME/Library/Preferences/edu.mit.scratch.scratch-desktop.plist..."
if [ -d "$HOME/Library/Preferences/edu.mit.scratch.scratch-desktop.plist" ]; then
    rm -rf "$HOME/Library/Preferences/edu.mit.scratch.scratch-desktop.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/edu.mit.scratch.scratch-desktop.plist" ]; then
    rm -f "$HOME/Library/Preferences/edu.mit.scratch.scratch-desktop.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
