#!/bin/bash
# Uninstall script for Icon Composer
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Icon Composer..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Icon Composer if running..."
pkill -f "Icon Composer" 2>/dev/null || true

# Remove /Applications/Icon Composer.app
echo "Removing /Applications/Icon Composer.app..."
if [ -d "/Applications/Icon Composer.app" ]; then
    rm -rf "/Applications/Icon Composer.app" 2>/dev/null || true
elif [ -f "/Applications/Icon Composer.app" ]; then
    rm -f "/Applications/Icon Composer.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.apple.IconComposer
echo "Removing $HOME/Library/Application Scripts/com.apple.IconComposer..."
if [ -d "$HOME/Library/Application Scripts/com.apple.IconComposer" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.apple.IconComposer" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.apple.IconComposer" ]; then
    rm -f "$HOME/Library/Application Scripts/com.apple.IconComposer" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.apple.IconComposerQuickLookPreviewAppExtension
echo "Removing $HOME/Library/Application Scripts/com.apple.IconComposerQuickLookPreviewAppExtension..."
if [ -d "$HOME/Library/Application Scripts/com.apple.IconComposerQuickLookPreviewAppExtension" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.apple.IconComposerQuickLookPreviewAppExtension" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.apple.IconComposerQuickLookPreviewAppExtension" ]; then
    rm -f "$HOME/Library/Application Scripts/com.apple.IconComposerQuickLookPreviewAppExtension" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.apple.IconComposerThumbnailExtension
echo "Removing $HOME/Library/Application Scripts/com.apple.IconComposerThumbnailExtension..."
if [ -d "$HOME/Library/Application Scripts/com.apple.IconComposerThumbnailExtension" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.apple.IconComposerThumbnailExtension" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.apple.IconComposerThumbnailExtension" ]; then
    rm -f "$HOME/Library/Application Scripts/com.apple.IconComposerThumbnailExtension" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
