#!/bin/bash
# Uninstall script for Notion Mail
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Notion Mail..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Notion Mail if running..."
pkill -f "Notion Mail" 2>/dev/null || true

# Remove /Applications/Notion Mail.app
echo "Removing /Applications/Notion Mail.app..."
if [ -d "/Applications/Notion Mail.app" ]; then
    rm -rf "/Applications/Notion Mail.app" 2>/dev/null || true
elif [ -f "/Applications/Notion Mail.app" ]; then
    rm -f "/Applications/Notion Mail.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/notion.mail.id.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/notion.mail.id.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/notion.mail.id.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/notion.mail.id.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/notion.mail.id.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/notion.mail.id.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Notion Mail
echo "Removing $HOME/Library/Application Support/Notion Mail..."
if [ -d "$HOME/Library/Application Support/Notion Mail" ]; then
    rm -rf "$HOME/Library/Application Support/Notion Mail" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Notion Mail" ]; then
    rm -f "$HOME/Library/Application Support/Notion Mail" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Notion Mail
echo "Removing $HOME/Library/Logs/Notion Mail..."
if [ -d "$HOME/Library/Logs/Notion Mail" ]; then
    rm -rf "$HOME/Library/Logs/Notion Mail" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Notion Mail" ]; then
    rm -f "$HOME/Library/Logs/Notion Mail" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/notion.mail.id.*
echo "Removing $HOME/Library/Preferences/notion.mail.id.*..."
if [ -d "$HOME/Library/Preferences/notion.mail.id.*" ]; then
    rm -rf "$HOME/Library/Preferences/notion.mail.id.*" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/notion.mail.id.*" ]; then
    rm -f "$HOME/Library/Preferences/notion.mail.id.*" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/notion.mail.id.savedState
echo "Removing $HOME/Library/Saved Application State/notion.mail.id.savedState..."
if [ -d "$HOME/Library/Saved Application State/notion.mail.id.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/notion.mail.id.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/notion.mail.id.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/notion.mail.id.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
