#!/bin/bash
# Uninstall script for CloudyTabs
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling CloudyTabs..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping CloudyTabs if running..."
pkill -f "CloudyTabs" 2>/dev/null || true

# Remove /Applications/CloudyTabs.app
echo "Removing /Applications/CloudyTabs.app..."
if [ -d "/Applications/CloudyTabs.app" ]; then
    rm -rf "/Applications/CloudyTabs.app" 2>/dev/null || true
elif [ -f "/Applications/CloudyTabs.app" ]; then
    rm -f "/Applications/CloudyTabs.app" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
