#!/bin/bash
# Uninstall script for Hides
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Hides..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Hides if running..."
pkill -f "Hides" 2>/dev/null || true

# Remove /Applications/Hides.app
echo "Removing /Applications/Hides.app..."
if [ -d "/Applications/Hides.app" ]; then
    rm -rf "/Applications/Hides.app" 2>/dev/null || true
elif [ -f "/Applications/Hides.app" ]; then
    rm -f "/Applications/Hides.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.sweetpproductions.Hides
echo "Removing $HOME/Library/Containers/com.sweetpproductions.Hides..."
if [ -d "$HOME/Library/Containers/com.sweetpproductions.Hides" ]; then
    rm -rf "$HOME/Library/Containers/com.sweetpproductions.Hides" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.sweetpproductions.Hides" ]; then
    rm -f "$HOME/Library/Containers/com.sweetpproductions.Hides" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/*.com.sweetpproductions.Hides
echo "Removing $HOME/Library/Group Containers/*.com.sweetpproductions.Hides..."
if [ -d "$HOME/Library/Group Containers/*.com.sweetpproductions.Hides" ]; then
    rm -rf "$HOME/Library/Group Containers/*.com.sweetpproductions.Hides" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/*.com.sweetpproductions.Hides" ]; then
    rm -f "$HOME/Library/Group Containers/*.com.sweetpproductions.Hides" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
