#!/bin/bash
# Uninstall script for XQuartz
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling XQuartz..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping XQuartz if running..."
pkill -f "XQuartz" 2>/dev/null || true

# Unload service org.xquartz.privileged_startx
echo "Unloading service org.xquartz.privileged_startx..."
launchctl unload -w /Library/LaunchAgents/org.xquartz.privileged_startx.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/org.xquartz.privileged_startx.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/org.xquartz.privileged_startx.plist 2>/dev/null || true

# Remove $HOME/.Xauthority
echo "Removing $HOME/.Xauthority..."
if [ -d "$HOME/.Xauthority" ]; then
    rm -rf "$HOME/.Xauthority" 2>/dev/null || true
elif [ -f "$HOME/.Xauthority" ]; then
    rm -f "$HOME/.Xauthority" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/org.xquartz.x11.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/org.xquartz.x11.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/org.xquartz.x11.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/org.xquartz.x11.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/org.xquartz.x11.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/org.xquartz.x11.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/XQuartz
echo "Removing $HOME/Library/Application Support/XQuartz..."
if [ -d "$HOME/Library/Application Support/XQuartz" ]; then
    rm -rf "$HOME/Library/Application Support/XQuartz" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/XQuartz" ]; then
    rm -f "$HOME/Library/Application Support/XQuartz" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/org.xquartz.X11
echo "Removing $HOME/Library/Caches/org.xquartz.X11..."
if [ -d "$HOME/Library/Caches/org.xquartz.X11" ]; then
    rm -rf "$HOME/Library/Caches/org.xquartz.X11" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/org.xquartz.X11" ]; then
    rm -f "$HOME/Library/Caches/org.xquartz.X11" 2>/dev/null || true
fi

# Remove $HOME/Library/Cookies/org.xquartz.X11.binarycookies
echo "Removing $HOME/Library/Cookies/org.xquartz.X11.binarycookies..."
if [ -d "$HOME/Library/Cookies/org.xquartz.X11.binarycookies" ]; then
    rm -rf "$HOME/Library/Cookies/org.xquartz.X11.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/Cookies/org.xquartz.X11.binarycookies" ]; then
    rm -f "$HOME/Library/Cookies/org.xquartz.X11.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/org.xquartz.X11
echo "Removing $HOME/Library/HTTPStorages/org.xquartz.X11..."
if [ -d "$HOME/Library/HTTPStorages/org.xquartz.X11" ]; then
    rm -rf "$HOME/Library/HTTPStorages/org.xquartz.X11" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/org.xquartz.X11" ]; then
    rm -f "$HOME/Library/HTTPStorages/org.xquartz.X11" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/X11/org.xquartz.log
echo "Removing $HOME/Library/Logs/X11/org.xquartz.log..."
if [ -d "$HOME/Library/Logs/X11/org.xquartz.log" ]; then
    rm -rf "$HOME/Library/Logs/X11/org.xquartz.log" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/X11/org.xquartz.log" ]; then
    rm -f "$HOME/Library/Logs/X11/org.xquartz.log" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/X11/org.xquartz.log.old
echo "Removing $HOME/Library/Logs/X11/org.xquartz.log.old..."
if [ -d "$HOME/Library/Logs/X11/org.xquartz.log.old" ]; then
    rm -rf "$HOME/Library/Logs/X11/org.xquartz.log.old" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/X11/org.xquartz.log.old" ]; then
    rm -f "$HOME/Library/Logs/X11/org.xquartz.log.old" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/org.macosforge.xquartz.X11.plist
echo "Removing $HOME/Library/Preferences/org.macosforge.xquartz.X11.plist..."
if [ -d "$HOME/Library/Preferences/org.macosforge.xquartz.X11.plist" ]; then
    rm -rf "$HOME/Library/Preferences/org.macosforge.xquartz.X11.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/org.macosforge.xquartz.X11.plist" ]; then
    rm -f "$HOME/Library/Preferences/org.macosforge.xquartz.X11.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/org.xquartz.X11.plist
echo "Removing $HOME/Library/Preferences/org.xquartz.X11.plist..."
if [ -d "$HOME/Library/Preferences/org.xquartz.X11.plist" ]; then
    rm -rf "$HOME/Library/Preferences/org.xquartz.X11.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/org.xquartz.X11.plist" ]; then
    rm -f "$HOME/Library/Preferences/org.xquartz.X11.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/org.xquartz.X11.savedState
echo "Removing $HOME/Library/Saved Application State/org.xquartz.X11.savedState..."
if [ -d "$HOME/Library/Saved Application State/org.xquartz.X11.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/org.xquartz.X11.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/org.xquartz.X11.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/org.xquartz.X11.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/org.xquartz.X11
echo "Removing $HOME/Library/WebKit/org.xquartz.X11..."
if [ -d "$HOME/Library/WebKit/org.xquartz.X11" ]; then
    rm -rf "$HOME/Library/WebKit/org.xquartz.X11" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/org.xquartz.X11" ]; then
    rm -f "$HOME/Library/WebKit/org.xquartz.X11" 2>/dev/null || true
fi

# Remove $HOME/.fonts
echo "Removing $HOME/.fonts..."
if [ -d "$HOME/.fonts" ]; then
    rm -rf "$HOME/.fonts" 2>/dev/null || true
elif [ -f "$HOME/.fonts" ]; then
    rm -f "$HOME/.fonts" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/X11
echo "Removing $HOME/Library/Logs/X11..."
if [ -d "$HOME/Library/Logs/X11" ]; then
    rm -rf "$HOME/Library/Logs/X11" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/X11" ]; then
    rm -f "$HOME/Library/Logs/X11" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
