#!/bin/bash
# Uninstall script for Meld for macOS
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Meld for macOS..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Meld for macOS if running..."
pkill -f "Meld for macOS" 2>/dev/null || true

# Remove /Applications/Meld.app
echo "Removing /Applications/Meld.app..."
if [ -d "/Applications/Meld.app" ]; then
    rm -rf "/Applications/Meld.app" 2>/dev/null || true
elif [ -f "/Applications/Meld.app" ]; then
    rm -f "/Applications/Meld.app" 2>/dev/null || true
fi

# Remove $HOME/.local/share/meld
echo "Removing $HOME/.local/share/meld..."
if [ -d "$HOME/.local/share/meld" ]; then
    rm -rf "$HOME/.local/share/meld" 2>/dev/null || true
elif [ -f "$HOME/.local/share/meld" ]; then
    rm -f "$HOME/.local/share/meld" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/org.gnome.Meld
echo "Removing $HOME/Library/Application Support/org.gnome.Meld..."
if [ -d "$HOME/Library/Application Support/org.gnome.Meld" ]; then
    rm -rf "$HOME/Library/Application Support/org.gnome.Meld" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/org.gnome.Meld" ]; then
    rm -f "$HOME/Library/Application Support/org.gnome.Meld" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/org.gnome.Meld
echo "Removing $HOME/Library/Caches/org.gnome.Meld..."
if [ -d "$HOME/Library/Caches/org.gnome.Meld" ]; then
    rm -rf "$HOME/Library/Caches/org.gnome.Meld" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/org.gnome.Meld" ]; then
    rm -f "$HOME/Library/Caches/org.gnome.Meld" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/org.gnome.Meld.plist
echo "Removing $HOME/Library/Preferences/org.gnome.Meld.plist..."
if [ -d "$HOME/Library/Preferences/org.gnome.Meld.plist" ]; then
    rm -rf "$HOME/Library/Preferences/org.gnome.Meld.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/org.gnome.Meld.plist" ]; then
    rm -f "$HOME/Library/Preferences/org.gnome.Meld.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/org.gnome.Meld.savedState
echo "Removing $HOME/Library/Saved Application State/org.gnome.Meld.savedState..."
if [ -d "$HOME/Library/Saved Application State/org.gnome.Meld.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/org.gnome.Meld.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/org.gnome.Meld.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/org.gnome.Meld.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
