#!/bin/bash
# Uninstall script for Unclutter
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Unclutter..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Unclutter if running..."
pkill -f "Unclutter" 2>/dev/null || true

# Remove /Applications/Unclutter.app
echo "Removing /Applications/Unclutter.app..."
if [ -d "/Applications/Unclutter.app" ]; then
    rm -rf "/Applications/Unclutter.app" 2>/dev/null || true
elif [ -f "/Applications/Unclutter.app" ]; then
    rm -f "/Applications/Unclutter.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/*.group.com.softwareambience.Unclutter
echo "Removing $HOME/Library/Application Scripts/*.group.com.softwareambience.Unclutter..."
if [ -d "$HOME/Library/Application Scripts/*.group.com.softwareambience.Unclutter" ]; then
    rm -rf "$HOME/Library/Application Scripts/*.group.com.softwareambience.Unclutter" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/*.group.com.softwareambience.Unclutter" ]; then
    rm -f "$HOME/Library/Application Scripts/*.group.com.softwareambience.Unclutter" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.softwareambience.unclutter.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.softwareambience.unclutter.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.softwareambience.unclutter.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.softwareambience.unclutter.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.softwareambience.unclutter.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.softwareambience.unclutter.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Unclutter
echo "Removing $HOME/Library/Application Support/Unclutter..."
if [ -d "$HOME/Library/Application Support/Unclutter" ]; then
    rm -rf "$HOME/Library/Application Support/Unclutter" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Unclutter" ]; then
    rm -f "$HOME/Library/Application Support/Unclutter" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.softwareambience.Unclutter
echo "Removing $HOME/Library/Caches/com.softwareambience.Unclutter..."
if [ -d "$HOME/Library/Caches/com.softwareambience.Unclutter" ]; then
    rm -rf "$HOME/Library/Caches/com.softwareambience.Unclutter" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.softwareambience.Unclutter" ]; then
    rm -f "$HOME/Library/Caches/com.softwareambience.Unclutter" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.softwareambience.Unclutter
echo "Removing $HOME/Library/Containers/com.softwareambience.Unclutter..."
if [ -d "$HOME/Library/Containers/com.softwareambience.Unclutter" ]; then
    rm -rf "$HOME/Library/Containers/com.softwareambience.Unclutter" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.softwareambience.Unclutter" ]; then
    rm -f "$HOME/Library/Containers/com.softwareambience.Unclutter" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/*.group.com.softwareambience.Unclutter
echo "Removing $HOME/Library/Group Containers/*.group.com.softwareambience.Unclutter..."
if [ -d "$HOME/Library/Group Containers/*.group.com.softwareambience.Unclutter" ]; then
    rm -rf "$HOME/Library/Group Containers/*.group.com.softwareambience.Unclutter" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/*.group.com.softwareambience.Unclutter" ]; then
    rm -f "$HOME/Library/Group Containers/*.group.com.softwareambience.Unclutter" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.softwareambience.Unclutter
echo "Removing $HOME/Library/HTTPStorages/com.softwareambience.Unclutter..."
if [ -d "$HOME/Library/HTTPStorages/com.softwareambience.Unclutter" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.softwareambience.Unclutter" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.softwareambience.Unclutter" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.softwareambience.Unclutter" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.softwareambience.Unclutter.plist
echo "Removing $HOME/Library/Preferences/com.softwareambience.Unclutter.plist..."
if [ -d "$HOME/Library/Preferences/com.softwareambience.Unclutter.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.softwareambience.Unclutter.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.softwareambience.Unclutter.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.softwareambience.Unclutter.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
