#!/bin/bash
# Uninstall script for .NET SDK
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling .NET SDK..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping .NET SDK if running..."
pkill -f ".NET SDK" 2>/dev/null || true

# Remove /usr/local/bin//usr/local/share/dotnet/dotnet
echo "Removing /usr/local/bin//usr/local/share/dotnet/dotnet..."
if [ -d "/usr/local/bin//usr/local/share/dotnet/dotnet" ]; then
    rm -rf "/usr/local/bin//usr/local/share/dotnet/dotnet" 2>/dev/null || true
elif [ -f "/usr/local/bin//usr/local/share/dotnet/dotnet" ]; then
    rm -f "/usr/local/bin//usr/local/share/dotnet/dotnet" 2>/dev/null || true
fi

# Remove /usr/local/bin//usr/local/share/dotnet/dnx
echo "Removing /usr/local/bin//usr/local/share/dotnet/dnx..."
if [ -d "/usr/local/bin//usr/local/share/dotnet/dnx" ]; then
    rm -rf "/usr/local/bin//usr/local/share/dotnet/dnx" 2>/dev/null || true
elif [ -f "/usr/local/bin//usr/local/share/dotnet/dnx" ]; then
    rm -f "/usr/local/bin//usr/local/share/dotnet/dnx" 2>/dev/null || true
fi

# Remove $HOME/.dotnet
echo "Removing $HOME/.dotnet..."
if [ -d "$HOME/.dotnet" ]; then
    rm -rf "$HOME/.dotnet" 2>/dev/null || true
elif [ -f "$HOME/.dotnet" ]; then
    rm -f "$HOME/.dotnet" 2>/dev/null || true
fi

# Remove $HOME/.nuget
echo "Removing $HOME/.nuget..."
if [ -d "$HOME/.nuget" ]; then
    rm -rf "$HOME/.nuget" 2>/dev/null || true
elif [ -f "$HOME/.nuget" ]; then
    rm -f "$HOME/.nuget" 2>/dev/null || true
fi

# Remove /etc/paths.d/dotnet
echo "Removing /etc/paths.d/dotnet..."
if [ -d "/etc/paths.d/dotnet" ]; then
    rm -rf "/etc/paths.d/dotnet" 2>/dev/null || true
elif [ -f "/etc/paths.d/dotnet" ]; then
    rm -f "/etc/paths.d/dotnet" 2>/dev/null || true
fi

# Remove /etc/paths.d/dotnet-cli-tools
echo "Removing /etc/paths.d/dotnet-cli-tools..."
if [ -d "/etc/paths.d/dotnet-cli-tools" ]; then
    rm -rf "/etc/paths.d/dotnet-cli-tools" 2>/dev/null || true
elif [ -f "/etc/paths.d/dotnet-cli-tools" ]; then
    rm -f "/etc/paths.d/dotnet-cli-tools" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
