#!/bin/bash
# Uninstall script for Affinity Publisher 2
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Affinity Publisher 2..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Affinity Publisher 2 if running..."
pkill -f "Affinity Publisher 2" 2>/dev/null || true

# Remove /Applications/Affinity Publisher 2.app
echo "Removing /Applications/Affinity Publisher 2.app..."
if [ -d "/Applications/Affinity Publisher 2.app" ]; then
    rm -rf "/Applications/Affinity Publisher 2.app" 2>/dev/null || true
elif [ -f "/Applications/Affinity Publisher 2.app" ]; then
    rm -f "/Applications/Affinity Publisher 2.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Affinity Publisher 2
echo "Removing $HOME/Library/Application Support/Affinity Publisher 2..."
if [ -d "$HOME/Library/Application Support/Affinity Publisher 2" ]; then
    rm -rf "$HOME/Library/Application Support/Affinity Publisher 2" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Affinity Publisher 2" ]; then
    rm -f "$HOME/Library/Application Support/Affinity Publisher 2" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.seriflabs.affinitypublisher2
echo "Removing $HOME/Library/Caches/com.seriflabs.affinitypublisher2..."
if [ -d "$HOME/Library/Caches/com.seriflabs.affinitypublisher2" ]; then
    rm -rf "$HOME/Library/Caches/com.seriflabs.affinitypublisher2" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.seriflabs.affinitypublisher2" ]; then
    rm -f "$HOME/Library/Caches/com.seriflabs.affinitypublisher2" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.seriflabs.affinitypublisher2
echo "Removing $HOME/Library/HTTPStorages/com.seriflabs.affinitypublisher2..."
if [ -d "$HOME/Library/HTTPStorages/com.seriflabs.affinitypublisher2" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.seriflabs.affinitypublisher2" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.seriflabs.affinitypublisher2" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.seriflabs.affinitypublisher2" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.seriflabs.affinitypublisher2.plist
echo "Removing $HOME/Library/Preferences/com.seriflabs.affinitypublisher2.plist..."
if [ -d "$HOME/Library/Preferences/com.seriflabs.affinitypublisher2.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.seriflabs.affinitypublisher2.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.seriflabs.affinitypublisher2.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.seriflabs.affinitypublisher2.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.seriflabs.affinitypublisher2.savedState
echo "Removing $HOME/Library/Saved Application State/com.seriflabs.affinitypublisher2.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.seriflabs.affinitypublisher2.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.seriflabs.affinitypublisher2.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.seriflabs.affinitypublisher2.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.seriflabs.affinitypublisher2.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.seriflabs.affinitypublisher2
echo "Removing $HOME/Library/WebKit/com.seriflabs.affinitypublisher2..."
if [ -d "$HOME/Library/WebKit/com.seriflabs.affinitypublisher2" ]; then
    rm -rf "$HOME/Library/WebKit/com.seriflabs.affinitypublisher2" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.seriflabs.affinitypublisher2" ]; then
    rm -f "$HOME/Library/WebKit/com.seriflabs.affinitypublisher2" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
