#!/bin/bash
# Uninstall script for Microsoft Outlook
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Microsoft Outlook..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Microsoft Outlook if running..."
pkill -f "Microsoft Outlook" 2>/dev/null || true

# Unload service com.microsoft.office.licensingV2.helper
echo "Unloading service com.microsoft.office.licensingV2.helper..."
launchctl unload -w /Library/LaunchAgents/com.microsoft.office.licensingV2.helper.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.microsoft.office.licensingV2.helper.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.microsoft.office.licensingV2.helper.plist 2>/dev/null || true

# Kill application with bundle ID com.microsoft.autoupdate2 if running
echo "Stopping application with bundle ID com.microsoft.autoupdate2 if running..."
killall -9 "com.microsoft.autoupdate2" 2>/dev/null || true

# Remove $HOME/Library/Application Scripts/com.microsoft.Outlook
echo "Removing $HOME/Library/Application Scripts/com.microsoft.Outlook..."
if [ -d "$HOME/Library/Application Scripts/com.microsoft.Outlook" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.microsoft.Outlook" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.microsoft.Outlook" ]; then
    rm -f "$HOME/Library/Application Scripts/com.microsoft.Outlook" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.microsoft.Outlook
echo "Removing $HOME/Library/Containers/com.microsoft.Outlook..."
if [ -d "$HOME/Library/Containers/com.microsoft.Outlook" ]; then
    rm -rf "$HOME/Library/Containers/com.microsoft.Outlook" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.microsoft.Outlook" ]; then
    rm -f "$HOME/Library/Containers/com.microsoft.Outlook" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
