#!/bin/bash
# Uninstall script for Ice
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Ice..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Ice if running..."
pkill -f "Ice" 2>/dev/null || true

# Kill application with bundle ID com.jordanbaird.Ice if running
echo "Stopping application with bundle ID com.jordanbaird.Ice if running..."
killall -9 "com.jordanbaird.Ice" 2>/dev/null || true

# Remove /Applications/Ice.app
echo "Removing /Applications/Ice.app..."
if [ -d "/Applications/Ice.app" ]; then
    rm -rf "/Applications/Ice.app" 2>/dev/null || true
elif [ -f "/Applications/Ice.app" ]; then
    rm -f "/Applications/Ice.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.jordanbaird.Ice
echo "Removing $HOME/Library/Caches/com.jordanbaird.Ice..."
if [ -d "$HOME/Library/Caches/com.jordanbaird.Ice" ]; then
    rm -rf "$HOME/Library/Caches/com.jordanbaird.Ice" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.jordanbaird.Ice" ]; then
    rm -f "$HOME/Library/Caches/com.jordanbaird.Ice" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.jordanbaird.Ice
echo "Removing $HOME/Library/HTTPStorages/com.jordanbaird.Ice..."
if [ -d "$HOME/Library/HTTPStorages/com.jordanbaird.Ice" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.jordanbaird.Ice" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.jordanbaird.Ice" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.jordanbaird.Ice" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.jordanbaird.Ice.plist
echo "Removing $HOME/Library/Preferences/com.jordanbaird.Ice.plist..."
if [ -d "$HOME/Library/Preferences/com.jordanbaird.Ice.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.jordanbaird.Ice.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.jordanbaird.Ice.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.jordanbaird.Ice.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.jordanbaird.Ice
echo "Removing $HOME/Library/WebKit/com.jordanbaird.Ice..."
if [ -d "$HOME/Library/WebKit/com.jordanbaird.Ice" ]; then
    rm -rf "$HOME/Library/WebKit/com.jordanbaird.Ice" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.jordanbaird.Ice" ]; then
    rm -f "$HOME/Library/WebKit/com.jordanbaird.Ice" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
