#!/bin/bash
# Uninstall script for AppFlowy
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling AppFlowy..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping AppFlowy if running..."
pkill -f "AppFlowy" 2>/dev/null || true

# Remove /Applications/AppFlowy-arm64.app
echo "Removing /Applications/AppFlowy-arm64.app..."
if [ -d "/Applications/AppFlowy-arm64.app" ]; then
    rm -rf "/Applications/AppFlowy-arm64.app" 2>/dev/null || true
elif [ -f "/Applications/AppFlowy-arm64.app" ]; then
    rm -f "/Applications/AppFlowy-arm64.app" 2>/dev/null || true
fi

# Remove /Applications/{'target': 'AppFlowy.app'}
echo "Removing /Applications/{'target': 'AppFlowy.app'}..."
if [ -d "/Applications/{'target': 'AppFlowy.app'}" ]; then
    rm -rf "/Applications/{'target': 'AppFlowy.app'}" 2>/dev/null || true
elif [ -f "/Applications/{'target': 'AppFlowy.app'}" ]; then
    rm -f "/Applications/{'target': 'AppFlowy.app'}" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.appflowy.macos
echo "Removing $HOME/Library/Application Scripts/com.appflowy.macos..."
if [ -d "$HOME/Library/Application Scripts/com.appflowy.macos" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.appflowy.macos" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.appflowy.macos" ]; then
    rm -f "$HOME/Library/Application Scripts/com.appflowy.macos" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.appflowy.macos
echo "Removing $HOME/Library/Containers/com.appflowy.macos..."
if [ -d "$HOME/Library/Containers/com.appflowy.macos" ]; then
    rm -rf "$HOME/Library/Containers/com.appflowy.macos" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.appflowy.macos" ]; then
    rm -f "$HOME/Library/Containers/com.appflowy.macos" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
