#!/bin/bash
# Uninstall script for Screens
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Screens..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Screens if running..."
pkill -f "Screens" 2>/dev/null || true

# Unload service com.edovia.screens.launcher
echo "Unloading service com.edovia.screens.launcher..."
launchctl unload -w /Library/LaunchAgents/com.edovia.screens.launcher.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.edovia.screens.launcher.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.edovia.screens.launcher.plist 2>/dev/null || true

# Kill application with bundle ID com.edovia.screens4.mac if running
echo "Stopping application with bundle ID com.edovia.screens4.mac if running..."
killall -9 "com.edovia.screens4.mac" 2>/dev/null || true

# Remove /Applications/Screens 4.app
echo "Removing /Applications/Screens 4.app..."
if [ -d "/Applications/Screens 4.app" ]; then
    rm -rf "/Applications/Screens 4.app" 2>/dev/null || true
elif [ -f "/Applications/Screens 4.app" ]; then
    rm -f "/Applications/Screens 4.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.edovia.screens4.mac
echo "Removing $HOME/Library/Application Scripts/com.edovia.screens4.mac..."
if [ -d "$HOME/Library/Application Scripts/com.edovia.screens4.mac" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.edovia.screens4.mac" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.edovia.screens4.mac" ]; then
    rm -f "$HOME/Library/Application Scripts/com.edovia.screens4.mac" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.edovia.screens.launcher
echo "Removing $HOME/Library/Application Scripts/com.edovia.screens.launcher..."
if [ -d "$HOME/Library/Application Scripts/com.edovia.screens.launcher" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.edovia.screens.launcher" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.edovia.screens.launcher" ]; then
    rm -f "$HOME/Library/Application Scripts/com.edovia.screens.launcher" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.edovia.screens4.mac
echo "Removing $HOME/Library/Containers/com.edovia.screens4.mac..."
if [ -d "$HOME/Library/Containers/com.edovia.screens4.mac" ]; then
    rm -rf "$HOME/Library/Containers/com.edovia.screens4.mac" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.edovia.screens4.mac" ]; then
    rm -f "$HOME/Library/Containers/com.edovia.screens4.mac" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.edovia.screens.launcher
echo "Removing $HOME/Library/Containers/com.edovia.screens.launcher..."
if [ -d "$HOME/Library/Containers/com.edovia.screens.launcher" ]; then
    rm -rf "$HOME/Library/Containers/com.edovia.screens.launcher" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.edovia.screens.launcher" ]; then
    rm -f "$HOME/Library/Containers/com.edovia.screens.launcher" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Screens
echo "Removing $HOME/Library/Logs/Screens..."
if [ -d "$HOME/Library/Logs/Screens" ]; then
    rm -rf "$HOME/Library/Logs/Screens" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Screens" ]; then
    rm -f "$HOME/Library/Logs/Screens" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.edovia.screens4.mac.plist
echo "Removing $HOME/Library/Preferences/com.edovia.screens4.mac.plist..."
if [ -d "$HOME/Library/Preferences/com.edovia.screens4.mac.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.edovia.screens4.mac.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.edovia.screens4.mac.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.edovia.screens4.mac.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
