#!/bin/bash
# Uninstall script for SimplySign Desktop
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling SimplySign Desktop..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping SimplySign Desktop if running..."
pkill -f "SimplySign Desktop" 2>/dev/null || true

# Unload service pl.ads.SimplySignDesktop
echo "Unloading service pl.ads.SimplySignDesktop..."
launchctl unload -w /Library/LaunchAgents/pl.ads.SimplySignDesktop.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/pl.ads.SimplySignDesktop.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/pl.ads.SimplySignDesktop.plist 2>/dev/null || true

# Kill application with bundle ID pl.ads.SimplySign-Desktop if running
echo "Stopping application with bundle ID pl.ads.SimplySign-Desktop if running..."
killall -9 "pl.ads.SimplySign-Desktop" 2>/dev/null || true

# Kill application with bundle ID pl.unizeto.pcja.SmartSign if running
echo "Stopping application with bundle ID pl.unizeto.pcja.SmartSign if running..."
killall -9 "pl.unizeto.pcja.SmartSign" 2>/dev/null || true

# Remove $HOME/Library/LaunchAgents/pl.ads.SimplySignDesktop.plist
echo "Removing $HOME/Library/LaunchAgents/pl.ads.SimplySignDesktop.plist..."
if [ -d "$HOME/Library/LaunchAgents/pl.ads.SimplySignDesktop.plist" ]; then
    rm -rf "$HOME/Library/LaunchAgents/pl.ads.SimplySignDesktop.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/LaunchAgents/pl.ads.SimplySignDesktop.plist" ]; then
    rm -f "$HOME/Library/LaunchAgents/pl.ads.SimplySignDesktop.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/pl.ads.SimplySign-Desktop.plist
echo "Removing $HOME/Library/Preferences/pl.ads.SimplySign-Desktop.plist..."
if [ -d "$HOME/Library/Preferences/pl.ads.SimplySign-Desktop.plist" ]; then
    rm -rf "$HOME/Library/Preferences/pl.ads.SimplySign-Desktop.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/pl.ads.SimplySign-Desktop.plist" ]; then
    rm -f "$HOME/Library/Preferences/pl.ads.SimplySign-Desktop.plist" 2>/dev/null || true
fi

# Remove $HOME/SimplySignDesktop.xml
echo "Removing $HOME/SimplySignDesktop.xml..."
if [ -d "$HOME/SimplySignDesktop.xml" ]; then
    rm -rf "$HOME/SimplySignDesktop.xml" 2>/dev/null || true
elif [ -f "$HOME/SimplySignDesktop.xml" ]; then
    rm -f "$HOME/SimplySignDesktop.xml" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
