#!/bin/bash
# Uninstall script for MailMate
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling MailMate..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping MailMate if running..."
pkill -f "MailMate" 2>/dev/null || true

# Remove /Applications/MailMate.app
echo "Removing /Applications/MailMate.app..."
if [ -d "/Applications/MailMate.app" ]; then
    rm -rf "/Applications/MailMate.app" 2>/dev/null || true
elif [ -f "/Applications/MailMate.app" ]; then
    rm -f "/Applications/MailMate.app" 2>/dev/null || true
fi

# Remove binary /Applications/MailMate.app/MailMate.app/Contents/Resources/emate
echo "Removing binary /Applications/MailMate.app/MailMate.app/Contents/Resources/emate..."
if [ -f "/Applications/MailMate.app/MailMate.app/Contents/Resources/emate" ]; then
    rm -f "/Applications/MailMate.app/MailMate.app/Contents/Resources/emate" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.freron.MailMate.MailMateShare
echo "Removing $HOME/Library/Application Scripts/com.freron.MailMate.MailMateShare..."
if [ -d "$HOME/Library/Application Scripts/com.freron.MailMate.MailMateShare" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.freron.MailMate.MailMateShare" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.freron.MailMate.MailMateShare" ]; then
    rm -f "$HOME/Library/Application Scripts/com.freron.MailMate.MailMateShare" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/MailMate
echo "Removing $HOME/Library/Application Support/MailMate..."
if [ -d "$HOME/Library/Application Support/MailMate" ]; then
    rm -rf "$HOME/Library/Application Support/MailMate" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/MailMate" ]; then
    rm -f "$HOME/Library/Application Support/MailMate" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.helpd/Generated/MailMate Help*1.13.2
echo "Removing $HOME/Library/Caches/com.apple.helpd/Generated/MailMate Help*1.13.2..."
if [ -d "$HOME/Library/Caches/com.apple.helpd/Generated/MailMate Help*1.13.2" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.helpd/Generated/MailMate Help*1.13.2" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.helpd/Generated/MailMate Help*1.13.2" ]; then
    rm -f "$HOME/Library/Caches/com.apple.helpd/Generated/MailMate Help*1.13.2" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.freron.MailMate
echo "Removing $HOME/Library/Caches/com.freron.MailMate..."
if [ -d "$HOME/Library/Caches/com.freron.MailMate" ]; then
    rm -rf "$HOME/Library/Caches/com.freron.MailMate" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.freron.MailMate" ]; then
    rm -f "$HOME/Library/Caches/com.freron.MailMate" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.freron.MailMate.MailMateShare
echo "Removing $HOME/Library/Containers/com.freron.MailMate.MailMateShare..."
if [ -d "$HOME/Library/Containers/com.freron.MailMate.MailMateShare" ]; then
    rm -rf "$HOME/Library/Containers/com.freron.MailMate.MailMateShare" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.freron.MailMate.MailMateShare" ]; then
    rm -f "$HOME/Library/Containers/com.freron.MailMate.MailMateShare" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.freron.MailMate.plist
echo "Removing $HOME/Library/Preferences/com.freron.MailMate.plist..."
if [ -d "$HOME/Library/Preferences/com.freron.MailMate.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.freron.MailMate.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.freron.MailMate.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.freron.MailMate.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.freron.MailMate.savedState
echo "Removing $HOME/Library/Saved Application State/com.freron.MailMate.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.freron.MailMate.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.freron.MailMate.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.freron.MailMate.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.freron.MailMate.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
