#!/bin/bash
# Uninstall script for IBM Aspera Connect
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling IBM Aspera Connect..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping IBM Aspera Connect if running..."
pkill -f "IBM Aspera Connect" 2>/dev/null || true

# Remove $HOME/Library/Application Scripts/com.aspera.connect.SafariExtension
echo "Removing $HOME/Library/Application Scripts/com.aspera.connect.SafariExtension..."
if [ -d "$HOME/Library/Application Scripts/com.aspera.connect.SafariExtension" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.aspera.connect.SafariExtension" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.aspera.connect.SafariExtension" ]; then
    rm -f "$HOME/Library/Application Scripts/com.aspera.connect.SafariExtension" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.aspera.drive.SendToExtension
echo "Removing $HOME/Library/Application Scripts/com.aspera.drive.SendToExtension..."
if [ -d "$HOME/Library/Application Scripts/com.aspera.drive.SendToExtension" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.aspera.drive.SendToExtension" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.aspera.drive.SendToExtension" ]; then
    rm -f "$HOME/Library/Application Scripts/com.aspera.drive.SendToExtension" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.aspera.connect.SafariExtension
echo "Removing $HOME/Library/Containers/com.aspera.connect.SafariExtension..."
if [ -d "$HOME/Library/Containers/com.aspera.connect.SafariExtension" ]; then
    rm -rf "$HOME/Library/Containers/com.aspera.connect.SafariExtension" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.aspera.connect.SafariExtension" ]; then
    rm -f "$HOME/Library/Containers/com.aspera.connect.SafariExtension" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.aspera.drive.SendToExtension
echo "Removing $HOME/Library/Containers/com.aspera.drive.SendToExtension..."
if [ -d "$HOME/Library/Containers/com.aspera.drive.SendToExtension" ]; then
    rm -rf "$HOME/Library/Containers/com.aspera.drive.SendToExtension" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.aspera.drive.SendToExtension" ]; then
    rm -f "$HOME/Library/Containers/com.aspera.drive.SendToExtension" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/group.com.aspera.connect
echo "Removing $HOME/Library/Group Containers/group.com.aspera.connect..."
if [ -d "$HOME/Library/Group Containers/group.com.aspera.connect" ]; then
    rm -rf "$HOME/Library/Group Containers/group.com.aspera.connect" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/group.com.aspera.connect" ]; then
    rm -f "$HOME/Library/Group Containers/group.com.aspera.connect" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Aspera_Connect
echo "Removing $HOME/Library/Logs/Aspera_Connect..."
if [ -d "$HOME/Library/Logs/Aspera_Connect" ]; then
    rm -rf "$HOME/Library/Logs/Aspera_Connect" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Aspera_Connect" ]; then
    rm -f "$HOME/Library/Logs/Aspera_Connect" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.aspera.connect.plist
echo "Removing $HOME/Library/Preferences/com.aspera.connect.plist..."
if [ -d "$HOME/Library/Preferences/com.aspera.connect.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.aspera.connect.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.aspera.connect.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.aspera.connect.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.aspera.connect.savedState
echo "Removing $HOME/Library/Saved Application State/com.aspera.connect.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.aspera.connect.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.aspera.connect.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.aspera.connect.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.aspera.connect.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
