#!/bin/bash
# Uninstall script for LinearMouse
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling LinearMouse..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping LinearMouse if running..."
pkill -f "LinearMouse" 2>/dev/null || true

# Kill application with bundle ID com.lujjjh.LinearMouse if running
echo "Stopping application with bundle ID com.lujjjh.LinearMouse if running..."
killall -9 "com.lujjjh.LinearMouse" 2>/dev/null || true

# Remove /Applications/LinearMouse.app
echo "Removing /Applications/LinearMouse.app..."
if [ -d "/Applications/LinearMouse.app" ]; then
    rm -rf "/Applications/LinearMouse.app" 2>/dev/null || true
elif [ -f "/Applications/LinearMouse.app" ]; then
    rm -f "/Applications/LinearMouse.app" 2>/dev/null || true
fi

# Remove $HOME/.config/linearmouse
echo "Removing $HOME/.config/linearmouse..."
if [ -d "$HOME/.config/linearmouse" ]; then
    rm -rf "$HOME/.config/linearmouse" 2>/dev/null || true
elif [ -f "$HOME/.config/linearmouse" ]; then
    rm -f "$HOME/.config/linearmouse" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.lujjjh.LinearMouse.plist
echo "Removing $HOME/Library/Preferences/com.lujjjh.LinearMouse.plist..."
if [ -d "$HOME/Library/Preferences/com.lujjjh.LinearMouse.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.lujjjh.LinearMouse.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.lujjjh.LinearMouse.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.lujjjh.LinearMouse.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
