#!/bin/bash
# Uninstall script for Wave Terminal
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Wave Terminal..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Wave Terminal if running..."
pkill -f "Wave Terminal" 2>/dev/null || true

# Remove /Applications/Wave.app
echo "Removing /Applications/Wave.app..."
if [ -d "/Applications/Wave.app" ]; then
    rm -rf "/Applications/Wave.app" 2>/dev/null || true
elif [ -f "/Applications/Wave.app" ]; then
    rm -f "/Applications/Wave.app" 2>/dev/null || true
fi

# Remove $HOME/.waveterm
echo "Removing $HOME/.waveterm..."
if [ -d "$HOME/.waveterm" ]; then
    rm -rf "$HOME/.waveterm" 2>/dev/null || true
elif [ -f "$HOME/.waveterm" ]; then
    rm -f "$HOME/.waveterm" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
