#!/bin/bash
# Uninstall script for Sentinel
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Sentinel..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Sentinel if running..."
pkill -f "Sentinel" 2>/dev/null || true

# Remove /usr/local/bin/sentinel
echo "Removing /usr/local/bin/sentinel..."
if [ -d "/usr/local/bin/sentinel" ]; then
    rm -rf "/usr/local/bin/sentinel" 2>/dev/null || true
elif [ -f "/usr/local/bin/sentinel" ]; then
    rm -f "/usr/local/bin/sentinel" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
