#!/bin/bash
# Uninstall script for Charles
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Charles..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Charles if running..."
pkill -f "Charles" 2>/dev/null || true

# Unload service com.xk72.Charles.ProxyHelper
echo "Unloading service com.xk72.Charles.ProxyHelper..."
launchctl unload -w /Library/LaunchAgents/com.xk72.Charles.ProxyHelper.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.xk72.Charles.ProxyHelper.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.xk72.Charles.ProxyHelper.plist 2>/dev/null || true

# Kill application with bundle ID com.xk72.Charles if running
echo "Stopping application with bundle ID com.xk72.Charles if running..."
killall -9 "com.xk72.Charles" 2>/dev/null || true

# Remove /Applications/Charles.app
echo "Removing /Applications/Charles.app..."
if [ -d "/Applications/Charles.app" ]; then
    rm -rf "/Applications/Charles.app" 2>/dev/null || true
elif [ -f "/Applications/Charles.app" ]; then
    rm -f "/Applications/Charles.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Charles
echo "Removing $HOME/Library/Application Support/Charles..."
if [ -d "$HOME/Library/Application Support/Charles" ]; then
    rm -rf "$HOME/Library/Application Support/Charles" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Charles" ]; then
    rm -f "$HOME/Library/Application Support/Charles" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.xk72.charles.config
echo "Removing $HOME/Library/Preferences/com.xk72.charles.config..."
if [ -d "$HOME/Library/Preferences/com.xk72.charles.config" ]; then
    rm -rf "$HOME/Library/Preferences/com.xk72.charles.config" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.xk72.charles.config" ]; then
    rm -f "$HOME/Library/Preferences/com.xk72.charles.config" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.xk72.Charles.plist
echo "Removing $HOME/Library/Preferences/com.xk72.Charles.plist..."
if [ -d "$HOME/Library/Preferences/com.xk72.Charles.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.xk72.Charles.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.xk72.Charles.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.xk72.Charles.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.xk72.Charles.savedState
echo "Removing $HOME/Library/Saved Application State/com.xk72.Charles.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.xk72.Charles.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.xk72.Charles.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.xk72.Charles.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.xk72.Charles.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
