#!/bin/bash
# Uninstall script for Switch Audio Converter
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Switch Audio Converter..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Switch Audio Converter if running..."
pkill -f "Switch Audio Converter" 2>/dev/null || true

# Remove /Applications/Switch.app
echo "Removing /Applications/Switch.app..."
if [ -d "/Applications/Switch.app" ]; then
    rm -rf "/Applications/Switch.app" 2>/dev/null || true
elif [ -f "/Applications/Switch.app" ]; then
    rm -f "/Applications/Switch.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Switch
echo "Removing $HOME/Library/Application Support/Switch..."
if [ -d "$HOME/Library/Application Support/Switch" ]; then
    rm -rf "$HOME/Library/Application Support/Switch" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Switch" ]; then
    rm -f "$HOME/Library/Application Support/Switch" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/SwitchSubStatAbort
echo "Removing $HOME/Library/Application Support/SwitchSubStatAbort..."
if [ -d "$HOME/Library/Application Support/SwitchSubStatAbort" ]; then
    rm -rf "$HOME/Library/Application Support/SwitchSubStatAbort" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/SwitchSubStatAbort" ]; then
    rm -f "$HOME/Library/Application Support/SwitchSubStatAbort" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/SwitchCounts.txt
echo "Removing $HOME/Library/Caches/SwitchCounts.txt..."
if [ -d "$HOME/Library/Caches/SwitchCounts.txt" ]; then
    rm -rf "$HOME/Library/Caches/SwitchCounts.txt" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/SwitchCounts.txt" ]; then
    rm -f "$HOME/Library/Caches/SwitchCounts.txt" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/ByHost/com.nchsoftware.switch.*.plist
echo "Removing $HOME/Library/Preferences/ByHost/com.nchsoftware.switch.*.plist..."
if [ -d "$HOME/Library/Preferences/ByHost/com.nchsoftware.switch.*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/ByHost/com.nchsoftware.switch.*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/ByHost/com.nchsoftware.switch.*.plist" ]; then
    rm -f "$HOME/Library/Preferences/ByHost/com.nchsoftware.switch.*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.nchsoftware.switch.plist
echo "Removing $HOME/Library/Preferences/com.nchsoftware.switch.plist..."
if [ -d "$HOME/Library/Preferences/com.nchsoftware.switch.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.nchsoftware.switch.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.nchsoftware.switch.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.nchsoftware.switch.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
