#!/bin/bash
# Uninstall script for ChatWork
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling ChatWork..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping ChatWork if running..."
pkill -f "ChatWork" 2>/dev/null || true

# Remove /Applications/ChatWork.app
echo "Removing /Applications/ChatWork.app..."
if [ -d "/Applications/ChatWork.app" ]; then
    rm -rf "/Applications/ChatWork.app" 2>/dev/null || true
elif [ -f "/Applications/ChatWork.app" ]; then
    rm -f "/Applications/ChatWork.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Chatwork
echo "Removing $HOME/Library/Application Support/Chatwork..."
if [ -d "$HOME/Library/Application Support/Chatwork" ]; then
    rm -rf "$HOME/Library/Application Support/Chatwork" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Chatwork" ]; then
    rm -f "$HOME/Library/Application Support/Chatwork" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.electron.chatwork
echo "Removing $HOME/Library/Caches/com.electron.chatwork..."
if [ -d "$HOME/Library/Caches/com.electron.chatwork" ]; then
    rm -rf "$HOME/Library/Caches/com.electron.chatwork" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.electron.chatwork" ]; then
    rm -f "$HOME/Library/Caches/com.electron.chatwork" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.electron.chatwork.ShipIt
echo "Removing $HOME/Library/Caches/com.electron.chatwork.ShipIt..."
if [ -d "$HOME/Library/Caches/com.electron.chatwork.ShipIt" ]; then
    rm -rf "$HOME/Library/Caches/com.electron.chatwork.ShipIt" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.electron.chatwork.ShipIt" ]; then
    rm -f "$HOME/Library/Caches/com.electron.chatwork.ShipIt" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.electron.chatwork
echo "Removing $HOME/Library/HTTPStorages/com.electron.chatwork..."
if [ -d "$HOME/Library/HTTPStorages/com.electron.chatwork" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.electron.chatwork" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.electron.chatwork" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.electron.chatwork" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.electron.chatwork.plist
echo "Removing $HOME/Library/Preferences/com.electron.chatwork.plist..."
if [ -d "$HOME/Library/Preferences/com.electron.chatwork.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.electron.chatwork.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.electron.chatwork.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.electron.chatwork.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
