#!/bin/bash
# Uninstall script for Box Tools
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Box Tools..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Box Tools if running..."
pkill -f "Box Tools" 2>/dev/null || true

# Kill application with bundle ID com.Box.Box-Edit if running
echo "Stopping application with bundle ID com.Box.Box-Edit if running..."
killall -9 "com.Box.Box-Edit" 2>/dev/null || true

# Kill application with bundle ID com.box.Box-Local-Com-Server if running
echo "Stopping application with bundle ID com.box.Box-Local-Com-Server if running..."
killall -9 "com.box.Box-Local-Com-Server" 2>/dev/null || true

# Remove /Applications/Install Box Tools.app/Contents/Resources/Box Device Trust.app
echo "Removing /Applications/Install Box Tools.app/Contents/Resources/Box Device Trust.app..."
if [ -d "/Applications/Install Box Tools.app/Contents/Resources/Box Device Trust.app" ]; then
    rm -rf "/Applications/Install Box Tools.app/Contents/Resources/Box Device Trust.app" 2>/dev/null || true
elif [ -f "/Applications/Install Box Tools.app/Contents/Resources/Box Device Trust.app" ]; then
    rm -f "/Applications/Install Box Tools.app/Contents/Resources/Box Device Trust.app" 2>/dev/null || true
fi

# Remove /Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Device Trust.app'}
echo "Removing /Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Device Trust.app'}..."
if [ -d "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Device Trust.app'}" ]; then
    rm -rf "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Device Trust.app'}" 2>/dev/null || true
elif [ -f "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Device Trust.app'}" ]; then
    rm -f "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Device Trust.app'}" 2>/dev/null || true
fi

# Remove /Applications/Install Box Tools.app/Contents/Resources/Box Edit.app
echo "Removing /Applications/Install Box Tools.app/Contents/Resources/Box Edit.app..."
if [ -d "/Applications/Install Box Tools.app/Contents/Resources/Box Edit.app" ]; then
    rm -rf "/Applications/Install Box Tools.app/Contents/Resources/Box Edit.app" 2>/dev/null || true
elif [ -f "/Applications/Install Box Tools.app/Contents/Resources/Box Edit.app" ]; then
    rm -f "/Applications/Install Box Tools.app/Contents/Resources/Box Edit.app" 2>/dev/null || true
fi

# Remove /Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Edit.app'}
echo "Removing /Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Edit.app'}..."
if [ -d "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Edit.app'}" ]; then
    rm -rf "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Edit.app'}" 2>/dev/null || true
elif [ -f "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Edit.app'}" ]; then
    rm -f "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Edit.app'}" 2>/dev/null || true
fi

# Remove /Applications/Install Box Tools.app/Contents/Resources/Box Local Com Server.app
echo "Removing /Applications/Install Box Tools.app/Contents/Resources/Box Local Com Server.app..."
if [ -d "/Applications/Install Box Tools.app/Contents/Resources/Box Local Com Server.app" ]; then
    rm -rf "/Applications/Install Box Tools.app/Contents/Resources/Box Local Com Server.app" 2>/dev/null || true
elif [ -f "/Applications/Install Box Tools.app/Contents/Resources/Box Local Com Server.app" ]; then
    rm -f "/Applications/Install Box Tools.app/Contents/Resources/Box Local Com Server.app" 2>/dev/null || true
fi

# Remove /Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Local Com Server.app'}
echo "Removing /Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Local Com Server.app'}..."
if [ -d "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Local Com Server.app'}" ]; then
    rm -rf "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Local Com Server.app'}" 2>/dev/null || true
elif [ -f "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Local Com Server.app'}" ]; then
    rm -f "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Local Com Server.app'}" 2>/dev/null || true
fi

# Remove /Applications/Install Box Tools.app/Contents/Resources/Box Tools Custom Apps.app
echo "Removing /Applications/Install Box Tools.app/Contents/Resources/Box Tools Custom Apps.app..."
if [ -d "/Applications/Install Box Tools.app/Contents/Resources/Box Tools Custom Apps.app" ]; then
    rm -rf "/Applications/Install Box Tools.app/Contents/Resources/Box Tools Custom Apps.app" 2>/dev/null || true
elif [ -f "/Applications/Install Box Tools.app/Contents/Resources/Box Tools Custom Apps.app" ]; then
    rm -f "/Applications/Install Box Tools.app/Contents/Resources/Box Tools Custom Apps.app" 2>/dev/null || true
fi

# Remove /Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Tools Custom Apps.app'}
echo "Removing /Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Tools Custom Apps.app'}..."
if [ -d "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Tools Custom Apps.app'}" ]; then
    rm -rf "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Tools Custom Apps.app'}" 2>/dev/null || true
elif [ -f "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Tools Custom Apps.app'}" ]; then
    rm -f "/Applications/{'target': '~/Library/Application Support/Box/Box Edit/Box Tools Custom Apps.app'}" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Box/Box Edit
echo "Removing $HOME/Library/Application Support/Box/Box Edit..."
if [ -d "$HOME/Library/Application Support/Box/Box Edit" ]; then
    rm -rf "$HOME/Library/Application Support/Box/Box Edit" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Box/Box Edit" ]; then
    rm -f "$HOME/Library/Application Support/Box/Box Edit" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Box
echo "Removing $HOME/Library/Application Support/Box..."
if [ -d "$HOME/Library/Application Support/Box" ]; then
    rm -rf "$HOME/Library/Application Support/Box" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Box" ]; then
    rm -f "$HOME/Library/Application Support/Box" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
