#!/bin/bash
# Uninstall script for Permute
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Permute..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Permute if running..."
pkill -f "Permute" 2>/dev/null || true

# Remove /Applications/Permute 3.app
echo "Removing /Applications/Permute 3.app..."
if [ -d "/Applications/Permute 3.app" ]; then
    rm -rf "/Applications/Permute 3.app" 2>/dev/null || true
elif [ -f "/Applications/Permute 3.app" ]; then
    rm -f "/Applications/Permute 3.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.charliemonroe.Permute-3
echo "Removing $HOME/Library/Containers/com.charliemonroe.Permute-3..."
if [ -d "$HOME/Library/Containers/com.charliemonroe.Permute-3" ]; then
    rm -rf "$HOME/Library/Containers/com.charliemonroe.Permute-3" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.charliemonroe.Permute-3" ]; then
    rm -f "$HOME/Library/Containers/com.charliemonroe.Permute-3" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.charliemonroe.Permute-3.plist
echo "Removing $HOME/Library/Preferences/com.charliemonroe.Permute-3.plist..."
if [ -d "$HOME/Library/Preferences/com.charliemonroe.Permute-3.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.charliemonroe.Permute-3.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.charliemonroe.Permute-3.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.charliemonroe.Permute-3.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
