#!/bin/bash
# Uninstall script for GPG Suite
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling GPG Suite..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping GPG Suite if running..."
pkill -f "GPG Suite" 2>/dev/null || true

# Unload service org.gpgtools.gpgmail.enable-bundles
echo "Unloading service org.gpgtools.gpgmail.enable-bundles..."
launchctl unload -w /Library/LaunchAgents/org.gpgtools.gpgmail.enable-bundles.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/org.gpgtools.gpgmail.enable-bundles.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/org.gpgtools.gpgmail.enable-bundles.plist 2>/dev/null || true

# Unload service org.gpgtools.gpgmail.patch-uuid-user
echo "Unloading service org.gpgtools.gpgmail.patch-uuid-user..."
launchctl unload -w /Library/LaunchAgents/org.gpgtools.gpgmail.patch-uuid-user.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/org.gpgtools.gpgmail.patch-uuid-user.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/org.gpgtools.gpgmail.patch-uuid-user.plist 2>/dev/null || true

# Unload service org.gpgtools.gpgmail.user-uuid-patcher
echo "Unloading service org.gpgtools.gpgmail.user-uuid-patcher..."
launchctl unload -w /Library/LaunchAgents/org.gpgtools.gpgmail.user-uuid-patcher.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/org.gpgtools.gpgmail.user-uuid-patcher.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/org.gpgtools.gpgmail.user-uuid-patcher.plist 2>/dev/null || true

# Unload service org.gpgtools.gpgmail.uuid-patcher
echo "Unloading service org.gpgtools.gpgmail.uuid-patcher..."
launchctl unload -w /Library/LaunchAgents/org.gpgtools.gpgmail.uuid-patcher.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/org.gpgtools.gpgmail.uuid-patcher.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/org.gpgtools.gpgmail.uuid-patcher.plist 2>/dev/null || true

# Unload service org.gpgtools.Libmacgpg.xpc
echo "Unloading service org.gpgtools.Libmacgpg.xpc..."
launchctl unload -w /Library/LaunchAgents/org.gpgtools.Libmacgpg.xpc.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/org.gpgtools.Libmacgpg.xpc.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/org.gpgtools.Libmacgpg.xpc.plist 2>/dev/null || true

# Unload service org.gpgtools.macgpg2.fix
echo "Unloading service org.gpgtools.macgpg2.fix..."
launchctl unload -w /Library/LaunchAgents/org.gpgtools.macgpg2.fix.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/org.gpgtools.macgpg2.fix.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/org.gpgtools.macgpg2.fix.plist 2>/dev/null || true

# Unload service org.gpgtools.macgpg2.gpg-agent
echo "Unloading service org.gpgtools.macgpg2.gpg-agent..."
launchctl unload -w /Library/LaunchAgents/org.gpgtools.macgpg2.gpg-agent.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/org.gpgtools.macgpg2.gpg-agent.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/org.gpgtools.macgpg2.gpg-agent.plist 2>/dev/null || true

# Unload service org.gpgtools.macgpg2.shutdown-gpg-agent
echo "Unloading service org.gpgtools.macgpg2.shutdown-gpg-agent..."
launchctl unload -w /Library/LaunchAgents/org.gpgtools.macgpg2.shutdown-gpg-agent.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/org.gpgtools.macgpg2.shutdown-gpg-agent.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/org.gpgtools.macgpg2.shutdown-gpg-agent.plist 2>/dev/null || true

# Unload service org.gpgtools.macgpg2.updater
echo "Unloading service org.gpgtools.macgpg2.updater..."
launchctl unload -w /Library/LaunchAgents/org.gpgtools.macgpg2.updater.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/org.gpgtools.macgpg2.updater.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/org.gpgtools.macgpg2.updater.plist 2>/dev/null || true

# Unload service org.gpgtools.updater
echo "Unloading service org.gpgtools.updater..."
launchctl unload -w /Library/LaunchAgents/org.gpgtools.updater.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/org.gpgtools.updater.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/org.gpgtools.updater.plist 2>/dev/null || true

# Kill application with bundle ID com.apple.mail if running
echo "Stopping application with bundle ID com.apple.mail if running..."
killall -9 "com.apple.mail" 2>/dev/null || true

# Kill application with bundle ID org.gpgtools.gpgkeychain if running
echo "Stopping application with bundle ID org.gpgtools.gpgkeychain if running..."
killall -9 "org.gpgtools.gpgkeychain" 2>/dev/null || true

# Kill application with bundle ID org.gpgtools.gpgkeychainaccess if running
echo "Stopping application with bundle ID org.gpgtools.gpgkeychainaccess if running..."
killall -9 "org.gpgtools.gpgkeychainaccess" 2>/dev/null || true

# Kill application with bundle ID org.gpgtools.gpgmail.upgrader if running
echo "Stopping application with bundle ID org.gpgtools.gpgmail.upgrader if running..."
killall -9 "org.gpgtools.gpgmail.upgrader" 2>/dev/null || true

# Kill application with bundle ID org.gpgtools.gpgservices if running
echo "Stopping application with bundle ID org.gpgtools.gpgservices if running..."
killall -9 "org.gpgtools.gpgservices" 2>/dev/null || true

# Remove $HOME/Library/Application Support/GPGTools
echo "Removing $HOME/Library/Application Support/GPGTools..."
if [ -d "$HOME/Library/Application Support/GPGTools" ]; then
    rm -rf "$HOME/Library/Application Support/GPGTools" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/GPGTools" ]; then
    rm -f "$HOME/Library/Application Support/GPGTools" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/org.gpgtools.gpg*
echo "Removing $HOME/Library/Caches/org.gpgtools.gpg*..."
if [ -d "$HOME/Library/Caches/org.gpgtools.gpg*" ]; then
    rm -rf "$HOME/Library/Caches/org.gpgtools.gpg*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/org.gpgtools.gpg*" ]; then
    rm -f "$HOME/Library/Caches/org.gpgtools.gpg*" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.apple.mail/Data/Library/Frameworks/Libmacgpg.framework
echo "Removing $HOME/Library/Containers/com.apple.mail/Data/Library/Frameworks/Libmacgpg.framework..."
if [ -d "$HOME/Library/Containers/com.apple.mail/Data/Library/Frameworks/Libmacgpg.framework" ]; then
    rm -rf "$HOME/Library/Containers/com.apple.mail/Data/Library/Frameworks/Libmacgpg.framework" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.apple.mail/Data/Library/Frameworks/Libmacgpg.framework" ]; then
    rm -f "$HOME/Library/Containers/com.apple.mail/Data/Library/Frameworks/Libmacgpg.framework" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.apple.mail/Data/Library/Preferences/org.gpgtools.*
echo "Removing $HOME/Library/Containers/com.apple.mail/Data/Library/Preferences/org.gpgtools.*..."
if [ -d "$HOME/Library/Containers/com.apple.mail/Data/Library/Preferences/org.gpgtools.*" ]; then
    rm -rf "$HOME/Library/Containers/com.apple.mail/Data/Library/Preferences/org.gpgtools.*" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.apple.mail/Data/Library/Preferences/org.gpgtools.*" ]; then
    rm -f "$HOME/Library/Containers/com.apple.mail/Data/Library/Preferences/org.gpgtools.*" 2>/dev/null || true
fi

# Remove $HOME/Library/Frameworks/Libmacgpg.framework
echo "Removing $HOME/Library/Frameworks/Libmacgpg.framework..."
if [ -d "$HOME/Library/Frameworks/Libmacgpg.framework" ]; then
    rm -rf "$HOME/Library/Frameworks/Libmacgpg.framework" 2>/dev/null || true
elif [ -f "$HOME/Library/Frameworks/Libmacgpg.framework" ]; then
    rm -f "$HOME/Library/Frameworks/Libmacgpg.framework" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/org.gpgtools.*
echo "Removing $HOME/Library/HTTPStorages/org.gpgtools.*..."
if [ -d "$HOME/Library/HTTPStorages/org.gpgtools.*" ]; then
    rm -rf "$HOME/Library/HTTPStorages/org.gpgtools.*" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/org.gpgtools.*" ]; then
    rm -f "$HOME/Library/HTTPStorages/org.gpgtools.*" 2>/dev/null || true
fi

# Remove $HOME/Library/LaunchAgents/org.gpgtools.*
echo "Removing $HOME/Library/LaunchAgents/org.gpgtools.*..."
if [ -d "$HOME/Library/LaunchAgents/org.gpgtools.*" ]; then
    rm -rf "$HOME/Library/LaunchAgents/org.gpgtools.*" 2>/dev/null || true
elif [ -f "$HOME/Library/LaunchAgents/org.gpgtools.*" ]; then
    rm -f "$HOME/Library/LaunchAgents/org.gpgtools.*" 2>/dev/null || true
fi

# Remove $HOME/Library/Mail/Bundles/GPGMail.mailbundle
echo "Removing $HOME/Library/Mail/Bundles/GPGMail.mailbundle..."
if [ -d "$HOME/Library/Mail/Bundles/GPGMail.mailbundle" ]; then
    rm -rf "$HOME/Library/Mail/Bundles/GPGMail.mailbundle" 2>/dev/null || true
elif [ -f "$HOME/Library/Mail/Bundles/GPGMail.mailbundle" ]; then
    rm -f "$HOME/Library/Mail/Bundles/GPGMail.mailbundle" 2>/dev/null || true
fi

# Remove $HOME/Library/PreferencePanes/GPGPreferences.prefPane
echo "Removing $HOME/Library/PreferencePanes/GPGPreferences.prefPane..."
if [ -d "$HOME/Library/PreferencePanes/GPGPreferences.prefPane" ]; then
    rm -rf "$HOME/Library/PreferencePanes/GPGPreferences.prefPane" 2>/dev/null || true
elif [ -f "$HOME/Library/PreferencePanes/GPGPreferences.prefPane" ]; then
    rm -f "$HOME/Library/PreferencePanes/GPGPreferences.prefPane" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/org.gpgtools.*
echo "Removing $HOME/Library/Preferences/org.gpgtools.*..."
if [ -d "$HOME/Library/Preferences/org.gpgtools.*" ]; then
    rm -rf "$HOME/Library/Preferences/org.gpgtools.*" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/org.gpgtools.*" ]; then
    rm -f "$HOME/Library/Preferences/org.gpgtools.*" 2>/dev/null || true
fi

# Remove $HOME/Library/Services/GPGServices.service
echo "Removing $HOME/Library/Services/GPGServices.service..."
if [ -d "$HOME/Library/Services/GPGServices.service" ]; then
    rm -rf "$HOME/Library/Services/GPGServices.service" 2>/dev/null || true
elif [ -f "$HOME/Library/Services/GPGServices.service" ]; then
    rm -f "$HOME/Library/Services/GPGServices.service" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
