#!/bin/bash
# Uninstall script for Postbox
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Postbox..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Postbox if running..."
pkill -f "Postbox" 2>/dev/null || true

# Remove /Applications/Postbox.app
echo "Removing /Applications/Postbox.app..."
if [ -d "/Applications/Postbox.app" ]; then
    rm -rf "/Applications/Postbox.app" 2>/dev/null || true
elif [ -f "/Applications/Postbox.app" ]; then
    rm -f "/Applications/Postbox.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Postbox
echo "Removing $HOME/Library/Application Support/Postbox..."
if [ -d "$HOME/Library/Application Support/Postbox" ]; then
    rm -rf "$HOME/Library/Application Support/Postbox" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Postbox" ]; then
    rm -f "$HOME/Library/Application Support/Postbox" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/PostboxApp
echo "Removing $HOME/Library/Application Support/PostboxApp..."
if [ -d "$HOME/Library/Application Support/PostboxApp" ]; then
    rm -rf "$HOME/Library/Application Support/PostboxApp" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/PostboxApp" ]; then
    rm -f "$HOME/Library/Application Support/PostboxApp" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.crashlytics.data/com.postbox-inc.postbox
echo "Removing $HOME/Library/Caches/com.crashlytics.data/com.postbox-inc.postbox..."
if [ -d "$HOME/Library/Caches/com.crashlytics.data/com.postbox-inc.postbox" ]; then
    rm -rf "$HOME/Library/Caches/com.crashlytics.data/com.postbox-inc.postbox" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.crashlytics.data/com.postbox-inc.postbox" ]; then
    rm -f "$HOME/Library/Caches/com.crashlytics.data/com.postbox-inc.postbox" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.postbox-inc.postbox
echo "Removing $HOME/Library/Caches/com.postbox-inc.postbox..."
if [ -d "$HOME/Library/Caches/com.postbox-inc.postbox" ]; then
    rm -rf "$HOME/Library/Caches/com.postbox-inc.postbox" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.postbox-inc.postbox" ]; then
    rm -f "$HOME/Library/Caches/com.postbox-inc.postbox" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/Postbox
echo "Removing $HOME/Library/Caches/Postbox..."
if [ -d "$HOME/Library/Caches/Postbox" ]; then
    rm -rf "$HOME/Library/Caches/Postbox" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/Postbox" ]; then
    rm -f "$HOME/Library/Caches/Postbox" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/PostboxApp
echo "Removing $HOME/Library/Caches/PostboxApp..."
if [ -d "$HOME/Library/Caches/PostboxApp" ]; then
    rm -rf "$HOME/Library/Caches/PostboxApp" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/PostboxApp" ]; then
    rm -f "$HOME/Library/Caches/PostboxApp" 2>/dev/null || true
fi

# Remove $HOME/Library/PDF Services/Mail PDF with Postbox
echo "Removing $HOME/Library/PDF Services/Mail PDF with Postbox..."
if [ -d "$HOME/Library/PDF Services/Mail PDF with Postbox" ]; then
    rm -rf "$HOME/Library/PDF Services/Mail PDF with Postbox" 2>/dev/null || true
elif [ -f "$HOME/Library/PDF Services/Mail PDF with Postbox" ]; then
    rm -f "$HOME/Library/PDF Services/Mail PDF with Postbox" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.postbox-inc.postbox.plist
echo "Removing $HOME/Library/Preferences/com.postbox-inc.postbox.plist..."
if [ -d "$HOME/Library/Preferences/com.postbox-inc.postbox.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.postbox-inc.postbox.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.postbox-inc.postbox.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.postbox-inc.postbox.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.postbox-inc.postbox.savedState
echo "Removing $HOME/Library/Saved Application State/com.postbox-inc.postbox.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.postbox-inc.postbox.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.postbox-inc.postbox.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.postbox-inc.postbox.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.postbox-inc.postbox.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
