#!/bin/bash
# Uninstall script for PicView
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling PicView..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping PicView if running..."
pkill -f "PicView" 2>/dev/null || true

# Remove /Applications/PicView.app
echo "Removing /Applications/PicView.app..."
if [ -d "/Applications/PicView.app" ]; then
    rm -rf "/Applications/PicView.app" 2>/dev/null || true
elif [ -f "/Applications/PicView.app" ]; then
    rm -f "/Applications/PicView.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Ruben2776/PicView
echo "Removing $HOME/Library/Application Support/Ruben2776/PicView..."
if [ -d "$HOME/Library/Application Support/Ruben2776/PicView" ]; then
    rm -rf "$HOME/Library/Application Support/Ruben2776/PicView" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Ruben2776/PicView" ]; then
    rm -f "$HOME/Library/Application Support/Ruben2776/PicView" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.ruben2776.picview.plist
echo "Removing $HOME/Library/Preferences/com.ruben2776.picview.plist..."
if [ -d "$HOME/Library/Preferences/com.ruben2776.picview.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.ruben2776.picview.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.ruben2776.picview.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.ruben2776.picview.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
