#!/bin/bash
# Uninstall script for GoodSync
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling GoodSync..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping GoodSync if running..."
pkill -f "GoodSync" 2>/dev/null || true

# Remove /Applications/GoodSync.app
echo "Removing /Applications/GoodSync.app..."
if [ -d "/Applications/GoodSync.app" ]; then
    rm -rf "/Applications/GoodSync.app" 2>/dev/null || true
elif [ -f "/Applications/GoodSync.app" ]; then
    rm -f "/Applications/GoodSync.app" 2>/dev/null || true
fi

# Remove /Library/Application Support/GoodSync
echo "Removing /Library/Application Support/GoodSync..."
if [ -d "/Library/Application Support/GoodSync" ]; then
    rm -rf "/Library/Application Support/GoodSync" 2>/dev/null || true
elif [ -f "/Library/Application Support/GoodSync" ]; then
    rm -f "/Library/Application Support/GoodSync" 2>/dev/null || true
fi

# Remove /Library/LaunchDaemons/com.siber.gs-server.plist
echo "Removing /Library/LaunchDaemons/com.siber.gs-server.plist..."
if [ -d "/Library/LaunchDaemons/com.siber.gs-server.plist" ]; then
    rm -rf "/Library/LaunchDaemons/com.siber.gs-server.plist" 2>/dev/null || true
elif [ -f "/Library/LaunchDaemons/com.siber.gs-server.plist" ]; then
    rm -f "/Library/LaunchDaemons/com.siber.gs-server.plist" 2>/dev/null || true
fi

# Remove $HOME/.goodsync
echo "Removing $HOME/.goodsync..."
if [ -d "$HOME/.goodsync" ]; then
    rm -rf "$HOME/.goodsync" 2>/dev/null || true
elif [ -f "$HOME/.goodsync" ]; then
    rm -f "$HOME/.goodsync" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/GoodSync
echo "Removing $HOME/Library/Application Support/GoodSync..."
if [ -d "$HOME/Library/Application Support/GoodSync" ]; then
    rm -rf "$HOME/Library/Application Support/GoodSync" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/GoodSync" ]; then
    rm -f "$HOME/Library/Application Support/GoodSync" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.sibersystems.goodsyncmac2000.plist
echo "Removing $HOME/Library/Preferences/com.sibersystems.goodsyncmac2000.plist..."
if [ -d "$HOME/Library/Preferences/com.sibersystems.goodsyncmac2000.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.sibersystems.goodsyncmac2000.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.sibersystems.goodsyncmac2000.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.sibersystems.goodsyncmac2000.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
