#!/bin/bash
# Uninstall script for SmartBear SoapUI
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling SmartBear SoapUI..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping SmartBear SoapUI if running..."
pkill -f "SmartBear SoapUI" 2>/dev/null || true

# Remove $HOME/.soapuios
echo "Removing $HOME/.soapuios..."
if [ -d "$HOME/.soapuios" ]; then
    rm -rf "$HOME/.soapuios" 2>/dev/null || true
elif [ -f "$HOME/.soapuios" ]; then
    rm -f "$HOME/.soapuios" 2>/dev/null || true
fi

# Remove $HOME/default-soapui-workspace.xml
echo "Removing $HOME/default-soapui-workspace.xml..."
if [ -d "$HOME/default-soapui-workspace.xml" ]; then
    rm -rf "$HOME/default-soapui-workspace.xml" 2>/dev/null || true
elif [ -f "$HOME/default-soapui-workspace.xml" ]; then
    rm -f "$HOME/default-soapui-workspace.xml" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/SoapUI-*
echo "Removing $HOME/Library/Application Support/SoapUI-*..."
if [ -d "$HOME/Library/Application Support/SoapUI-*" ]; then
    rm -rf "$HOME/Library/Application Support/SoapUI-*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/SoapUI-*" ]; then
    rm -f "$HOME/Library/Application Support/SoapUI-*" 2>/dev/null || true
fi

# Remove $HOME/soapui-settings.xml
echo "Removing $HOME/soapui-settings.xml..."
if [ -d "$HOME/soapui-settings.xml" ]; then
    rm -rf "$HOME/soapui-settings.xml" 2>/dev/null || true
elif [ -f "$HOME/soapui-settings.xml" ]; then
    rm -f "$HOME/soapui-settings.xml" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
