#!/bin/bash
# Uninstall script for Eclipse IDE for Eclipse Committers
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Eclipse IDE for Eclipse Committers..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Eclipse IDE for Eclipse Committers if running..."
pkill -f "Eclipse IDE for Eclipse Committers" 2>/dev/null || true

# Remove /Applications/Eclipse.app
echo "Removing /Applications/Eclipse.app..."
if [ -d "/Applications/Eclipse.app" ]; then
    rm -rf "/Applications/Eclipse.app" 2>/dev/null || true
elif [ -f "/Applications/Eclipse.app" ]; then
    rm -f "/Applications/Eclipse.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/epp.package.committers.plist
echo "Removing $HOME/Library/Preferences/epp.package.committers.plist..."
if [ -d "$HOME/Library/Preferences/epp.package.committers.plist" ]; then
    rm -rf "$HOME/Library/Preferences/epp.package.committers.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/epp.package.committers.plist" ]; then
    rm -f "$HOME/Library/Preferences/epp.package.committers.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
