#!/bin/bash
# Uninstall script for MQTTX
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling MQTTX..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping MQTTX if running..."
pkill -f "MQTTX" 2>/dev/null || true

# Remove /Applications/MQTTX.app
echo "Removing /Applications/MQTTX.app..."
if [ -d "/Applications/MQTTX.app" ]; then
    rm -rf "/Applications/MQTTX.app" 2>/dev/null || true
elif [ -f "/Applications/MQTTX.app" ]; then
    rm -f "/Applications/MQTTX.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/MQTTX
echo "Removing $HOME/Library/Application Support/MQTTX..."
if [ -d "$HOME/Library/Application Support/MQTTX" ]; then
    rm -rf "$HOME/Library/Application Support/MQTTX" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/MQTTX" ]; then
    rm -f "$HOME/Library/Application Support/MQTTX" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/MQTTX
echo "Removing $HOME/Library/Logs/MQTTX..."
if [ -d "$HOME/Library/Logs/MQTTX" ]; then
    rm -rf "$HOME/Library/Logs/MQTTX" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/MQTTX" ]; then
    rm -f "$HOME/Library/Logs/MQTTX" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.electron.mqttx.plist
echo "Removing $HOME/Library/Preferences/com.electron.mqttx.plist..."
if [ -d "$HOME/Library/Preferences/com.electron.mqttx.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.electron.mqttx.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.electron.mqttx.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.electron.mqttx.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.electron.mqttx.savedState
echo "Removing $HOME/Library/Saved Application State/com.electron.mqttx.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.electron.mqttx.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.electron.mqttx.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.electron.mqttx.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.electron.mqttx.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
