#!/bin/bash
# Uninstall script for Bluefish
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Bluefish..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Bluefish if running..."
pkill -f "Bluefish" 2>/dev/null || true

# Remove /Applications/Bluefish.app
echo "Removing /Applications/Bluefish.app..."
if [ -d "/Applications/Bluefish.app" ]; then
    rm -rf "/Applications/Bluefish.app" 2>/dev/null || true
elif [ -f "/Applications/Bluefish.app" ]; then
    rm -f "/Applications/Bluefish.app" 2>/dev/null || true
fi

# Remove $HOME/.bluefish
echo "Removing $HOME/.bluefish..."
if [ -d "$HOME/.bluefish" ]; then
    rm -rf "$HOME/.bluefish" 2>/dev/null || true
elif [ -f "$HOME/.bluefish" ]; then
    rm -f "$HOME/.bluefish" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/nl.openoffice.bluefish.plist
echo "Removing $HOME/Library/Preferences/nl.openoffice.bluefish.plist..."
if [ -d "$HOME/Library/Preferences/nl.openoffice.bluefish.plist" ]; then
    rm -rf "$HOME/Library/Preferences/nl.openoffice.bluefish.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/nl.openoffice.bluefish.plist" ]; then
    rm -f "$HOME/Library/Preferences/nl.openoffice.bluefish.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/nl.openoffice.bluefish.savedState
echo "Removing $HOME/Library/Saved Application State/nl.openoffice.bluefish.savedState..."
if [ -d "$HOME/Library/Saved Application State/nl.openoffice.bluefish.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/nl.openoffice.bluefish.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/nl.openoffice.bluefish.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/nl.openoffice.bluefish.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
