#!/bin/bash
# Uninstall script for Disk Drill
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Disk Drill..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Disk Drill if running..."
pkill -f "Disk Drill" 2>/dev/null || true

# Remove /Applications/Disk Drill.app
echo "Removing /Applications/Disk Drill.app..."
if [ -d "/Applications/Disk Drill.app" ]; then
    rm -rf "/Applications/Disk Drill.app" 2>/dev/null || true
elif [ -f "/Applications/Disk Drill.app" ]; then
    rm -f "/Applications/Disk Drill.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.cleverfiles.diskdrill.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.cleverfiles.diskdrill.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.cleverfiles.diskdrill.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.cleverfiles.diskdrill.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.cleverfiles.diskdrill.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.cleverfiles.diskdrill.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/DiskDrill
echo "Removing $HOME/Library/Application Support/DiskDrill..."
if [ -d "$HOME/Library/Application Support/DiskDrill" ]; then
    rm -rf "$HOME/Library/Application Support/DiskDrill" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/DiskDrill" ]; then
    rm -f "$HOME/Library/Application Support/DiskDrill" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.cleverfiles.Disk_Drill
echo "Removing $HOME/Library/Caches/com.cleverfiles.Disk_Drill..."
if [ -d "$HOME/Library/Caches/com.cleverfiles.Disk_Drill" ]; then
    rm -rf "$HOME/Library/Caches/com.cleverfiles.Disk_Drill" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.cleverfiles.Disk_Drill" ]; then
    rm -f "$HOME/Library/Caches/com.cleverfiles.Disk_Drill" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.cleverfiles.DiskDrill.Media/Data/cfbackd.chief
echo "Removing $HOME/Library/Containers/com.cleverfiles.DiskDrill.Media/Data/cfbackd.chief..."
if [ -d "$HOME/Library/Containers/com.cleverfiles.DiskDrill.Media/Data/cfbackd.chief" ]; then
    rm -rf "$HOME/Library/Containers/com.cleverfiles.DiskDrill.Media/Data/cfbackd.chief" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.cleverfiles.DiskDrill.Media/Data/cfbackd.chief" ]; then
    rm -f "$HOME/Library/Containers/com.cleverfiles.DiskDrill.Media/Data/cfbackd.chief" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.cleverfiles.DiskDrill.binarycookies
echo "Removing $HOME/Library/HTTPStorages/com.cleverfiles.DiskDrill.binarycookies..."
if [ -d "$HOME/Library/HTTPStorages/com.cleverfiles.DiskDrill.binarycookies" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.cleverfiles.DiskDrill.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.cleverfiles.DiskDrill.binarycookies" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.cleverfiles.DiskDrill.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/DiskDrill.log
echo "Removing $HOME/Library/Logs/DiskDrill.log..."
if [ -d "$HOME/Library/Logs/DiskDrill.log" ]; then
    rm -rf "$HOME/Library/Logs/DiskDrill.log" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/DiskDrill.log" ]; then
    rm -f "$HOME/Library/Logs/DiskDrill.log" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.cleverfiles.activator.xml
echo "Removing $HOME/Library/Preferences/com.cleverfiles.activator.xml..."
if [ -d "$HOME/Library/Preferences/com.cleverfiles.activator.xml" ]; then
    rm -rf "$HOME/Library/Preferences/com.cleverfiles.activator.xml" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.cleverfiles.activator.xml" ]; then
    rm -f "$HOME/Library/Preferences/com.cleverfiles.activator.xml" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.cleverfiles.Disk_Drill.plist
echo "Removing $HOME/Library/Preferences/com.cleverfiles.Disk_Drill.plist..."
if [ -d "$HOME/Library/Preferences/com.cleverfiles.Disk_Drill.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.cleverfiles.Disk_Drill.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.cleverfiles.Disk_Drill.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.cleverfiles.Disk_Drill.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.cleverfiles.DiskDrill-setapp.plist
echo "Removing $HOME/Library/Preferences/com.cleverfiles.DiskDrill-setapp.plist..."
if [ -d "$HOME/Library/Preferences/com.cleverfiles.DiskDrill-setapp.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.cleverfiles.DiskDrill-setapp.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.cleverfiles.DiskDrill-setapp.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.cleverfiles.DiskDrill-setapp.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.cleverfiles.DiskDrill.plist
echo "Removing $HOME/Library/Preferences/com.cleverfiles.DiskDrill.plist..."
if [ -d "$HOME/Library/Preferences/com.cleverfiles.DiskDrill.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.cleverfiles.DiskDrill.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.cleverfiles.DiskDrill.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.cleverfiles.DiskDrill.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
