#!/bin/bash
# Uninstall script for KeyboardCleanTool
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling KeyboardCleanTool..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping KeyboardCleanTool if running..."
pkill -f "KeyboardCleanTool" 2>/dev/null || true

# Remove /Applications/KeyboardCleanTool.app
echo "Removing /Applications/KeyboardCleanTool.app..."
if [ -d "/Applications/KeyboardCleanTool.app" ]; then
    rm -rf "/Applications/KeyboardCleanTool.app" 2>/dev/null || true
elif [ -f "/Applications/KeyboardCleanTool.app" ]; then
    rm -f "/Applications/KeyboardCleanTool.app" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
