#!/bin/bash
# Uninstall script for LunaSea
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling LunaSea..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping LunaSea if running..."
pkill -f "LunaSea" 2>/dev/null || true

# Remove /Applications/LunaSea.app
echo "Removing /Applications/LunaSea.app..."
if [ -d "/Applications/LunaSea.app" ]; then
    rm -rf "/Applications/LunaSea.app" 2>/dev/null || true
elif [ -f "/Applications/LunaSea.app" ]; then
    rm -f "/Applications/LunaSea.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/app.lunasea.lunasea
echo "Removing $HOME/Library/Application Scripts/app.lunasea.lunasea..."
if [ -d "$HOME/Library/Application Scripts/app.lunasea.lunasea" ]; then
    rm -rf "$HOME/Library/Application Scripts/app.lunasea.lunasea" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/app.lunasea.lunasea" ]; then
    rm -f "$HOME/Library/Application Scripts/app.lunasea.lunasea" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/app.lunasea.lunasea
echo "Removing $HOME/Library/Containers/app.lunasea.lunasea..."
if [ -d "$HOME/Library/Containers/app.lunasea.lunasea" ]; then
    rm -rf "$HOME/Library/Containers/app.lunasea.lunasea" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/app.lunasea.lunasea" ]; then
    rm -f "$HOME/Library/Containers/app.lunasea.lunasea" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
