#!/bin/bash
# Uninstall script for SonoBus
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling SonoBus..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping SonoBus if running..."
pkill -f "SonoBus" 2>/dev/null || true

# Remove $HOME/Library/Application Support/SonoBus
echo "Removing $HOME/Library/Application Support/SonoBus..."
if [ -d "$HOME/Library/Application Support/SonoBus" ]; then
    rm -rf "$HOME/Library/Application Support/SonoBus" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/SonoBus" ]; then
    rm -f "$HOME/Library/Application Support/SonoBus" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.Sonosaurus.SonoBus
echo "Removing $HOME/Library/Caches/com.Sonosaurus.SonoBus..."
if [ -d "$HOME/Library/Caches/com.Sonosaurus.SonoBus" ]; then
    rm -rf "$HOME/Library/Caches/com.Sonosaurus.SonoBus" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.Sonosaurus.SonoBus" ]; then
    rm -f "$HOME/Library/Caches/com.Sonosaurus.SonoBus" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.Sonosaurus.SonoBus.savedState
echo "Removing $HOME/Library/Saved Application State/com.Sonosaurus.SonoBus.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.Sonosaurus.SonoBus.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.Sonosaurus.SonoBus.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.Sonosaurus.SonoBus.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.Sonosaurus.SonoBus.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
