#!/bin/bash
# Uninstall script for OpenInTerminal
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling OpenInTerminal..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping OpenInTerminal if running..."
pkill -f "OpenInTerminal" 2>/dev/null || true

# Remove /Applications/OpenInTerminal.app
echo "Removing /Applications/OpenInTerminal.app..."
if [ -d "/Applications/OpenInTerminal.app" ]; then
    rm -rf "/Applications/OpenInTerminal.app" 2>/dev/null || true
elif [ -f "/Applications/OpenInTerminal.app" ]; then
    rm -f "/Applications/OpenInTerminal.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/group.wang.jianing.app.OpenInTerminal
echo "Removing $HOME/Library/Application Scripts/group.wang.jianing.app.OpenInTerminal..."
if [ -d "$HOME/Library/Application Scripts/group.wang.jianing.app.OpenInTerminal" ]; then
    rm -rf "$HOME/Library/Application Scripts/group.wang.jianing.app.OpenInTerminal" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/group.wang.jianing.app.OpenInTerminal" ]; then
    rm -f "$HOME/Library/Application Scripts/group.wang.jianing.app.OpenInTerminal" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminal
echo "Removing $HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminal..."
if [ -d "$HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminal" ]; then
    rm -rf "$HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminal" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminal" ]; then
    rm -f "$HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminal" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension
echo "Removing $HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension..."
if [ -d "$HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension" ]; then
    rm -rf "$HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension" ]; then
    rm -f "$HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminalHelper
echo "Removing $HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminalHelper..."
if [ -d "$HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminalHelper" ]; then
    rm -rf "$HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminalHelper" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminalHelper" ]; then
    rm -f "$HOME/Library/Application Scripts/wang.jianing.app.OpenInTerminalHelper" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/wang.jianing.app.openinterminalhelper.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/wang.jianing.app.openinterminalhelper.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/wang.jianing.app.openinterminalhelper.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/wang.jianing.app.openinterminalhelper.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/wang.jianing.app.openinterminalhelper.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/wang.jianing.app.openinterminalhelper.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension
echo "Removing $HOME/Library/Containers/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension..."
if [ -d "$HOME/Library/Containers/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension" ]; then
    rm -rf "$HOME/Library/Containers/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension" ]; then
    rm -f "$HOME/Library/Containers/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/wang.jianing.app.OpenInTerminalHelper
echo "Removing $HOME/Library/Containers/wang.jianing.app.OpenInTerminalHelper..."
if [ -d "$HOME/Library/Containers/wang.jianing.app.OpenInTerminalHelper" ]; then
    rm -rf "$HOME/Library/Containers/wang.jianing.app.OpenInTerminalHelper" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/wang.jianing.app.OpenInTerminalHelper" ]; then
    rm -f "$HOME/Library/Containers/wang.jianing.app.OpenInTerminalHelper" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/group.wang.jianing.app.OpenInTerminal
echo "Removing $HOME/Library/Group Containers/group.wang.jianing.app.OpenInTerminal..."
if [ -d "$HOME/Library/Group Containers/group.wang.jianing.app.OpenInTerminal" ]; then
    rm -rf "$HOME/Library/Group Containers/group.wang.jianing.app.OpenInTerminal" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/group.wang.jianing.app.OpenInTerminal" ]; then
    rm -f "$HOME/Library/Group Containers/group.wang.jianing.app.OpenInTerminal" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/OpenInTerminal
echo "Removing $HOME/Library/Logs/OpenInTerminal..."
if [ -d "$HOME/Library/Logs/OpenInTerminal" ]; then
    rm -rf "$HOME/Library/Logs/OpenInTerminal" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/OpenInTerminal" ]; then
    rm -f "$HOME/Library/Logs/OpenInTerminal" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/wang.jianing.app.OpenInTerminal.plist
echo "Removing $HOME/Library/Preferences/wang.jianing.app.OpenInTerminal.plist..."
if [ -d "$HOME/Library/Preferences/wang.jianing.app.OpenInTerminal.plist" ]; then
    rm -rf "$HOME/Library/Preferences/wang.jianing.app.OpenInTerminal.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/wang.jianing.app.OpenInTerminal.plist" ]; then
    rm -f "$HOME/Library/Preferences/wang.jianing.app.OpenInTerminal.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
