#!/bin/bash
# Uninstall script for Contexts
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Contexts..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Contexts if running..."
pkill -f "Contexts" 2>/dev/null || true

# Kill application with bundle ID com.contextsformac.Contexts if running
echo "Stopping application with bundle ID com.contextsformac.Contexts if running..."
killall -9 "com.contextsformac.Contexts" 2>/dev/null || true

# Remove /Applications/Contexts.app
echo "Removing /Applications/Contexts.app..."
if [ -d "/Applications/Contexts.app" ]; then
    rm -rf "/Applications/Contexts.app" 2>/dev/null || true
elif [ -f "/Applications/Contexts.app" ]; then
    rm -f "/Applications/Contexts.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/.com.contextsformac.Contexts.plist
echo "Removing $HOME/Library/Application Support/.com.contextsformac.Contexts.plist..."
if [ -d "$HOME/Library/Application Support/.com.contextsformac.Contexts.plist" ]; then
    rm -rf "$HOME/Library/Application Support/.com.contextsformac.Contexts.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/.com.contextsformac.Contexts.plist" ]; then
    rm -f "$HOME/Library/Application Support/.com.contextsformac.Contexts.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.contextsformac.Contexts
echo "Removing $HOME/Library/Application Support/com.contextsformac.Contexts..."
if [ -d "$HOME/Library/Application Support/com.contextsformac.Contexts" ]; then
    rm -rf "$HOME/Library/Application Support/com.contextsformac.Contexts" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.contextsformac.Contexts" ]; then
    rm -f "$HOME/Library/Application Support/com.contextsformac.Contexts" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.contextsformac.Contexts
echo "Removing $HOME/Library/Caches/com.contextsformac.Contexts..."
if [ -d "$HOME/Library/Caches/com.contextsformac.Contexts" ]; then
    rm -rf "$HOME/Library/Caches/com.contextsformac.Contexts" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.contextsformac.Contexts" ]; then
    rm -f "$HOME/Library/Caches/com.contextsformac.Contexts" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Contexts
echo "Removing $HOME/Library/Logs/Contexts..."
if [ -d "$HOME/Library/Logs/Contexts" ]; then
    rm -rf "$HOME/Library/Logs/Contexts" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Contexts" ]; then
    rm -f "$HOME/Library/Logs/Contexts" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.contextsformac.Contexts.plist
echo "Removing $HOME/Library/Preferences/com.contextsformac.Contexts.plist..."
if [ -d "$HOME/Library/Preferences/com.contextsformac.Contexts.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.contextsformac.Contexts.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.contextsformac.Contexts.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.contextsformac.Contexts.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
