#!/bin/bash
# Uninstall script for Music Decoy
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Music Decoy..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Music Decoy if running..."
pkill -f "Music Decoy" 2>/dev/null || true

# Remove /Applications/Music Decoy.app
echo "Removing /Applications/Music Decoy.app..."
if [ -d "/Applications/Music Decoy.app" ]; then
    rm -rf "/Applications/Music Decoy.app" 2>/dev/null || true
elif [ -f "/Applications/Music Decoy.app" ]; then
    rm -f "/Applications/Music Decoy.app" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
