#!/bin/bash
# Uninstall script for Mullvad VPN
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Mullvad VPN..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Mullvad VPN if running..."
pkill -f "Mullvad VPN" 2>/dev/null || true

# Unload service net.mullvad.daemon
echo "Unloading service net.mullvad.daemon..."
launchctl unload -w /Library/LaunchAgents/net.mullvad.daemon.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/net.mullvad.daemon.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/net.mullvad.daemon.plist 2>/dev/null || true

# Kill application with bundle ID net.mullvad.vpn if running
echo "Stopping application with bundle ID net.mullvad.vpn if running..."
killall -9 "net.mullvad.vpn" 2>/dev/null || true

# Remove /etc/mullvad-vpn
echo "Removing /etc/mullvad-vpn..."
if [ -d "/etc/mullvad-vpn" ]; then
    rm -rf "/etc/mullvad-vpn" 2>/dev/null || true
elif [ -f "/etc/mullvad-vpn" ]; then
    rm -f "/etc/mullvad-vpn" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.mullvad.vpn.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.mullvad.vpn.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.mullvad.vpn.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.mullvad.vpn.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.mullvad.vpn.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.mullvad.vpn.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Mullvad VPN
echo "Removing $HOME/Library/Application Support/Mullvad VPN..."
if [ -d "$HOME/Library/Application Support/Mullvad VPN" ]; then
    rm -rf "$HOME/Library/Application Support/Mullvad VPN" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Mullvad VPN" ]; then
    rm -f "$HOME/Library/Application Support/Mullvad VPN" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Mullvad VPN
echo "Removing $HOME/Library/Logs/Mullvad VPN..."
if [ -d "$HOME/Library/Logs/Mullvad VPN" ]; then
    rm -rf "$HOME/Library/Logs/Mullvad VPN" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Mullvad VPN" ]; then
    rm -f "$HOME/Library/Logs/Mullvad VPN" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/net.mullvad.vpn.helper.plist
echo "Removing $HOME/Library/Preferences/net.mullvad.vpn.helper.plist..."
if [ -d "$HOME/Library/Preferences/net.mullvad.vpn.helper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/net.mullvad.vpn.helper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/net.mullvad.vpn.helper.plist" ]; then
    rm -f "$HOME/Library/Preferences/net.mullvad.vpn.helper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/net.mullvad.vpn.plist
echo "Removing $HOME/Library/Preferences/net.mullvad.vpn.plist..."
if [ -d "$HOME/Library/Preferences/net.mullvad.vpn.plist" ]; then
    rm -rf "$HOME/Library/Preferences/net.mullvad.vpn.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/net.mullvad.vpn.plist" ]; then
    rm -f "$HOME/Library/Preferences/net.mullvad.vpn.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
