#!/bin/bash
# Uninstall script for Soulver
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Soulver..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Soulver if running..."
pkill -f "Soulver" 2>/dev/null || true

# Remove /Applications/Soulver 3.app
echo "Removing /Applications/Soulver 3.app..."
if [ -d "/Applications/Soulver 3.app" ]; then
    rm -rf "/Applications/Soulver 3.app" 2>/dev/null || true
elif [ -f "/Applications/Soulver 3.app" ]; then
    rm -f "/Applications/Soulver 3.app" 2>/dev/null || true
fi

# Remove binary /Applications/Soulver.app/Soulver 3.app/Contents/MacOS/CLI/soulver
echo "Removing binary /Applications/Soulver.app/Soulver 3.app/Contents/MacOS/CLI/soulver..."
if [ -f "/Applications/Soulver.app/Soulver 3.app/Contents/MacOS/CLI/soulver" ]; then
    rm -f "/Applications/Soulver.app/Soulver 3.app/Contents/MacOS/CLI/soulver" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/app.soulver.mac.QuicklookInSpotlight
echo "Removing $HOME/Library/Application Scripts/app.soulver.mac.QuicklookInSpotlight..."
if [ -d "$HOME/Library/Application Scripts/app.soulver.mac.QuicklookInSpotlight" ]; then
    rm -rf "$HOME/Library/Application Scripts/app.soulver.mac.QuicklookInSpotlight" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/app.soulver.mac.QuicklookInSpotlight" ]; then
    rm -f "$HOME/Library/Application Scripts/app.soulver.mac.QuicklookInSpotlight" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/app.soulver.mac
echo "Removing $HOME/Library/Application Support/app.soulver.mac..."
if [ -d "$HOME/Library/Application Support/app.soulver.mac" ]; then
    rm -rf "$HOME/Library/Application Support/app.soulver.mac" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/app.soulver.mac" ]; then
    rm -f "$HOME/Library/Application Support/app.soulver.mac" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/app.soulver.mac.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/app.soulver.mac.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/app.soulver.mac.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/app.soulver.mac.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/app.soulver.mac.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/app.soulver.mac.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Soulver 3
echo "Removing $HOME/Library/Application Support/Soulver 3..."
if [ -d "$HOME/Library/Application Support/Soulver 3" ]; then
    rm -rf "$HOME/Library/Application Support/Soulver 3" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Soulver 3" ]; then
    rm -f "$HOME/Library/Application Support/Soulver 3" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/app.soulver.mac
echo "Removing $HOME/Library/Caches/app.soulver.mac..."
if [ -d "$HOME/Library/Caches/app.soulver.mac" ]; then
    rm -rf "$HOME/Library/Caches/app.soulver.mac" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/app.soulver.mac" ]; then
    rm -f "$HOME/Library/Caches/app.soulver.mac" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/app.soulver.mac.QuicklookInSpotlight
echo "Removing $HOME/Library/Containers/app.soulver.mac.QuicklookInSpotlight..."
if [ -d "$HOME/Library/Containers/app.soulver.mac.QuicklookInSpotlight" ]; then
    rm -rf "$HOME/Library/Containers/app.soulver.mac.QuicklookInSpotlight" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/app.soulver.mac.QuicklookInSpotlight" ]; then
    rm -f "$HOME/Library/Containers/app.soulver.mac.QuicklookInSpotlight" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/group.app.soulver
echo "Removing $HOME/Library/Group Containers/group.app.soulver..."
if [ -d "$HOME/Library/Group Containers/group.app.soulver" ]; then
    rm -rf "$HOME/Library/Group Containers/group.app.soulver" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/group.app.soulver" ]; then
    rm -f "$HOME/Library/Group Containers/group.app.soulver" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/app.soulver.mac.binarycookies
echo "Removing $HOME/Library/HTTPStorages/app.soulver.mac.binarycookies..."
if [ -d "$HOME/Library/HTTPStorages/app.soulver.mac.binarycookies" ]; then
    rm -rf "$HOME/Library/HTTPStorages/app.soulver.mac.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/app.soulver.mac.binarycookies" ]; then
    rm -f "$HOME/Library/HTTPStorages/app.soulver.mac.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/app.soulver.mac.plist
echo "Removing $HOME/Library/Preferences/app.soulver.mac.plist..."
if [ -d "$HOME/Library/Preferences/app.soulver.mac.plist" ]; then
    rm -rf "$HOME/Library/Preferences/app.soulver.mac.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/app.soulver.mac.plist" ]; then
    rm -f "$HOME/Library/Preferences/app.soulver.mac.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/app.soulver.mac.savedState
echo "Removing $HOME/Library/Saved Application State/app.soulver.mac.savedState..."
if [ -d "$HOME/Library/Saved Application State/app.soulver.mac.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/app.soulver.mac.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/app.soulver.mac.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/app.soulver.mac.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
