#!/bin/bash
# Uninstall script for Element
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Element..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Element if running..."
pkill -f "Element" 2>/dev/null || true

# Remove /Applications/Element.app
echo "Removing /Applications/Element.app..."
if [ -d "/Applications/Element.app" ]; then
    rm -rf "/Applications/Element.app" 2>/dev/null || true
elif [ -f "/Applications/Element.app" ]; then
    rm -f "/Applications/Element.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Element
echo "Removing $HOME/Library/Application Support/Element..."
if [ -d "$HOME/Library/Application Support/Element" ]; then
    rm -rf "$HOME/Library/Application Support/Element" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Element" ]; then
    rm -f "$HOME/Library/Application Support/Element" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Riot
echo "Removing $HOME/Library/Application Support/Riot..."
if [ -d "$HOME/Library/Application Support/Riot" ]; then
    rm -rf "$HOME/Library/Application Support/Riot" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Riot" ]; then
    rm -f "$HOME/Library/Application Support/Riot" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/im.riot.app
echo "Removing $HOME/Library/Caches/im.riot.app..."
if [ -d "$HOME/Library/Caches/im.riot.app" ]; then
    rm -rf "$HOME/Library/Caches/im.riot.app" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/im.riot.app" ]; then
    rm -f "$HOME/Library/Caches/im.riot.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/im.riot.app.ShipIt
echo "Removing $HOME/Library/Caches/im.riot.app.ShipIt..."
if [ -d "$HOME/Library/Caches/im.riot.app.ShipIt" ]; then
    rm -rf "$HOME/Library/Caches/im.riot.app.ShipIt" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/im.riot.app.ShipIt" ]; then
    rm -f "$HOME/Library/Caches/im.riot.app.ShipIt" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/im.riot.app
echo "Removing $HOME/Library/HTTPStorages/im.riot.app..."
if [ -d "$HOME/Library/HTTPStorages/im.riot.app" ]; then
    rm -rf "$HOME/Library/HTTPStorages/im.riot.app" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/im.riot.app" ]; then
    rm -f "$HOME/Library/HTTPStorages/im.riot.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Riot
echo "Removing $HOME/Library/Logs/Riot..."
if [ -d "$HOME/Library/Logs/Riot" ]; then
    rm -rf "$HOME/Library/Logs/Riot" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Riot" ]; then
    rm -f "$HOME/Library/Logs/Riot" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/ByHost/im.riot.app.ShipIt.*.plist
echo "Removing $HOME/Library/Preferences/ByHost/im.riot.app.ShipIt.*.plist..."
if [ -d "$HOME/Library/Preferences/ByHost/im.riot.app.ShipIt.*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/ByHost/im.riot.app.ShipIt.*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/ByHost/im.riot.app.ShipIt.*.plist" ]; then
    rm -f "$HOME/Library/Preferences/ByHost/im.riot.app.ShipIt.*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/im.riot.app.helper.plist
echo "Removing $HOME/Library/Preferences/im.riot.app.helper.plist..."
if [ -d "$HOME/Library/Preferences/im.riot.app.helper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/im.riot.app.helper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/im.riot.app.helper.plist" ]; then
    rm -f "$HOME/Library/Preferences/im.riot.app.helper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/im.riot.app.plist
echo "Removing $HOME/Library/Preferences/im.riot.app.plist..."
if [ -d "$HOME/Library/Preferences/im.riot.app.plist" ]; then
    rm -rf "$HOME/Library/Preferences/im.riot.app.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/im.riot.app.plist" ]; then
    rm -f "$HOME/Library/Preferences/im.riot.app.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/im.riot.app.savedState
echo "Removing $HOME/Library/Saved Application State/im.riot.app.savedState..."
if [ -d "$HOME/Library/Saved Application State/im.riot.app.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/im.riot.app.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/im.riot.app.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/im.riot.app.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
